// GENERATED by tool/validate_content.py. Do not edit by hand.
//
// The version lives in pubspec.yaml. Restating it in Dart by hand is how
// five files ended up disagreeing about which release this was, so it is
// generated instead and the validator fails the build if it drifts.

const String appVersion = '4.7.0+53';
const String appVocabularyCount = '10000';
