import 'conversation.dart';
import 'models.dart';

/// A1 role-plays, second batch. Original text written for this
/// app.
const List<ConversationScenario> conversationA1MoreScenarios = <ConversationScenario>[
  ConversationScenario(
    id: 'cv-a1-05',
    level: CefrLevel.a1,
    emoji: '🥐',
    title: 'Beim Bäcker',
    setting: 'The small Bäckerei Körnerweg in the town of Alberbach, just after seven in the morning.',
    tutorRole: 'Verkäuferin (shop assistant)',
    learnerRole: 'Kunde (customer)',
    goal: 'Buy rolls and bread, ask what the cake costs, and pay at the counter.',
    usefulPhrases: <String>[
      'Ich hätte gern …',
      'Was kostet das?',
      'Das ist alles, danke.',
      'Ich zahle bar.',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Guten Morgen! Was darf es sein?',
        tutorEnglish: 'Good morning! What can I get you?',
        task: 'Greet the assistant and order some rolls.',
        keywords: <String>[
          'brötchen',
          'hätte gern',
          'möchte',
          'bitte',
          'vier',
          'zwei',
          'guten morgen',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Guten Morgen! Ich hätte gern vier Brötchen, bitte.',
        modelAnswerEnglish: 'Good morning! I would like four rolls, please.',
        quickReplies: <String>[
          'Guten Morgen! Zwei Brötchen, bitte.',
          'Ich möchte drei Brötchen, bitte.',
        ],
        coachTip: '„Ich hätte gern“ is the friendly way to order at a counter; „Ich will“ sounds blunt.',
      ),
      DialogueStep(
        tutorGerman: 'Gern. Möchten Sie auch ein Brot dazu?',
        tutorEnglish: 'Certainly. Would you like a loaf of bread as well?',
        task: 'Accept or decline, and name what you want.',
        keywords: <String>[
          'ja',
          'nehme',
          'brot',
          'brötchen',
          'bitte',
          'nein danke',
          'möchte',
          'danke',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Ja, ich nehme ein Vollkornbrot, bitte.',
        modelAnswerEnglish: 'Yes, I will take a wholemeal loaf, please.',
        quickReplies: <String>[
          'Nein danke, nur die Brötchen.',
          'Ja, bitte, ein kleines Brot.',
        ],
        coachTip: 'A short „Ja, bitte“ or „Nein, danke“ is already a complete and polite answer in a shop.',
      ),
      DialogueStep(
        tutorGerman: 'Wir haben heute frischen Apfelkuchen. Der ist noch warm.',
        tutorEnglish: 'We have fresh apple cake today. It is still warm.',
        task: 'Ask what the cake costs.',
        keywords: <String>[
          'was kostet',
          'kostet',
          'wie viel',
          'teuer',
          'preis',
          'kuchen',
          'stück',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Was kostet ein Stück Apfelkuchen, bitte?',
        modelAnswerEnglish: 'What does a slice of apple cake cost, please?',
        quickReplies: <String>[
          'Wie viel kostet ein Stück Kuchen?',
          'Wie teuer ist ein Stück?',
        ],
        coachTip: '„Was kostet …?“ and „Wie viel kostet …?“ are fully interchangeable here.',
      ),
      DialogueStep(
        tutorGerman: 'Ein Stück kostet zwei Euro vierzig. Soll ich Ihnen eins einpacken?',
        tutorEnglish: 'A slice costs two euros forty. Shall I wrap one up for you?',
        task: 'Answer yes or no, and signal that your order is finished.',
        keywords: <String>[
          'ja',
          'nein',
          'stück',
          'bitte',
          'das ist alles',
          'alles',
          'sonst nichts',
          'danke',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Ja, ein Stück bitte. Das ist alles.',
        modelAnswerEnglish: 'Yes, one slice please. That is everything.',
        quickReplies: <String>[
          'Nein danke, das ist alles.',
          'Ja gern, sonst nichts.',
        ],
        coachTip: '„Das ist alles“ closes an order and tells the seller to add it up.',
      ),
      DialogueStep(
        tutorGerman: 'Zusammen sind das sechs Euro zehn. Zahlen Sie bar oder mit Karte?',
        tutorEnglish: 'That is six euros ten altogether. Are you paying cash or by card?',
        task: 'Say how you want to pay.',
        keywords: <String>[
          'bar',
          'karte',
          'zahle',
          'mit karte',
          'bargeld',
          'euro',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Ich zahle bar, hier sind zehn Euro.',
        modelAnswerEnglish: 'I am paying cash, here is ten euros.',
        quickReplies: <String>[
          'Ich zahle mit Karte, bitte.',
          'Bar, bitte, ich habe Kleingeld.',
        ],
        coachTip: 'After „mit“ the article goes into the dative: mit der Karte, mit dem Handy.',
      ),
      DialogueStep(
        tutorGerman: 'Danke sehr. Hier ist Ihr Wechselgeld. Schönen Tag noch!',
        tutorEnglish: 'Thank you very much. Here is your change. Have a nice day!',
        task: 'Thank her and say goodbye.',
        keywords: <String>[
          'dank',
          'vielen dank',
          'wiedersehen',
          'tschüss',
          'gleichfalls',
          'ebenfalls',
          'ihnen auch',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Vielen Dank, Ihnen auch! Auf Wiedersehen.',
        modelAnswerEnglish: 'Many thanks, you too! Goodbye.',
        quickReplies: <String>[
          'Vielen Dank, tschüss!',
          'Danke schön, Ihnen auch!',
        ],
        coachTip: '„Gleichfalls“ and „Ihnen auch“ hand the good wish back in one short breath.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-a1-06',
    level: CefrLevel.a1,
    emoji: '🧭',
    title: 'Der Weg zum Markt',
    setting: 'A quiet street corner in the small town of Ellenhorst. You are holding a paper map and a woman stops next to you.',
    tutorRole: 'Passantin (passer-by)',
    learnerRole: 'Besucher (visitor)',
    goal: 'Ask the way to the market square, check the directions, and find out how long the walk takes.',
    usefulPhrases: <String>[
      'Entschuldigung, wo ist …?',
      'Wie komme ich zum Marktplatz?',
      'Ist das weit von hier?',
      'Wie lange dauert das?',
      'Vielen Dank für Ihre Hilfe.',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Sie schauen auf den Stadtplan. Suchen Sie etwas?',
        tutorEnglish: 'You are looking at the map. Are you looking for something?',
        task: 'Excuse yourself and ask the way to the market square.',
        keywords: <String>[
          'entschuldigung',
          'wie komme ich',
          'marktplatz',
          'markt',
          'wo ist',
          'suche',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Entschuldigung, wie komme ich zum Marktplatz?',
        modelAnswerEnglish: 'Excuse me, how do I get to the market square?',
        quickReplies: <String>[
          'Entschuldigung, wo ist der Marktplatz?',
          'Ich suche den Markt. Ist er weit?',
        ],
        coachTip: '„Wie komme ich zum …?“ uses zu plus dative: zum Markt, zur Post.',
      ),
      DialogueStep(
        tutorGerman: 'Der Marktplatz, ja. Gehen Sie hier geradeaus bis zur Ampel, dann links.',
        tutorEnglish: 'The market square, yes. Go straight ahead to the traffic light, then left.',
        task: 'Repeat the directions back to check that you understood.',
        keywords: <String>[
          'geradeaus',
          'links',
          'ampel',
          'also',
          'rechts',
          'dann',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Also geradeaus bis zur Ampel und dann links?',
        modelAnswerEnglish: 'So straight ahead to the traffic light and then left?',
        quickReplies: <String>[
          'Geradeaus und dann links, richtig?',
          'Also erst geradeaus, dann links an der Ampel?',
        ],
        coachTip: 'Starting with „Also …“ and ending with a rising question buys you a second hearing.',
      ),
      DialogueStep(
        tutorGerman: 'Genau. Nach der Ampel sehen Sie eine Kirche. Der Markt ist direkt dahinter.',
        tutorEnglish: 'Exactly. After the traffic light you will see a church. The market is right behind it.',
        task: 'Ask how far it is or how long the walk takes.',
        keywords: <String>[
          'weit',
          'wie lange',
          'dauert',
          'zu fuß',
          'minuten',
          'kilometer',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Ist das weit? Wie lange dauert das zu Fuß?',
        modelAnswerEnglish: 'Is that far? How long does it take on foot?',
        quickReplies: <String>[
          'Ist das weit? Kann ich zu Fuß gehen?',
          'Wie viele Minuten sind das zu Fuß?',
        ],
        coachTip: '„Wie lange dauert das?“ asks about time, „Wie weit ist das?“ asks about distance.',
      ),
      DialogueStep(
        tutorGerman: 'Zu Fuß sind das ungefähr zehn Minuten. Sie können auch den Bus nehmen.',
        tutorEnglish: 'On foot it is about ten minutes. You can also take the bus.',
        task: 'Say whether you will walk or take the bus, and give a short reason.',
        keywords: <String>[
          'zu fuß',
          'gehe',
          'laufe',
          'bus',
          'nehme',
          'weit',
          'minuten',
          'lieber',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Ich gehe zu Fuß, denn zehn Minuten sind nicht weit.',
        modelAnswerEnglish: 'I will walk, because ten minutes is not far.',
        quickReplies: <String>[
          'Ich nehme lieber den Bus.',
          'Zehn Minuten sind okay, ich laufe.',
        ],
        coachTip: '„denn“ joins two main clauses and leaves the verb in second position: …, denn zehn Minuten sind nicht weit.',
      ),
      DialogueStep(
        tutorGerman: 'Beides geht gut. Zu Fuß kommen Sie an einem kleinen Park vorbei.',
        tutorEnglish: 'Both work well. On foot you come past a small park.',
        task: 'Ask one more question about something on the way, for example a bakery, a bank or a toilet.',
        keywords: <String>[
          'gibt es',
          'dort',
          'bäckerei',
          'bank',
          'apotheke',
          'toilette',
          'supermarkt',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Gibt es dort auch eine Bäckerei?',
        modelAnswerEnglish: 'Is there a bakery there as well?',
        quickReplies: <String>[
          'Gibt es dort eine Bank?',
          'Ist dort auch eine Apotheke?',
        ],
        coachTip: '„Gibt es …?“ is the all-purpose way to ask whether something exists nearby.',
      ),
      DialogueStep(
        tutorGerman: 'Ja, gleich neben der Kirche. Dann viel Spaß auf dem Markt!',
        tutorEnglish: 'Yes, right next to the church. Enjoy the market!',
        task: 'Thank the passer-by warmly and say goodbye.',
        keywords: <String>[
          'dank',
          'vielen dank',
          'hilfe',
          'wiedersehen',
          'tschüss',
          'nett',
          'schönen tag',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Vielen Dank für Ihre Hilfe. Auf Wiedersehen!',
        modelAnswerEnglish: 'Many thanks for your help. Goodbye!',
        quickReplies: <String>[
          'Danke schön, tschüss!',
          'Das ist sehr nett, vielen Dank!',
        ],
        coachTip: '„Danke für Ihre Hilfe“ keeps the formal Sie form right to the end of the exchange.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-a1-07',
    level: CefrLevel.a1,
    emoji: '🎫',
    title: 'Der Fahrkartenautomat',
    setting: 'The platform of the little station in Talbrück. The ticket machine shows five buttons and you are not sure which one to press.',
    tutorRole: 'Mitarbeiterin der Bahn (station staff)',
    learnerRole: 'Reisender (traveller)',
    goal: 'Get help with the machine and buy a ticket to the next town.',
    usefulPhrases: <String>[
      'Ich verstehe das nicht.',
      'Können Sie mir helfen?',
      'Eine Fahrkarte nach Grünsee, bitte.',
      'Einfach oder hin und zurück?',
      'Auf welchem Gleis?',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Sie stehen schon eine Weile vor dem Automaten. Alles in Ordnung?',
        tutorEnglish: 'You have been standing at the machine for a while. Is everything all right?',
        task: 'Say that you do not understand the machine and ask for help.',
        keywords: <String>[
          'verstehe',
          'nicht',
          'helfen',
          'hilfe',
          'automat',
          'können sie',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Ich verstehe den Automaten nicht. Können Sie mir helfen?',
        modelAnswerEnglish: 'I do not understand the machine. Can you help me?',
        quickReplies: <String>[
          'Nein, ich verstehe den Automaten nicht.',
          'Können Sie mir bitte helfen?',
        ],
        coachTip: 'Modal verbs send the main verb to the end: Können Sie mir helfen?',
      ),
      DialogueStep(
        tutorGerman: 'Kein Problem, der Automat ist wirklich kompliziert. Wohin möchten Sie fahren?',
        tutorEnglish: 'No problem, the machine really is complicated. Where do you want to travel to?',
        task: 'Say where you want to travel to.',
        keywords: <String>[
          'möchte',
          'nach',
          'fahren',
          'grünsee',
          'bitte',
          'fahrkarte',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Ich möchte nach Grünsee fahren, bitte.',
        modelAnswerEnglish: 'I would like to travel to Grünsee, please.',
        quickReplies: <String>[
          'Nach Grünsee, bitte.',
          'Ich brauche eine Fahrkarte nach Grünsee.',
        ],
        coachTip: 'Town names take „nach“ with no article: nach Grünsee, nach Talbrück.',
      ),
      DialogueStep(
        tutorGerman: 'Grünsee, gut. Der Automat fragt jetzt: einfach oder hin und zurück?',
        tutorEnglish: 'Grünsee, good. The machine is now asking: one way or return?',
        task: 'Choose one option and say when you are coming back, if you are.',
        keywords: <String>[
          'hin und zurück',
          'zurück',
          'einfach',
          'heute',
          'abend',
          'komme',
          'bitte',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Hin und zurück, bitte. Ich komme heute Abend zurück.',
        modelAnswerEnglish: 'Return, please. I am coming back this evening.',
        quickReplies: <String>[
          'Nur einfach, bitte.',
          'Hin und zurück. Ich fahre morgen zurück.',
        ],
        coachTip: '„zurück“ is a separable prefix and lands at the very end: Ich komme heute Abend zurück.',
      ),
      DialogueStep(
        tutorGerman: 'Jetzt kommt der Preis: neun Euro achtzig. Der Automat nimmt leider keine Scheine.',
        tutorEnglish: 'Now the price appears: nine euros eighty. Unfortunately the machine does not take notes.',
        task: 'Say how you can pay, or ask about another way of paying.',
        keywords: <String>[
          'karte',
          'mit karte',
          'bezahlen',
          'münzen',
          'kleingeld',
          'kann ich',
          'bar',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Ich habe kein Bargeld. Kann ich mit Karte bezahlen?',
        modelAnswerEnglish: 'I have no cash. Can I pay by card?',
        quickReplies: <String>[
          'Ich habe Münzen. Kann ich damit bezahlen?',
          'Kann ich auch mit dem Handy bezahlen?',
        ],
        coachTip: '„mit“ always takes the dative: mit der Karte, mit dem Handy, mit Kleingeld.',
      ),
      DialogueStep(
        tutorGerman: 'Karte und Münzen gehen beide. Die Karte halten Sie einfach unten an das Lesegerät.',
        tutorEnglish: 'Card and coins both work. You just hold the card against the reader at the bottom.',
        task: 'Ask whether you also have to print the ticket.',
        keywords: <String>[
          'muss ich',
          'drucken',
          'fahrkarte',
          'ticket',
          'papier',
          'brauche',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Muss ich die Fahrkarte auch drucken?',
        modelAnswerEnglish: 'Do I also have to print the ticket?',
        quickReplies: <String>[
          'Brauche ich auch ein Papierticket?',
          'Muss ich das Ticket hier abholen?',
        ],
        coachTip: '„müssen“ pushes the infinitive to the end: Muss ich die Fahrkarte drucken?',
      ),
      DialogueStep(
        tutorGerman: 'Die Fahrkarte kommt gleich unten heraus. Der Zug fährt auf Gleis zwei.',
        tutorEnglish: 'The ticket comes out at the bottom in a moment. The train leaves from platform two.',
        task: 'Thank her and check the platform number.',
        keywords: <String>[
          'dank',
          'vielen dank',
          'gleis',
          'zwei',
          'richtig',
          'stimmt',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Vielen Dank! Gleis zwei, richtig?',
        modelAnswerEnglish: 'Many thanks! Platform two, right?',
        quickReplies: <String>[
          'Danke schön! Also Gleis zwei?',
          'Gleis zwei, stimmt das?',
        ],
        coachTip: 'Adding „richtig?“ or „stimmt das?“ turns a plain statement into a quick check.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-a1-08',
    level: CefrLevel.a1,
    emoji: '🏠',
    title: 'Neu im Haus',
    setting: 'The stairwell of a small block of flats in Weidegrund. You are carrying a box up the stairs and meet the woman from the flat below.',
    tutorRole: 'Nachbarin (neighbour)',
    learnerRole: 'neuer Mieter (new tenant)',
    goal: 'Introduce yourself, say where you are from and what you do, and end on a friendly next step.',
    usefulPhrases: <String>[
      'Ich bin neu hier.',
      'Ich heiße …',
      'Ich komme aus …',
      'Freut mich!',
      'Bis bald!',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Hallo! Sie sind neu hier im Haus, oder? Ich wohne unten links.',
        tutorEnglish: 'Hello! You are new here in the building, right? I live downstairs on the left.',
        task: 'Greet her and introduce yourself by name.',
        keywords: <String>[
          'ich heiße',
          'heiße',
          'hallo',
          'guten tag',
          'neu',
          'mein name',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Hallo! Ja, ich bin neu. Ich heiße Nuray.',
        modelAnswerEnglish: 'Hello! Yes, I am new. My name is Nuray.',
        quickReplies: <String>[
          'Guten Tag! Ich heiße Nuray Deniz.',
          'Hallo! Mein Name ist Bekir Aydemir.',
        ],
        coachTip: '„Ich heiße …“ and „Mein Name ist …“ do the same job; the first is more everyday.',
      ),
      DialogueStep(
        tutorGerman: 'Freut mich! Ich bin Marlies Ostwald. Und woher kommen Sie?',
        tutorEnglish: 'Nice to meet you! I am Marlies Ostwald. And where are you from?',
        task: 'Say where you come from and how long you have lived here.',
        keywords: <String>[
          'komme aus',
          'bin aus',
          'wohne',
          'seit',
          'monat',
          'jahr',
          'hier',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Ich komme aus Ankara und wohne seit zwei Monaten hier.',
        modelAnswerEnglish: 'I come from Ankara and have lived here for two months.',
        quickReplies: <String>[
          'Aus Portugal. Ich bin seit einem Jahr in Deutschland.',
          'Ich bin aus Vietnam und wohne seit Mai hier.',
        ],
        coachTip: '„seit“ takes the dative and pairs with the present tense: Ich wohne seit zwei Monaten hier.',
      ),
      DialogueStep(
        tutorGerman: 'Ah, schön. Und arbeiten Sie hier in der Stadt oder lernen Sie noch?',
        tutorEnglish: 'Ah, lovely. And do you work here in town or are you still studying?',
        task: 'Say what you do and where.',
        keywords: <String>[
          'arbeite',
          'studiere',
          'lerne',
          'büro',
          'stadt',
          'schule',
          'deutsch',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Ich arbeite in einem Büro in der Stadt.',
        modelAnswerEnglish: 'I work in an office in town.',
        quickReplies: <String>[
          'Ich studiere und lerne auch Deutsch.',
          'Ich arbeite in einer kleinen Schule.',
        ],
        coachTip: 'The verb stays in second position: Ich arbeite hier, but Hier arbeite ich.',
      ),
      DialogueStep(
        tutorGerman: 'Interessant. Hier im Haus ist es meistens ruhig. Der Müll kommt am Dienstag raus.',
        tutorEnglish: 'Interesting. It is usually quiet here in the building. The bins go out on Tuesday.',
        task: 'Ask a practical question about the building, for example the post, the cellar or parking.',
        keywords: <String>[
          'wo ist',
          'briefkasten',
          'post',
          'müll',
          'keller',
          'parken',
          'wann',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Danke! Und wo ist der Briefkasten für meine Post?',
        modelAnswerEnglish: 'Thanks! And where is the letterbox for my post?',
        quickReplies: <String>[
          'Wann kommt die Post normalerweise?',
          'Wo ist der Keller? Ich habe noch keinen Schlüssel.',
        ],
        coachTip: 'W-questions put the question word first and the verb straight after: Wo ist der Keller?',
      ),
      DialogueStep(
        tutorGerman: 'Fragen Sie mich gern alles. Der Briefkasten ist neben der Haustür, der Keller ist unten rechts.',
        tutorEnglish: 'Feel free to ask me anything. The letterbox is next to the front door, the cellar is downstairs on the right.',
        task: 'Offer something friendly, for example a coffee or your help.',
        keywords: <String>[
          'kaffee',
          'möchten sie',
          'trinken',
          'gern',
          'hilfe',
          'helfen',
          'klopfen',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Super, danke. Möchten Sie bald einmal Kaffee trinken?',
        modelAnswerEnglish: 'Great, thanks. Would you like to have a coffee some time soon?',
        quickReplies: <String>[
          'Sie können gern bei mir klopfen.',
          'Kommen Sie gern mal auf einen Kaffee vorbei.',
        ],
        coachTip: 'An invitation in the Sie form stays a question: Möchten Sie …? — polite and never pushy.',
      ),
      DialogueStep(
        tutorGerman: 'Sehr gern! Ich bin fast immer zu Hause. Dann bis bald!',
        tutorEnglish: 'I would love to! I am at home almost all the time. See you soon then!',
        task: 'Say goodbye and name a rough time you could meet.',
        keywords: <String>[
          'bis bald',
          'samstag',
          'sonntag',
          'nachmittag',
          'abend',
          'tschüss',
          'vielleicht',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Bis bald! Vielleicht am Samstagnachmittag?',
        modelAnswerEnglish: 'See you soon! Maybe on Saturday afternoon?',
        quickReplies: <String>[
          'Tschüss! Vielleicht am Sonntag?',
          'Bis bald! Freitagabend passt mir gut.',
        ],
        coachTip: 'Days and parts of the day take „am“: am Samstag, am Abend. Joined together they become one word: am Samstagnachmittag.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-a1-09',
    level: CefrLevel.a1,
    emoji: '📚',
    title: 'In der Bücherei',
    setting: 'Die Stadtbücherei Lindenau an einem ruhigen Nachmittag.',
    tutorRole: 'Bibliothekar',
    learnerRole: 'Leser oder Leserin',
    goal: 'Zwei Bücher zu spät zurückgeben, die Gebühr bezahlen und nach etwas Neuem fragen.',
    usefulPhrases: <String>[
      'Ich möchte die Bücher zurückgeben.',
      'Das tut mir leid.',
      'Was kostet die Gebühr?',
      'Haben Sie ein Buch über …?',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Guten Tag. Wie kann ich Ihnen helfen?',
        tutorEnglish: 'Hello. How can I help you?',
        task: 'Greet the librarian and say you want to return two books.',
        keywords: <String>[
          'möchte',
          'bücher',
          'zurückgeben',
          'zwei',
          'abgeben',
          'guten tag',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Guten Tag. Ich möchte zwei Bücher zurückgeben.',
        modelAnswerEnglish: 'Hello. I would like to return two books.',
        quickReplies: <String>[
          'Hallo, ich bringe zwei Bücher zurück.',
          'Ich möchte diese Bücher abgeben.',
        ],
        coachTip: 'With a modal verb like „möchte“, the main verb moves to the end of the sentence as an infinitive.',
      ),
      DialogueStep(
        tutorGerman: 'Danke. Ich sehe im System, die Bücher sind seit einer Woche fällig.',
        tutorEnglish: 'Thank you. I can see in the system that the books have been due for a week.',
        task: 'Apologise for being late and give a short reason.',
        keywords: <String>[
          'tut mir leid',
          'entschuldigung',
          'krank',
          'war',
          'arbeit',
          'vergessen',
          'leider',
        ],
        requiredHits: 2,
        minWords: 5,
        modelAnswer: 'Das tut mir leid. Ich war krank und komme erst heute.',
        modelAnswerEnglish: 'I am sorry. I was ill and am only coming today.',
        quickReplies: <String>[
          'Entschuldigung, ich war im Urlaub.',
          'Es tut mir leid, ich hatte viel Arbeit.',
        ],
        coachTip: 'A German apology usually pairs „Das tut mir leid“ with a short reason in the very same breath.',
      ),
      DialogueStep(
        tutorGerman: 'Kein Problem, das passiert oft. Die Gebühr beträgt zwei Euro.',
        tutorEnglish: 'No problem, that happens often. The fee is two euros.',
        task: 'Say how you want to pay the fee.',
        keywords: <String>[
          'zahle',
          'karte',
          'bar',
          'gebühr',
          'euro',
          'handy',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Gut, ich bezahle die Gebühr mit Karte.',
        modelAnswerEnglish: 'Fine, I will pay the fee by card.',
        quickReplies: <String>[
          'Ich zahle bar, bitte.',
          'Kann ich mit Karte zahlen?',
        ],
        coachTip: 'The preposition „mit“ takes the dative, so you pay mit Karte or mit dem Handy.',
      ),
      DialogueStep(
        tutorGerman: 'Danke, das ist erledigt. Möchten Sie noch etwas ausleihen?',
        tutorEnglish: 'Thanks, that is settled. Would you like to borrow anything else?',
        task: 'Ask whether the library has a book on a topic you like.',
        keywords: <String>[
          'haben sie',
          'buch',
          'über',
          'suche',
          'gibt es',
          'kochen',
          'krimi',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Haben Sie ein Buch über Kochen für Anfänger?',
        modelAnswerEnglish: 'Do you have a book about cooking for beginners?',
        quickReplies: <String>[
          'Gibt es hier Krimis auf Deutsch?',
          'Ich suche ein Buch für Anfänger.',
        ],
        coachTip: 'Yes-no questions put the conjugated verb first: „Haben Sie …?“ rather than Sie haben.',
      ),
      DialogueStep(
        tutorGerman: 'Ja, bei uns finden Sie einiges. Das Regal hinten links ist voll davon. Wir schließen um achtzehn Uhr.',
        tutorEnglish: 'Yes, we have plenty. The shelf at the back on the left is full of them. We close at six.',
        task: 'Thank the librarian and say goodbye.',
        keywords: <String>[
          'dank',
          'vielen dank',
          'wiedersehen',
          'tschüss',
          'hilfe',
          'schönen tag',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Vielen Dank für die Hilfe. Auf Wiedersehen!',
        modelAnswerEnglish: 'Many thanks for your help. Goodbye!',
        quickReplies: <String>[
          'Danke für alles, tschüss!',
          'Vielen Dank, schönen Tag noch!',
        ],
        coachTip: 'A polite ending in German pairs thanks with a farewell such as „Auf Wiedersehen“.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-a1-10',
    level: CefrLevel.a1,
    emoji: '🍎',
    title: 'Am Marktstand',
    setting: 'Ein Obst- und Gemüsestand auf dem Wochenmarkt am Rosenplatz.',
    tutorRole: 'Marktverkäufer',
    learnerRole: 'Kunde oder Kundin',
    goal: 'Obst und Gemüse bestellen, nach dem Preis fragen und bezahlen.',
    usefulPhrases: <String>[
      'Ich nehme ein Kilo …',
      'Was kostet das?',
      'Das ist alles, danke.',
      'Ich zahle bar.',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Guten Morgen! Alles frisch von heute. Was darf ich Ihnen geben?',
        tutorEnglish: 'Good morning! Everything is fresh today. What can I get you?',
        task: 'Order a quantity of fruit.',
        keywords: <String>[
          'nehme',
          'möchte',
          'kilo',
          'äpfel',
          'bitte',
          'hätte gern',
          'erdbeeren',
          'gramm',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Guten Morgen. Ich nehme ein Kilo Äpfel, bitte.',
        modelAnswerEnglish: 'Good morning. I will take a kilo of apples, please.',
        quickReplies: <String>[
          'Ich hätte gern zwei Kilo Kartoffeln.',
          'Ich möchte ein Pfund Erdbeeren.',
        ],
        coachTip: 'Quantities need no preposition in German: say ein Kilo Äpfel, never ein Kilo von Äpfeln.',
      ),
      DialogueStep(
        tutorGerman: 'Sehr gern. Bei uns kommt alles von einem Hof hier in der Nähe.',
        tutorEnglish: 'Gladly. Everything we sell comes from a farm nearby.',
        task: 'Ask what it costs.',
        keywords: <String>[
          'was kostet',
          'kostet',
          'wie teuer',
          'teuer',
          'preis',
          'kilo',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Schön. Was kostet ein Kilo?',
        modelAnswerEnglish: 'Nice. What does a kilo cost?',
        quickReplies: <String>[
          'Wie teuer sind die Äpfel?',
          'Was kosten die Erdbeeren?',
        ],
        coachTip: 'German asks about price with „Was kostet …?“, not with a word-for-word how much.',
      ),
      DialogueStep(
        tutorGerman: 'Zwei Euro achtzig das Kilo. Die Möhren sind übrigens auch sehr gut.',
        tutorEnglish: 'Two euros eighty a kilo. The carrots are very good too, by the way.',
        task: 'Add a vegetable to your order.',
        keywords: <String>[
          'nehme',
          'möhren',
          'auch',
          'bund',
          'tomaten',
          'salat',
          'gemüse',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Gut, dann nehme ich auch ein Bund Möhren.',
        modelAnswerEnglish: 'Good, then I will also take a bunch of carrots.',
        quickReplies: <String>[
          'Ich möchte auch Tomaten, bitte.',
          'Ich nehme noch einen Salat.',
        ],
        coachTip: 'Starting a sentence with „dann“ pushes the subject behind the verb: dann nehme ich.',
      ),
      DialogueStep(
        tutorGerman: 'Alles klar. Möchten Sie sonst noch etwas?',
        tutorEnglish: 'All right. Would you like anything else?',
        task: 'Say that is everything.',
        keywords: <String>[
          'das ist alles',
          'alles',
          'nein',
          'dank',
          'nichts mehr',
          'reicht',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Nein danke, das ist alles.',
        modelAnswerEnglish: 'No thanks, that is everything.',
        quickReplies: <String>[
          'Das reicht, vielen Dank.',
          'Nein, sonst nichts mehr.',
        ],
        coachTip: 'Pairing „nein“ with danke keeps a refusal friendly, since danke on its own is ambiguous.',
      ),
      DialogueStep(
        tutorGerman: 'Das macht dann fünf Euro sechzig zusammen.',
        tutorEnglish: 'That comes to five euros sixty altogether.',
        task: 'Say how you are paying.',
        keywords: <String>[
          'zahle',
          'bar',
          'hier',
          'euro',
          'karte',
          'stimmt so',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Hier sind sechs Euro. Ich zahle bar.',
        modelAnswerEnglish: 'Here are six euros. I am paying cash.',
        quickReplies: <String>[
          'Kann ich mit Karte zahlen?',
          'Hier, bitte. Stimmt so.',
        ],
        coachTip: 'Paying cash is simply „Ich zahle bar“, with no article in front of bar.',
      ),
      DialogueStep(
        tutorGerman: 'Danke schön. Nächste Woche haben wir wieder Kirschen.',
        tutorEnglish: 'Thank you. Next week we will have cherries again.',
        task: 'Say goodbye and that you will come back.',
        keywords: <String>[
          'komme',
          'wieder',
          'nächste woche',
          'tschüss',
          'bis dann',
          'dank',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Schön, dann komme ich nächste Woche wieder. Tschüss!',
        modelAnswerEnglish: 'Nice, then I will come back next week. Bye!',
        quickReplies: <String>[
          'Bis nächste Woche, tschüss!',
          'Auf Wiedersehen und danke!',
        ],
        coachTip: 'Time expressions such as nächste Woche stand in the accusative and need no preposition.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-a1-11',
    level: CefrLevel.a1,
    emoji: '💊',
    title: 'In der Apotheke',
    setting: 'Die Apotheke am Ahornweg, kurz vor Feierabend.',
    tutorRole: 'Apothekerin',
    learnerRole: 'Kunde oder Kundin',
    goal: 'Sagen, wie du dich fühlst, und etwas gegen die Erkältung aussuchen.',
    usefulPhrases: <String>[
      'Ich habe eine Erkältung.',
      'Mein Hals tut weh.',
      'Haben Sie etwas dagegen?',
      'Brauche ich ein Rezept?',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Guten Tag. Was kann ich für Sie tun?',
        tutorEnglish: 'Hello. What can I do for you?',
        task: 'Greet the pharmacist and say you have a cold.',
        keywords: <String>[
          'erkältung',
          'ich habe',
          'seit',
          'gestern',
          'husten',
          'schnupfen',
          'krank',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Guten Tag. Ich habe seit gestern eine Erkältung.',
        modelAnswerEnglish: 'Hello. I have had a cold since yesterday.',
        quickReplies: <String>[
          'Ich bin seit drei Tagen krank.',
          'Ich habe Husten und Schnupfen.',
        ],
        coachTip: 'The preposition „seit“ takes the dative and marks something that began earlier and still lasts.',
      ),
      DialogueStep(
        tutorGerman: 'Das hört man zurzeit oft. Wie fühlen Sie sich denn genau?',
        tutorEnglish: 'We hear that a lot at the moment. How exactly are you feeling?',
        task: 'Describe two symptoms.',
        keywords: <String>[
          'halsschmerzen',
          'kopf',
          'tut weh',
          'husten',
          'schnupfen',
          'müde',
          'fieber',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Ich habe Halsschmerzen und mein Kopf tut weh.',
        modelAnswerEnglish: 'I have a sore throat and my head hurts.',
        quickReplies: <String>[
          'Ich huste viel und bin müde.',
          'Mein Hals tut weh und ich habe Schnupfen.',
        ],
        coachTip: 'German names pain either with a compound noun like Halsschmerzen or with the phrase tut weh.',
      ),
      DialogueStep(
        tutorGerman: 'Verstehe. Wir haben Lutschtabletten, einen Tee und ein Nasenspray.',
        tutorEnglish: 'I see. We have lozenges, a tea and a nasal spray.',
        task: 'Choose one of the options and ask for it politely.',
        keywords: <String>[
          'nehme',
          'tee',
          'bitte',
          'lutschtabletten',
          'nasenspray',
          'möchte',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Ich nehme gern den Tee, bitte.',
        modelAnswerEnglish: 'I will happily take the tea, please.',
        quickReplies: <String>[
          'Die Lutschtabletten, bitte.',
          'Ich möchte lieber das Nasenspray.',
        ],
        coachTip: 'Adding „gern“ after the verb turns a bare request into a friendly one.',
      ),
      DialogueStep(
        tutorGerman: 'Gute Wahl. Das kostet vier Euro neunzig.',
        tutorEnglish: 'Good choice. That costs four euros ninety.',
        task: 'Ask whether you need a prescription.',
        keywords: <String>[
          'rezept',
          'brauche',
          'dafür',
          'ohne rezept',
          'muss ich',
          'arzt',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Brauche ich dafür ein Rezept?',
        modelAnswerEnglish: 'Do I need a prescription for that?',
        quickReplies: <String>[
          'Ist das ohne Rezept möglich?',
          'Muss ich zum Arzt gehen?',
        ],
        coachTip: 'A yes-no question begins with the conjugated verb: „Brauche ich …?“',
      ),
      DialogueStep(
        tutorGerman: 'Nein, das bekommen Sie hier frei. Trinken Sie viel und ruhen Sie sich aus.',
        tutorEnglish: 'No, you can get that here without one. Drink plenty and get some rest.',
        task: 'Thank her and ask what to do next.',
        keywords: <String>[
          'arzt',
          'soll ich',
          'dank',
          'gehen',
          'besser',
          'wieder',
          'trinken',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Danke. Soll ich dann zum Arzt gehen?',
        modelAnswerEnglish: 'Thank you. Should I go to the doctor then?',
        quickReplies: <String>[
          'Danke, und wann komme ich wieder?',
          'Soll ich noch etwas trinken?',
        ],
        coachTip: 'The modal „soll“ asks for a recommendation, while muss would ask about an obligation.',
      ),
      DialogueStep(
        tutorGerman: 'Wenn es länger als eine Woche dauert, fragen Sie bitte Ihre Ärztin. Gute Besserung!',
        tutorEnglish: 'If it lasts longer than a week, please ask your doctor. Get well soon!',
        task: 'Thank her again and say goodbye.',
        keywords: <String>[
          'dank',
          'vielen dank',
          'wiedersehen',
          'tschüss',
          'mache ich',
          'hilfe',
          'schönen abend',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Danke schön, das mache ich. Auf Wiedersehen!',
        modelAnswerEnglish: 'Thank you, I will do that. Goodbye!',
        quickReplies: <String>[
          'Vielen Dank für Ihre Hilfe.',
          'Danke, tschüss und schönen Abend!',
        ],
        coachTip: 'Closing with „Auf Wiedersehen“ keeps the formal Sie you have used all the way through.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-a1-12',
    level: CefrLevel.a1,
    emoji: '📱',
    title: 'Verabredung am Samstag',
    setting: 'Ein kurzes Telefonat mit einer Freundin am Donnerstagabend.',
    tutorRole: 'Freundin Nadja',
    learnerRole: 'Freund oder Freundin',
    goal: 'Eine Aktivität, eine Uhrzeit und einen Treffpunkt für Samstag vereinbaren.',
    usefulPhrases: <String>[
      'Hast du am Samstag Zeit?',
      'Wollen wir ins Kino gehen?',
      'Passt dir sieben Uhr?',
      'Wir treffen uns vor dem Kino.',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Hallo! Schön, dass du anrufst. Wie geht es dir?',
        tutorEnglish: 'Hi! Nice that you are calling. How are you?',
        task: 'Say how you are and ask the same back.',
        keywords: <String>[
          'gut',
          'mir geht es',
          'und dir',
          'und du',
          'dank',
          'müde',
          'super',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Hallo Nadja! Mir geht es gut. Und dir?',
        modelAnswerEnglish: 'Hi Nadja! I am doing well. And you?',
        quickReplies: <String>[
          'Danke, sehr gut. Wie geht es dir?',
          'Ich bin ein bisschen müde. Und du?',
        ],
        coachTip: 'This phrase uses the dative: mir geht es gut, and the short question back is „Und dir?“',
      ),
      DialogueStep(
        tutorGerman: 'Das freut mich. Ich habe am Wochenende endlich frei.',
        tutorEnglish: 'Glad to hear it. I finally have the weekend off.',
        task: 'Suggest doing something together on Saturday.',
        keywords: <String>[
          'wollen wir',
          'samstag',
          'kino',
          'gehen',
          'hast du',
          'zeit',
          'schwimmen',
          'treffen',
        ],
        requiredHits: 2,
        minWords: 5,
        modelAnswer: 'Super! Wollen wir am Samstag ins Kino gehen?',
        modelAnswerEnglish: 'Great! Shall we go to the cinema on Saturday?',
        quickReplies: <String>[
          'Hast du am Samstag Zeit für einen Kaffee?',
          'Wir können zusammen schwimmen gehen.',
        ],
        coachTip: 'A suggestion often opens with „Wollen wir …?“ and keeps the infinitive at the very end.',
      ),
      DialogueStep(
        tutorGerman: 'Gute Idee! Am Nachmittag habe ich noch einen Termin, aber danach passt es.',
        tutorEnglish: 'Good idea! I still have an appointment in the afternoon, but after that it works.',
        task: 'Propose a time.',
        keywords: <String>[
          'um sieben',
          'uhr',
          'treffen',
          'halb acht',
          'abends',
          'passt',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Dann treffen wir uns um sieben Uhr.',
        modelAnswerEnglish: 'Then let us meet at seven o clock.',
        quickReplies: <String>[
          'Passt dir halb acht?',
          'Geht es um acht Uhr abends?',
        ],
        coachTip: 'Clock times take the preposition „um“: um sieben Uhr, um halb acht.',
      ),
      DialogueStep(
        tutorGerman: 'Das klingt gut. Und wo treffen wir uns?',
        tutorEnglish: 'That sounds good. And where shall we meet?',
        task: 'Name a meeting place.',
        keywords: <String>[
          'treffen',
          'vor dem',
          'kino',
          'marktplatz',
          'am eingang',
          'zu mir',
          'nach hause',
          'bahnhof',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Wir treffen uns vor dem Kino am Marktplatz.',
        modelAnswerEnglish: 'We will meet in front of the cinema on the market square.',
        quickReplies: <String>[
          'Am Eingang vom Kino, okay?',
          'Komm einfach zu mir nach Hause.',
        ],
        coachTip: 'For a fixed location „vor“ takes the dative, so it is vor dem Kino.',
      ),
      DialogueStep(
        tutorGerman: 'Perfekt, das kenne ich. Soll ich noch jemanden mitbringen?',
        tutorEnglish: 'Perfect, I know that spot. Should I bring anyone along?',
        task: 'Say whether she should bring someone, with a short reason.',
        keywords: <String>[
          'ja gern',
          'gern',
          'bring',
          'mag',
          'nein',
          'lieber',
          'nur wir',
          'freund',
        ],
        requiredHits: 2,
        minWords: 4,
        modelAnswer: 'Ja gern, bring Tobias mit. Er mag Filme.',
        modelAnswerEnglish: 'Yes, please bring Tobias. He likes films.',
        quickReplies: <String>[
          'Nein, lieber nur wir zwei.',
          'Ja, bring gern deine Freundin mit.',
        ],
        coachTip: 'Separable verbs split in an imperative: bring Tobias mit, with mit at the end.',
      ),
      DialogueStep(
        tutorGerman: 'Alles klar, dann bis Samstag. Ich freue mich!',
        tutorEnglish: 'All right, see you on Saturday then. I am looking forward to it!',
        task: 'Confirm the plan and say goodbye.',
        keywords: <String>[
          'bis samstag',
          'tschüss',
          'freue mich',
          'auch',
          'bis dann',
          'ciao',
        ],
        requiredHits: 2,
        minWords: 3,
        modelAnswer: 'Ich freue mich auch. Bis Samstag, tschüss!',
        modelAnswerEnglish: 'I am looking forward to it too. See you Saturday, bye!',
        quickReplies: <String>[
          'Bis dann, ich freue mich!',
          'Super, dann bis Samstag. Ciao!',
        ],
        coachTip: 'German says goodbye with bis plus a time word: bis Samstag, bis dann, bis später.',
      ),
    ],
  ),
];
