import 'conversation.dart';
import 'models.dart';

/// B1 role-plays, second batch. Original text written for this
/// app.
const List<ConversationScenario> conversationB1MoreScenarios = <ConversationScenario>[
  ConversationScenario(
    id: 'cv-b1-06',
    level: CefrLevel.b1,
    emoji: '🎒',
    title: 'Elternsprechstunde',
    setting: 'A quiet classroom at the Ahornweg-Gesamtschule after lessons, where parents are seen one after the other.',
    tutorRole: 'Herr Talberg, the class teacher, who has the register in front of him and keeps the meeting moving.',
    learnerRole: 'You, the parent of Jonas, twelve years old, who has stopped handing in his homework.',
    goal: 'Explain what has changed at home, disagree politely with one explanation and agree on a concrete plan.',
    usefulPhrases: <String>[
      'Danke, dass Sie sich Zeit nehmen.',
      'Zu Hause sieht es etwas anders aus.',
      'Das wusste ich so noch nicht.',
      'Könnten wir das so vereinbaren?',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Guten Tag, schön, dass Sie kommen konnten. Ich habe Sie eingeladen, weil Jonas seit etwa sechs Wochen fast keine Hausaufgaben mehr abgibt. Wie erleben Sie das zu Hause?',
        tutorEnglish: 'Hello, good that you could come. I invited you because Jonas has handed in almost no homework for about six weeks. How do you experience that at home?',
        task: 'Describe what you notice at home and name one reason you suspect.',
        keywords: <String>[
          'zu hause',
          'schreibtisch',
          'weil',
          'umzug',
          'freunde',
          'kaum',
          'müde',
          'still',
        ],
        requiredHits: 2,
        minWords: 12,
        modelAnswer: 'Zu Hause sitzt er zwar am Schreibtisch, aber er kommt nicht voran, weil er seit dem Umzug kaum noch mit seinen alten Freunden spricht.',
        modelAnswerEnglish: 'At home he does sit at his desk, but he makes no progress, because since the move he has hardly spoken with his old friends any more.',
        quickReplies: <String>[
          'Er setzt sich hin, aber nach zehn Minuten macht er etwas anderes.',
          'Bei uns wirkt er seit dem Umzug oft müde und sehr still.',
        ],
        coachTip: 'Attach your reason with „weil“ and let the conjugated verb drop to the end of that clause.',
      ),
      DialogueStep(
        tutorGerman: 'Das ist ein wichtiger Hinweis. Meine Kollegin sagt allerdings, Jonas sei in diesem Jahr einfach bequem geworden. Ich sehe das nicht ganz so, möchte aber Ihre Sicht hören.',
        tutorEnglish: 'That is an important clue. My colleague says, though, that Jonas has simply become lazy this year. I do not quite see it that way, but I would like to hear your view.',
        task: 'Disagree politely with that explanation and offer a different one.',
        keywords: <String>[
          'das sehe ich',
          'anders',
          'denn',
          'kind',
          'überfordert',
          'bequem',
          'nicht ganz',
          'faul',
        ],
        requiredHits: 3,
        minWords: 12,
        modelAnswer: 'Das sehe ich anders, denn ein Kind, das plötzlich alles liegen lässt, ist meistens überfordert und nicht bequem.',
        modelAnswerEnglish: 'I see that differently, because a child who suddenly lets everything slide is usually overwhelmed and not lazy.',
        quickReplies: <String>[
          'Da bin ich nicht ganz Ihrer Meinung, denn faul war er noch nie.',
          'Ich glaube eher, dass ihn der Stoff im Moment überfordert.',
        ],
        coachTip: 'The relative clause „das plötzlich alles liegen lässt“ describes the noun before it and pushes its verb to the end.',
      ),
      DialogueStep(
        tutorGerman: 'Gut, dann schauen wir nach vorn. Ich würde gern wissen, was aus Ihrer Sicht in der Schule anders laufen müsste, damit Jonas wieder mitkommt.',
        tutorEnglish: 'Good, then let us look ahead. I would like to know what would have to run differently at school, from your point of view, so that Jonas can keep up again.',
        task: 'Say what you would like the school to change, keeping it polite with Konjunktiv II.',
        keywords: <String>[
          'wäre',
          'hilfe',
          'schriftlich',
          'aufgaben',
          'bekäme',
          'vergisst',
          'würde',
          'könnten',
        ],
        requiredHits: 3,
        minWords: 12,
        modelAnswer: 'Es wäre uns eine große Hilfe, wenn Jonas die Aufgaben schriftlich bekäme, denn mündliche Ansagen vergisst er bis zum Nachmittag regelmäßig.',
        modelAnswerEnglish: 'It would be a great help to us if Jonas received the assignments in writing, because he regularly forgets spoken announcements by the afternoon.',
        quickReplies: <String>[
          'Könnten Sie ihm die Aufgaben bitte schriftlich mitgeben?',
          'Es würde uns helfen, wenn er die Wochenpläne ausgedruckt bekäme.',
        ],
        coachTip: '„Es wäre eine Hilfe, wenn …“ turns a request into a wish, which is exactly what Konjunktiv II is for.',
      ),
      DialogueStep(
        tutorGerman: 'Das lässt sich machen, die Wochenpläne liegen ohnehin digital vor. Umgekehrt brauche ich auch etwas von Ihnen: Wie könnten Sie zu Hause den Nachmittag anders gestalten?',
        tutorEnglish: 'That can be done, the weekly plans exist digitally anyway. In return I also need something from you: how could you organise the afternoon differently at home?',
        task: 'Offer one concrete thing you will change at home and say what it is for.',
        keywords: <String>[
          'könnten',
          'nachmittag',
          'einteilen',
          'hausaufgaben',
          'pause',
          'abend',
          'damit',
          'feste zeit',
        ],
        requiredHits: 3,
        minWords: 14,
        modelAnswer: 'Wir könnten den Nachmittag fest einteilen: erst eine halbe Stunde Pause, dann die Hausaufgaben, um den Abend nicht wieder zu verlieren.',
        modelAnswerEnglish: 'We could organise the afternoon firmly: first half an hour of break, then the homework, in order not to lose the evening again.',
        quickReplies: <String>[
          'Wir führen ab Montag feste Zeiten für die Hausaufgaben ein.',
          'Ich lege das Handy weg, damit er in Ruhe arbeiten kann.',
        ],
        coachTip: 'The „um … zu“ clause names the purpose of your plan and always ends with the infinitive.',
      ),
      DialogueStep(
        tutorGerman: 'Einverstanden. Eine Sache muss ich noch ansprechen: Ich würde Jonas gern für vier Wochen in die Lerngruppe am Donnerstag schicken. Was halten Sie davon?',
        tutorEnglish: 'Agreed. There is one more thing I have to raise: I would like to send Jonas to the Thursday study group for four weeks. What do you think of that?',
        task: 'Say why the proposal is difficult and suggest a workable alternative.',
        keywords: <String>[
          'leider',
          'weil',
          'schwimm',
          'deshalb',
          'würde',
          'dienstag',
          'vorschlag',
          'training',
        ],
        requiredHits: 3,
        minWords: 14,
        modelAnswer: 'Donnerstags geht es leider schlecht, weil er da zum Schwimmen fährt; deshalb würde ich den Dienstag vorschlagen, falls dort noch ein Platz frei ist.',
        modelAnswerEnglish: 'Thursdays are unfortunately difficult, because he goes swimming then; that is why I would suggest Tuesday, if there is still a place free there.',
        quickReplies: <String>[
          'Am Donnerstag geht es leider nicht, aber der Dienstag wäre möglich.',
          'Das ist schwierig, weil er donnerstags zum Training muss.',
        ],
        coachTip: '„deshalb“ states the consequence and pulls the verb right after it, before the subject.',
      ),
      DialogueStep(
        tutorGerman: 'Gut, dann halte ich fest: Wochenplan schriftlich, feste Zeiten zu Hause, Lerngruppe an einem anderen Tag. Fassen Sie bitte zusammen, was Sie bis zum nächsten Gespräch übernehmen.',
        tutorEnglish: 'Good, then I will note down: weekly plan in writing, fixed times at home, study group on another day. Please sum up what you will take on until our next meeting.',
        task: 'Summarise your part of the agreement and name a date for checking in.',
        keywords: <String>[
          'übernehme',
          'feste',
          'zeiten',
          'wochenplan',
          'melde',
          'vier wochen',
          'nachmittag',
          'abend',
        ],
        requiredHits: 3,
        minWords: 14,
        modelAnswer: 'Ich übernehme die festen Zeiten am Nachmittag und schaue jeden Abend in den Wochenplan; in vier Wochen melde ich mich wieder bei Ihnen.',
        modelAnswerEnglish: 'I will take on the fixed times in the afternoon and look at the weekly plan every evening; in four weeks I will get in touch with you again.',
        quickReplies: <String>[
          'Ich achte auf die festen Zeiten und schreibe Ihnen in vier Wochen.',
          'Wir sprechen jeden Abend kurz über den Wochenplan, das übernehme ich.',
        ],
        coachTip: 'Summaries keep verb-second order: start with the time phrase and the verb still comes in position two.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-b1-07',
    level: CefrLevel.b1,
    emoji: '🏦',
    title: 'Der kleine Kredit',
    setting: 'An advice desk at the Uferbank Falkenau on a quiet weekday morning, with a printed rate sheet on the table.',
    tutorRole: 'Herr Bendig, a loan adviser who answers in figures and steadily works through his checklist.',
    learnerRole: 'You, a customer who wants a small loan and wants to know what it really costs.',
    goal: 'Find out the total cost, question one condition and decide with a reason instead of signing today.',
    usefulPhrases: <String>[
      'Was kostet das am Ende insgesamt?',
      'Habe ich das richtig verstanden?',
      'Könnten Sie mir das aufschreiben?',
      'Ich möchte es mir noch überlegen.',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Guten Morgen, setzen Sie sich. Sie hatten wegen eines Kredits angefragt. Damit ich Ihnen etwas rechnen kann: Worum geht es genau, und an welche Summe denken Sie?',
        tutorEnglish: 'Good morning, do sit down. You had enquired about a loan. So that I can calculate something for you: what exactly is it about, and what sum are you thinking of?',
        task: 'Say what you need the loan for and how much you are thinking of.',
        keywords: <String>[
          'hätte gern',
          'kredit',
          'euro',
          'weil',
          'transporter',
          'gebraucht',
          'brauche',
          'viertausend',
        ],
        requiredHits: 2,
        minWords: 12,
        modelAnswer: 'Ich hätte gern einen Kredit über viertausend Euro, weil ich einen gebrauchten Transporter für meinen kleinen Gartenbetrieb brauche.',
        modelAnswerEnglish: 'I would like a loan of four thousand euros, because I need a used van for my small gardening business.',
        quickReplies: <String>[
          'Ich brauche etwa viertausend Euro für ein gebrauchtes Fahrzeug.',
          'Es geht um einen kleinen Kredit, weil mein Transporter kaputt ist.',
        ],
        coachTip: '„Ich hätte gern“ is Konjunktiv II doing polite everyday work at a counter.',
      ),
      DialogueStep(
        tutorGerman: 'Danke. Für kleinere Summen liegt unser Zinssatz derzeit bei knapp acht Prozent effektiv, üblich ist eine Laufzeit von drei Jahren. Haben Sie dazu Fragen?',
        tutorEnglish: 'Thank you. For smaller sums our interest rate is currently just under eight percent effective, and three years is the usual term. Do you have any questions about that?',
        task: 'Ask what the loan costs in total, not only per month.',
        keywords: <String>[
          'könnten',
          'insgesamt',
          'zurück',
          'rate',
          'zinsen',
          'am ende',
          'wie viel',
          'kosten',
        ],
        requiredHits: 3,
        minWords: 12,
        modelAnswer: 'Könnten Sie mir bitte sagen, wie viel ich am Ende insgesamt zurückzahle, also nicht nur die Rate, sondern auch die gesamten Zinsen?',
        modelAnswerEnglish: 'Could you please tell me how much I pay back in total in the end, so not just the instalment but also the entire interest?',
        quickReplies: <String>[
          'Wie hoch wären die gesamten Kosten am Ende der Laufzeit?',
          'Können Sie mir sagen, wie viel Zinsen insgesamt zusammenkommen?',
        ],
        coachTip: 'An indirect question with „wie viel“ sends the verb to the end of the subordinate clause.',
      ),
      DialogueStep(
        tutorGerman: 'Ich rechne es Ihnen aus: Bei viertausend Euro und sechsunddreißig Monaten wären das etwa hundertfünfundzwanzig Euro monatlich und rund vierhundertfünfzig Euro Zinsen. Dazu käme eine Restschuldversicherung für neun Euro im Monat.',
        tutorEnglish: 'I will work it out for you: with four thousand euros over thirty-six months that would be about one hundred and twenty-five euros a month and around four hundred and fifty euros in interest. On top of that there would be payment protection insurance at nine euros a month.',
        task: 'Ask whether the insurance is compulsory and say what you think of it.',
        keywords: <String>[
          'versicherung',
          'pflicht',
          'könnte',
          'verzichten',
          'teuer',
          'weil',
          'freiwillig',
          'brauche ich',
        ],
        requiredHits: 3,
        minWords: 12,
        modelAnswer: 'Ist diese Versicherung wirklich Pflicht, oder könnte ich darauf verzichten? Ich finde sie teuer, weil sie über drei Jahre noch einmal dreihundert Euro kostet.',
        modelAnswerEnglish: 'Is this insurance really compulsory, or could I do without it? I find it expensive, because over three years it costs another three hundred euros.',
        quickReplies: <String>[
          'Ist die Versicherung freiwillig, oder gehört sie zum Vertrag?',
          'Neun Euro im Monat finde ich viel; brauche ich das wirklich?',
        ],
        coachTip: 'A yes/no question puts the verb first: „Ist diese Versicherung Pflicht?“',
      ),
      DialogueStep(
        tutorGerman: 'Freiwillig ist sie, viele nehmen sie trotzdem. Ohne Versicherung bleibt es bei den genannten Zinsen. Ein anderer Punkt, den ich immer anspreche: Möchten Sie später schneller zurückzahlen können?',
        tutorEnglish: 'It is voluntary, though many people take it anyway. Without the insurance the interest stays as quoted. Another point I always raise: would you like to be able to pay back faster later on?',
        task: 'Ask about paying the loan off early and what that would cost.',
        keywords: <String>[
          'wäre',
          'würde',
          'kosten',
          'kredit',
          'gebühr',
          'ablösen',
          'früher',
          'vorzeitig',
        ],
        requiredHits: 3,
        minWords: 12,
        modelAnswer: 'Ja, das wäre mir wichtig. Was würde es kosten, wenn ich den Kredit schon nach einem Jahr komplett ablöse? Fällt dann eine Gebühr an?',
        modelAnswerEnglish: 'Yes, that would be important to me. What would it cost if I paid the loan off completely after just one year? Is there a fee then?',
        quickReplies: <String>[
          'Was passiert, wenn ich früher zurückzahlen möchte?',
          'Fällt eine Gebühr an, wenn ich den Kredit vorzeitig ablöse?',
        ],
        coachTip: 'Konjunktiv II („was würde es kosten“) frames a case that has not happened yet.',
      ),
      DialogueStep(
        tutorGerman: 'Eine vorzeitige Rückzahlung ist bei uns jederzeit möglich, es fällt aber ein Prozent der Restsumme an. Ich hätte den Vertrag hier fertig. Sollen wir das gleich unterschreiben?',
        tutorEnglish: 'Early repayment is possible with us at any time, but one percent of the remaining sum is charged. I have the contract ready here. Shall we sign it right away?',
        task: 'Decline to sign today, give a reason and propose a next step.',
        keywords: <String>[
          'noch nicht',
          'unterschreiben',
          'weil',
          'vergleichen',
          'schriftlich',
          'könnten',
          'nächste woche',
          'überlegen',
        ],
        requiredHits: 3,
        minWords: 14,
        modelAnswer: 'Heute möchte ich noch nicht unterschreiben, weil ich die Angebote in Ruhe vergleichen will. Könnten Sie mir alles schriftlich mitgeben? Dann melde ich mich nächste Woche.',
        modelAnswerEnglish: 'I would rather not sign today, because I want to compare the offers calmly. Could you give me everything in writing? Then I will get in touch next week.',
        quickReplies: <String>[
          'Ich würde das gern erst in Ruhe durchrechnen und überlegen.',
          'Geben Sie mir bitte alles schriftlich mit, dann melde ich mich.',
        ],
        coachTip: 'A refusal with a reason and a next step keeps a no from sounding like the end of the conversation.',
      ),
      DialogueStep(
        tutorGerman: 'Kein Problem, ich drucke Ihnen alles aus. Falls Sie sich anders entscheiden: Wir hätten auch einen Rahmenkredit, der teurer, aber flexibler ist. Was ist Ihnen am Ende wichtiger?',
        tutorEnglish: 'No problem, I will print everything out for you. In case you decide otherwise: we would also have a flexible credit line, which is more expensive but more flexible. What matters more to you in the end?',
        task: 'Say which matters more to you, cost or flexibility, and justify it.',
        keywords: <String>[
          'wichtiger',
          'kosten',
          'flexib',
          'denn',
          'monat',
          'betrag',
          'lieber',
          'planen',
        ],
        requiredHits: 3,
        minWords: 14,
        modelAnswer: 'Mir sind die niedrigen Kosten wichtiger als die Flexibilität, denn ich zahle jeden Monat den gleichen Betrag und plane lieber fest.',
        modelAnswerEnglish: 'Low costs matter more to me than flexibility, because I pay the same amount every month and prefer to plan firmly.',
        quickReplies: <String>[
          'Für mich zählt vor allem, dass die Rate niedrig bleibt.',
          'Flexibilität wäre schön, aber die Zinsen sind mir wichtiger.',
        ],
        coachTip: 'Comparisons run on „wichtiger als“, and „denn“ adds the reason without changing the word order.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-b1-08',
    level: CefrLevel.b1,
    emoji: '📅',
    title: 'Die Wochenendschicht',
    setting: 'The back office of Möwenhof Logistik on a Friday afternoon, while the shift plan for next month is being finished.',
    tutorRole: 'Frau Kastl, the shift supervisor, who needs the Saturdays covered and asks more than once.',
    learnerRole: 'You, a warehouse worker who has already worked three weekends in a row.',
    goal: 'Turn down the extra weekend shifts, keep the tone warm and offer something you can genuinely do.',
    usefulPhrases: <String>[
      'Das geht diesmal leider nicht.',
      'Ich verstehe, dass es eng ist.',
      'Anbieten könnte ich Ihnen …',
      'Sollen wir das anders lösen?',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Schön, dass ich Sie noch erwische. Der Plan für September steht fast, nur die Samstage sind offen. Sie waren zuletzt sehr zuverlässig. Wie sieht es bei Ihnen aus?',
        tutorEnglish: 'Good that I caught you. The plan for September is almost done, only the Saturdays are open. You have been very reliable lately. How does it look for you?',
        task: 'Say clearly that you cannot take the weekends, and give your reason.',
        keywords: <String>[
          'leider',
          'absagen',
          'weil',
          'wochenende',
          'familie',
          'gearbeitet',
          'hintereinander',
          'schaffe',
        ],
        requiredHits: 2,
        minWords: 12,
        modelAnswer: 'Diesmal muss ich leider absagen, weil ich drei Wochenenden hintereinander gearbeitet habe und meine Familie mich am Samstag kaum noch sieht.',
        modelAnswerEnglish: 'This time I have to say no, unfortunately, because I have worked three weekends in a row and my family hardly sees me on Saturdays any more.',
        quickReplies: <String>[
          'Diesmal schaffe ich die Samstage leider nicht.',
          'Ich muss absagen, weil ich schon drei Wochenenden gearbeitet habe.',
        ],
        coachTip: 'Put the refusal first and the reason after it; „leider“ marks the no without turning it into an apology.',
      ),
      DialogueStep(
        tutorGerman: 'Das verstehe ich, ehrlich. Nur habe ich für den achten und den fünfzehnten sonst niemanden, und der Betrieb muss laufen. Könnten Sie wenigstens einen davon übernehmen?',
        tutorEnglish: 'I do understand that, honestly. But I have nobody else for the eighth and the fifteenth, and the place has to keep running. Could you at least take one of them?',
        task: 'Hold your no politely while showing that you see her problem.',
        keywords: <String>[
          'problem',
          'trotzdem',
          'samstag',
          'schaffe',
          'weil',
          'pause',
          'dringend',
          'verstehe',
        ],
        requiredHits: 3,
        minWords: 12,
        modelAnswer: 'Ich sehe Ihr Problem, trotzdem bleibe ich dabei: Auch einen einzelnen Samstag schaffe ich nicht, weil ich die Pause wirklich dringend brauche.',
        modelAnswerEnglish: 'I see your problem, but I am sticking with it: I cannot manage even a single Saturday, because I really do need the break urgently.',
        quickReplies: <String>[
          'Ich verstehe den Engpass, trotzdem bleibe ich bei meinem Nein.',
          'Auch ein einzelner Samstag ist mir im September zu viel.',
        ],
        coachTip: '„trotzdem“ concedes her point and refuses anyway, and it puts the verb straight after it.',
      ),
      DialogueStep(
        tutorGerman: 'Hm. Ich frage mich, ob das an den Schichten liegt oder an etwas anderem. Ist bei Ihnen im Moment etwas los, wovon ich wissen sollte?',
        tutorEnglish: 'Hm. I wonder whether this is about the shifts or about something else. Is something going on with you at the moment that I should know about?',
        task: 'Explain your situation briefly and factually, without over-sharing.',
        keywords: <String>[
          'mutter',
          'hilfe',
          'wochenende',
          'einzige',
          'zeit',
          'seit',
          'privat',
          'kümmere',
        ],
        requiredHits: 3,
        minWords: 12,
        modelAnswer: 'Es ist nichts Dramatisches: Meine Mutter braucht seit dem Sommer mehr Hilfe, und die Wochenenden sind die einzige Zeit, die ich dafür habe.',
        modelAnswerEnglish: 'It is nothing dramatic: my mother has needed more help since the summer, and the weekends are the only time I have for that.',
        quickReplies: <String>[
          'Es ist nichts Schlimmes, ich brauche die Wochenenden für die Familie.',
          'Meine Mutter braucht Hilfe, und dafür bleibt mir nur der Samstag.',
        ],
        coachTip: 'A relative clause („die Zeit, die ich dafür habe“) adds the detail without a second sentence.',
      ),
      DialogueStep(
        tutorGerman: 'Danke, dass Sie das sagen. Dann suche ich woanders weiter. Entlastung im Lager brauche ich aber trotzdem. Haben Sie eine Idee, was möglich wäre?',
        tutorEnglish: 'Thank you for saying that. Then I will keep looking elsewhere. But I still need relief in the warehouse. Do you have an idea of what would be possible?',
        task: 'Offer a realistic alternative that you can genuinely deliver.',
        keywords: <String>[
          'könnte',
          'länger',
          'freitag',
          'vorbereitung',
          'übernehmen',
          'damit',
          'stunden',
          'anbieten',
        ],
        requiredHits: 3,
        minWords: 14,
        modelAnswer: 'Ich könnte unter der Woche zwei Stunden länger bleiben oder freitags die Vorbereitung übernehmen, damit am Samstag weniger Arbeit liegen bleibt.',
        modelAnswerEnglish: 'I could stay two hours longer during the week or take on the preparation on Fridays, so that less work is left over on Saturday.',
        quickReplies: <String>[
          'Anbieten könnte ich Ihnen zwei Stunden mehr unter der Woche.',
          'Freitags würde ich die Vorbereitung machen, damit es samstags schneller geht.',
        ],
        coachTip: '„damit“ introduces the purpose when the two clauses have different subjects.',
      ),
      DialogueStep(
        tutorGerman: 'Das ist ein guter Vorschlag, den ich mit dem Lagerleiter bespreche. Eine Bitte hätte ich noch: Wären Sie am Wochenende wenigstens telefonisch erreichbar?',
        tutorEnglish: 'That is a good suggestion, which I will discuss with the warehouse manager. I have one more request: would you at least be reachable by phone at the weekend?',
        task: 'Set a clear limit for emergencies and say what you do agree to.',
        keywords: <String>[
          'erreichbar',
          'nur bis',
          'uhr',
          'rufen',
          'dringend',
          'montag',
          'notfall',
          'abends',
        ],
        requiredHits: 3,
        minWords: 14,
        modelAnswer: 'Erreichbar bin ich gern, aber nur bis achtzehn Uhr; wenn wirklich etwas Dringendes ist, rufen Sie mich an, sonst klären wir es am Montag.',
        modelAnswerEnglish: 'I am happy to be reachable, but only until six in the evening; if something really urgent comes up, call me, otherwise we sort it out on Monday.',
        quickReplies: <String>[
          'Rufen Sie mich im Notfall an, aber bitte nicht spät abends.',
          'Bis achtzehn Uhr bin ich erreichbar, danach lieber erst am Montag.',
        ],
        coachTip: 'Fronting the important word („Erreichbar bin ich …“) still leaves the verb in second position.',
      ),
      DialogueStep(
        tutorGerman: 'Gut, so machen wir das. Für die Samstage trage ich Sie nicht ein. Damit es beim nächsten Plan nicht wieder so eng wird: Wie sollen wir künftig vorgehen?',
        tutorEnglish: 'Good, that is how we will do it. I will not put you down for the Saturdays. So that it does not get this tight with the next plan: how should we proceed in future?',
        task: 'Propose how the shift planning should work next time, politely.',
        keywords: <String>[
          'wäre',
          'hilfreich',
          'plan',
          'vorher',
          'besprechen',
          'würden',
          'weil',
          'termine',
        ],
        requiredHits: 3,
        minWords: 14,
        modelAnswer: 'Es wäre hilfreich, wenn wir den Plan vier Wochen vorher besprechen würden, weil ich dann meine privaten Termine rechtzeitig anpassen kann.',
        modelAnswerEnglish: 'It would be helpful if we discussed the plan four weeks in advance, because then I can adjust my private appointments in good time.',
        quickReplies: <String>[
          'Könnten wir den Plan künftig früher gemeinsam besprechen?',
          'Vier Wochen Vorlauf würden mir sehr helfen.',
        ],
        coachTip: '„wenn … würden“ turns a demand into a proposal that leaves the other person room to answer.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-b1-09',
    level: CefrLevel.b1,
    emoji: '🧹',
    title: 'Putztag im Viertel',
    setting: 'The courtyard of a block of flats on Ahlbecker Weg, where six neighbours have gathered on a Sunday afternoon.',
    tutorRole: 'Herr Osmani from the ground floor, who likes the idea but keeps raising practical objections.',
    learnerRole: 'You, the neighbour who called the meeting and wants people to take on tasks.',
    goal: 'Present the clean-up day, answer objections and get concrete jobs taken on by name.',
    usefulPhrases: <String>[
      'Ich habe einen Vorschlag.',
      'Wer könnte das übernehmen?',
      'Das kriegen wir zusammen hin.',
      'Dann trage ich Sie dafür ein.',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Schön, dass so viele gekommen sind. Sie hatten zu dieser Runde eingeladen. Sagen Sie doch einmal, worum es geht und warum das gerade jetzt sein muss.',
        tutorEnglish: 'Nice that so many people came. You invited us to this get-together. Do tell us what it is about and why it has to be right now.',
        task: 'Present your idea for the clean-up day and give a reason.',
        keywords: <String>[
          'schlage',
          'putztag',
          'samstag',
          'weil',
          'hof',
          'spielplatz',
          'müll',
          'aufräum',
        ],
        requiredHits: 2,
        minWords: 12,
        modelAnswer: 'Ich schlage einen Putztag am letzten Samstag im Monat vor, weil der Hof und der Spielplatz seit dem Frühjahr ziemlich verwahrlost aussehen.',
        modelAnswerEnglish: 'I suggest a clean-up day on the last Saturday of the month, because the yard and the playground have looked pretty neglected since the spring.',
        quickReplies: <String>[
          'Ich möchte einen Putztag organisieren, weil überall Müll liegt.',
          'Mein Vorschlag ist ein gemeinsamer Aufräumtag am Samstagvormittag.',
        ],
        coachTip: 'Separable verbs split: „Ich schlage … vor“ leaves the prefix waiting at the end of the clause.',
      ),
      DialogueStep(
        tutorGerman: 'Verstehe. Ich sage gleich dazu: Solche Aktionen hatten wir schon zweimal, und am Ende standen drei Leute mit dem Besen da. Warum sollte es diesmal anders laufen?',
        tutorEnglish: 'I see. Let me say right away: we have had such actions twice already, and in the end three people stood there with a broom. Why should it be different this time?',
        task: 'Answer the objection and explain what you would do differently.',
        keywords: <String>[
          'anders',
          'denn',
          'aufgaben',
          'verteilen',
          'schriftlich',
          'sodass',
          'verantwortlich',
          'liste',
        ],
        requiredHits: 3,
        minWords: 12,
        modelAnswer: 'Diesmal machen wir es anders, denn wir verteilen die Aufgaben heute schriftlich, sodass jeder genau weiß, wofür er verantwortlich ist.',
        modelAnswerEnglish: 'This time we will do it differently, because we hand out the tasks in writing today, so that everyone knows exactly what they are responsible for.',
        quickReplies: <String>[
          'Diesmal schreiben wir vorher auf, wer welche Aufgabe übernimmt.',
          'Mit einer Liste läuft es besser, weil jeder seinen Teil kennt.',
        ],
        coachTip: '„sodass“ names the consequence and, like „weil“, sends its verb to the end.',
      ),
      DialogueStep(
        tutorGerman: 'Klingt vernünftig. Nur: Wer macht was? Ich habe an dem Samstag Dienst und kann höchstens eine Stunde helfen. Andere sagen bestimmt gleich dasselbe.',
        tutorEnglish: 'Sounds sensible. But who does what? I am on duty that Saturday and can help for an hour at most. Others will certainly say the same thing.',
        task: 'Give him a small, specific job and make it easy to say yes.',
        keywords: <String>[
          'stunde',
          'reicht',
          'könnten',
          'container',
          'bestellen',
          'aufschließen',
          'übernehmen',
          'kurz',
        ],
        requiredHits: 3,
        minWords: 12,
        modelAnswer: 'Eine Stunde reicht völlig: Könnten Sie den Container bestellen und morgens kurz das Tor aufschließen? Alles andere übernehmen wir, während Sie im Dienst sind.',
        modelAnswerEnglish: 'One hour is quite enough: could you order the skip and unlock the gate briefly in the morning? We will take care of everything else while you are on duty.',
        quickReplies: <String>[
          'Könnten Sie nur den Container bestellen? Das dauert zehn Minuten.',
          'Eine Stunde reicht, wenn Sie morgens kurz aufschließen.',
        ],
        coachTip: 'A request phrased as „Könnten Sie …?“ is much easier to accept than an instruction.',
      ),
      DialogueStep(
        tutorGerman: 'Den Container kann ich bestellen, das ist machbar. Aber wer kümmert sich um Handschuhe, Säcke und die Kinder, die unbedingt mithelfen wollen?',
        tutorEnglish: 'I can order the skip, that is doable. But who takes care of gloves, bags and the children who insist on helping?',
        task: 'Split the remaining jobs and name who does what, proposing rather than ordering.',
        keywords: <String>[
          'würde',
          'handschuhe',
          'könnte',
          'säcke',
          'kinder',
          'sammeln',
          'besorgen',
          'aufsicht',
        ],
        requiredHits: 3,
        minWords: 14,
        modelAnswer: 'Ich würde die Handschuhe besorgen, Frau Perl könnte die Säcke mitbringen, und die Kinder sammeln unter Aufsicht das Laub im vorderen Hof.',
        modelAnswerEnglish: 'I would get the gloves, Mrs Perl could bring the bags, and the children can collect the leaves in the front yard under supervision.',
        quickReplies: <String>[
          'Frau Perl könnte die Säcke besorgen, ich kümmere mich um die Handschuhe.',
          'Die Kinder würden das Laub sammeln, wenn jemand dabei bleibt.',
        ],
        coachTip: 'Konjunktiv II („ich würde …, sie könnte …“) hands out jobs as suggestions instead of orders.',
      ),
      DialogueStep(
        tutorGerman: 'Gut. Und wenn es an dem Samstag regnet? Dann sitzen wir hier mit zwanzig Säcken und niemand kommt. Daran hat noch keiner gedacht.',
        tutorEnglish: 'Good. And what if it rains that Saturday? Then we sit here with twenty bags and nobody turns up. Nobody has thought about that yet.',
        task: 'Deal with the rain problem and propose a fallback.',
        keywords: <String>[
          'falls',
          'regnet',
          'verschieben',
          'sonntag',
          'zettel',
          'treppenhaus',
          'damit',
          'bescheid',
        ],
        requiredHits: 3,
        minWords: 14,
        modelAnswer: 'Falls es regnet, verschieben wir einfach auf den Sonntag; ich hänge einen Zettel ins Treppenhaus, damit alle rechtzeitig Bescheid wissen.',
        modelAnswerEnglish: 'If it rains, we simply move it to the Sunday; I will put a note in the stairwell so that everyone knows in good time.',
        quickReplies: <String>[
          'Bei Regen verschieben wir alles auf den nächsten Sonntag.',
          'Ich hänge einen Zettel auf, falls das Wetter nicht mitspielt.',
        ],
        coachTip: '„falls“ works like „wenn“ for a case that may or may not happen, and its verb goes to the end.',
      ),
      DialogueStep(
        tutorGerman: 'Also, ich fasse zusammen: Container, Handschuhe, Säcke, Kinder, Ersatztermin. Sagen Sie es bitte noch einmal laut, dann glauben es die anderen auch.',
        tutorEnglish: 'So, let me sum up: skip, gloves, bags, children, replacement date. Please say it out loud once more, then the others will believe it too.',
        task: 'Sum up the agreement clearly and thank the group.',
        keywords: <String>[
          'treffen',
          'samstag',
          'zehn',
          'hof',
          'container',
          'handschuhe',
          'regen',
          'bestellt',
        ],
        requiredHits: 3,
        minWords: 14,
        modelAnswer: 'Wir treffen uns am letzten Samstag um zehn Uhr im Hof; Herr Osmani bestellt den Container, ich bringe die Handschuhe, und bei Regen verschieben wir alles.',
        modelAnswerEnglish: 'We meet on the last Saturday at ten in the yard; Mr Osmani orders the skip, I bring the gloves, and if it rains we move everything.',
        quickReplies: <String>[
          'Wir treffen uns also um zehn im Hof, mit Handschuhen und Säcken.',
          'Danke euch allen; Container, Säcke und Ersatztermin stehen jetzt fest.',
        ],
        coachTip: 'A closing summary in the present tense is how German speakers confirm an arrangement.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-b1-10',
    level: CefrLevel.b1,
    emoji: '📋',
    title: 'Die Jahresbeurteilung',
    setting: 'A small meeting room at Lindhoff Systemtechnik, where the annual review is held once a year.',
    tutorRole: 'Frau Weiskopf, the team leader, who goes through the written assessment point by point.',
    learnerRole: 'You, an employee in the project office who does not agree with parts of the assessment.',
    goal: 'Disagree politely with two points in your review, back it up with evidence, and propose a concrete alternative.',
    usefulPhrases: <String>[
      'Das sehe ich etwas anders.',
      'Darf ich kurz etwas ergänzen?',
      'Ich würde gern ein Beispiel nennen.',
      'Könnten wir das noch einmal anschauen?',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Schön, dass Sie da sind. Ich habe Ihre Jahresbeurteilung schon vorbereitet. Bevor wir sie durchgehen: Wie schätzen Sie Ihr eigenes Jahr ein?',
        tutorEnglish: 'Good that you are here. I have already prepared your annual review. Before we go through it: how do you assess your own year?',
        task: 'Sum up your year and name one thing you are proud of, with a reason.',
        keywords: <String>[
          'insgesamt',
          'weil',
          'projekt',
          'übernommen',
          'allein',
          'zufrieden',
          'stolz',
        ],
        requiredHits: 2,
        minWords: 12,
        modelAnswer: 'Insgesamt war es ein gutes Jahr, weil ich das Projekt Nordwind allein übernommen habe, obwohl es sehr kurzfristig kam.',
        modelAnswerEnglish: 'All in all it was a good year, because I took over the Nordwind project on my own, even though it came at very short notice.',
        quickReplies: <String>[
          'Ich bin insgesamt zufrieden, weil ich viel Neues gelernt habe.',
          'Es war anstrengend, aber ich habe zwei große Aufgaben allein übernommen.',
        ],
        coachTip: 'Use „weil“ to attach your reason, and remember that the conjugated verb slides to the end of that clause.',
      ),
      DialogueStep(
        tutorGerman: 'Danke. In meiner Bewertung steht bei Teamarbeit allerdings nur die Note befriedigend. Ich habe den Eindruck, dass Sie oft sehr für sich arbeiten.',
        tutorEnglish: 'Thank you. In my assessment, though, teamwork only gets the grade satisfactory. I have the impression that you often work very much on your own.',
        task: 'Disagree politely with the teamwork rating and give one concrete counter-example.',
        keywords: <String>[
          'das sehe ich',
          'anders',
          'denn',
          'eingearbeitet',
          'team',
          'kolleg',
          'nicht ganz',
        ],
        requiredHits: 3,
        minWords: 14,
        modelAnswer: 'Das sehe ich ehrlich gesagt anders, denn ich habe die neuen Kolleginnen eingearbeitet und jede Woche die Übergabe für das ganze Team geschrieben.',
        modelAnswerEnglish: 'Honestly, I see that differently, because I trained the new colleagues and wrote the weekly handover for the whole team.',
        quickReplies: <String>[
          'Da bin ich nicht ganz Ihrer Meinung, denn ich helfe im Team oft aus.',
          'Das sehe ich anders, weil ich zwei Kolleginnen eingearbeitet habe.',
        ],
        coachTip: '„denn“ joins your objection to its reason without changing the word order, unlike „weil“.',
      ),
      DialogueStep(
        tutorGerman: 'Interessant. Trotzdem zeigt die Statistik, dass Ihre Vorgänge im Schnitt länger dauern als die der anderen. Wie erklären Sie sich das?',
        tutorEnglish: 'Interesting. Even so, the statistics show that your cases take longer on average than the others. How do you explain that?',
        task: 'Explain what lies behind the numbers and question the comparison itself.',
        keywords: <String>[
          'zahlen',
          'vergleichbar',
          'weil',
          'komplizier',
          'fälle',
          'aber',
          'schwierig',
        ],
        requiredHits: 3,
        minWords: 14,
        modelAnswer: 'Die Zahlen stimmen, aber sie sind nicht vergleichbar, weil ich vor allem die komplizierten Fälle bekomme, die andere schon einmal abgegeben haben.',
        modelAnswerEnglish: 'The numbers are correct, but they are not comparable, because I mainly get the complicated cases that others have already handed back.',
        quickReplies: <String>[
          'Die Zahlen stimmen, aber meine Fälle sind oft komplizierter als andere.',
          'Ein Vergleich ist schwierig, weil ich fast nur alte Fälle übernehme.',
        ],
        coachTip: 'The relative pronoun „die“ picks up „Fälle“ and sends the verb of the relative clause to the very end.',
      ),
      DialogueStep(
        tutorGerman: 'Gut, das notiere ich mir. Wenn wir an der Bewertung etwas ändern sollen, brauche ich allerdings einen konkreten Vorschlag von Ihnen.',
        tutorEnglish: 'Good, I will note that down. If we are to change anything in the assessment, though, I need a concrete proposal from you.',
        task: 'Propose an alternative measure or wording, keeping it polite with Konjunktiv II.',
        keywords: <String>[
          'ich würde',
          'vorschlag',
          'könnte',
          'getrennt',
          'zählen',
          'vergleichen',
          'wäre',
        ],
        requiredHits: 3,
        minWords: 14,
        modelAnswer: 'Ich würde vorschlagen, dass wir die schwierigen Fälle getrennt zählen; dann könnte man meine Bearbeitungszeit fair mit der Statistik der anderen vergleichen.',
        modelAnswerEnglish: 'I would suggest that we count the difficult cases separately; then my processing time could be compared fairly with the statistics of the others.',
        quickReplies: <String>[
          'Ich würde vorschlagen, die schwierigen Fälle getrennt zu zählen.',
          'Könnten wir die Bearbeitungszeiten getrennt vergleichen? Das wäre für mich fairer.',
        ],
        coachTip: '„Ich würde vorschlagen“ turns a demand into an offer, and Konjunktiv II keeps the disagreement collegial.',
      ),
      DialogueStep(
        tutorGerman: 'Verstanden. Für das nächste Jahr müssen wir außerdem ein Entwicklungsziel eintragen. Was brauchen Sie von mir, um besser arbeiten zu können?',
        tutorEnglish: 'Understood. For next year we also have to enter a development goal. What do you need from me in order to work better?',
        task: 'Say what support you need and why, using um ... zu.',
        keywords: <String>[
          'bräuchte',
          'schulung',
          'um die',
          'zu prüfen',
          'schneller',
          'feedback',
          'unterstützung',
        ],
        requiredHits: 3,
        minWords: 12,
        modelAnswer: 'Ich bräuchte eine Schulung für die neue Software, um die Anträge schneller zu prüfen, und einmal im Monat ein kurzes Feedbackgespräch.',
        modelAnswerEnglish: 'I would need training on the new software in order to check the applications faster, and a short feedback conversation once a month.',
        quickReplies: <String>[
          'Ich bräuchte eine Schulung, um die neue Software schneller zu bedienen.',
          'Mir würde regelmäßiges Feedback helfen, um die Anträge schneller zu prüfen.',
        ],
        coachTip: 'An „um … zu“ clause has no subject of its own, and „zu“ stands directly before the infinitive at the end.',
      ),
      DialogueStep(
        tutorGerman: 'Danke, das trage ich so ein. Fassen Sie zum Schluss bitte noch einmal zusammen, worauf wir uns heute geeinigt haben.',
        tutorEnglish: 'Thank you, I will enter it like that. To finish, please sum up once more what we have agreed on today.',
        task: 'Summarise the agreement in your own words and close the meeting politely.',
        keywords: <String>[
          'halten fest',
          'note',
          'teamarbeit',
          'überprüft',
          'schulung',
          'monatlich',
          'zusammengefasst',
        ],
        requiredHits: 3,
        minWords: 14,
        modelAnswer: 'Wir halten fest, dass die Note zur Teamarbeit überprüft wird, dass ich eine Schulung bekomme und dass wir uns monatlich kurz austauschen.',
        modelAnswerEnglish: 'We note that the teamwork grade will be reviewed, that I will get training, and that we will have a short exchange every month.',
        quickReplies: <String>[
          'Wir halten fest: Die Note wird überprüft und ich bekomme eine Schulung.',
          'Zusammengefasst: Sie prüfen die Bewertung zur Teamarbeit und wir sprechen monatlich.',
        ],
        coachTip: 'Stacking „dass“ clauses is a tidy way to list agreements, and each one ends with its own verb.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-b1-11',
    level: CefrLevel.b1,
    emoji: '🚗',
    title: 'Der Blechschaden',
    setting: 'A phone call and counter conversation at Autohaus Kellerbach after a bump in a car park.',
    tutorRole: 'Herr Trautmann, the workshop foreman, who quotes prices and dates.',
    learnerRole: 'You, the owner of the damaged car, arranging the repair.',
    goal: 'Describe the damage, sort out the insurance, and negotiate price, time and a replacement car.',
    usefulPhrases: <String>[
      'Was würde die Reparatur ungefähr kosten?',
      'Könnten Sie mir einen Kostenvoranschlag machen?',
      'Das ist mir leider zu teuer.',
      'Wäre es möglich, den Wagen früher zu bekommen?',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Autohaus Kellerbach, Trautmann am Apparat. Sie hatten wegen eines Schadens angerufen. Erzählen Sie mir bitte kurz, was passiert ist.',
        tutorEnglish: 'Kellerbach car dealership, Trautmann speaking. You called about some damage. Please tell me briefly what happened.',
        task: 'Describe the accident briefly and say what is damaged.',
        keywords: <String>[
          'ausparken',
          'deshalb',
          'stoßstange',
          'rücklicht',
          'kaputt',
          'hinten',
          'beschädigt',
        ],
        requiredHits: 2,
        minWords: 10,
        modelAnswer: 'Beim Ausparken ist mir ein Transporter hinten reingefahren, deshalb sind die Stoßstange und das rechte Rücklicht kaputt.',
        modelAnswerEnglish: 'While I was pulling out of a parking space, a van drove into the back of me, so the bumper and the right rear light are broken.',
        quickReplies: <String>[
          'Ein Transporter ist mir hinten reingefahren, deshalb ist die Stoßstange kaputt.',
          'Beim Ausparken hat mich ein Auto touchiert; das Rücklicht ist beschädigt.',
        ],
        coachTip: '„deshalb“ names a consequence and takes first position, so the verb follows immediately after it.',
      ),
      DialogueStep(
        tutorGerman: 'Verstehe, das klingt nach einem klassischen Blechschaden. Läuft das über die Versicherung der anderen Seite oder zahlen Sie die Reparatur selbst?',
        tutorEnglish: 'I see, that sounds like a classic dented-metal case. Is this going through the other side\'s insurance, or are you paying for the repair yourself?',
        task: 'Explain how the repair will be paid for and ask what the workshop needs from you.',
        keywords: <String>[
          'versicherung',
          'übernimmt',
          'weil',
          'schuld',
          'unterlagen',
          'brauchen sie',
          'selbst',
        ],
        requiredHits: 3,
        minWords: 12,
        modelAnswer: 'Die Versicherung des Transporters übernimmt den Schaden, weil der Fahrer die Schuld zugegeben hat. Welche Unterlagen brauchen Sie von mir?',
        modelAnswerEnglish: 'The van\'s insurance is covering the damage, because the driver admitted fault. Which documents do you need from me?',
        quickReplies: <String>[
          'Die Versicherung der anderen Seite übernimmt das, weil der Fahrer schuld ist.',
          'Wenn die Versicherung nicht zahlt, zahle ich selbst. Welche Unterlagen brauchen Sie?',
        ],
        coachTip: 'Ending your turn with a question keeps the conversation moving; „Welche Unterlagen brauchen Sie?“ is more useful than a bare yes.',
      ),
      DialogueStep(
        tutorGerman: 'Gut. Ich habe mir den Wagen kurz angesehen. Der Kostenvoranschlag liegt bei etwa elfhundert Euro, und wir bräuchten das Auto acht Tage.',
        tutorEnglish: 'Good. I had a quick look at the car. The estimate is around eleven hundred euros, and we would need the car for eight days.',
        task: 'React to the price and the length of time, and ask whether a cheaper solution is possible.',
        keywords: <String>[
          'wären',
          'schwierig',
          'weil',
          'günstiger',
          'gebrauchte',
          'lösung',
          'zu lange',
        ],
        requiredHits: 3,
        minWords: 12,
        modelAnswer: 'Acht Tage wären für mich schwierig, weil ich das Auto für die Arbeit brauche. Gäbe es eine günstigere Lösung mit gebrauchten Teilen?',
        modelAnswerEnglish: 'Eight days would be difficult for me, because I need the car for work. Would there be a cheaper solution with used parts?',
        quickReplies: <String>[
          'Acht Tage sind zu lange, weil ich pendle. Gibt es eine günstigere Lösung?',
          'Elfhundert Euro wären schwierig für mich; wären gebrauchte Teile möglich?',
        ],
        coachTip: 'Konjunktiv II forms such as „wären“ and „gäbe es“ turn a complaint into a negotiable question.',
      ),
      DialogueStep(
        tutorGerman: 'Gebrauchte Teile sind möglich, dann sind es rund achthundert Euro. Allerdings kann ich auf gebrauchte Teile nur ein halbes Jahr Garantie geben.',
        tutorEnglish: 'Used parts are possible, then it is around eight hundred euros. However, I can only give six months of warranty on used parts.',
        task: 'Weigh up the two options out loud and decide, giving your reason.',
        keywords: <String>[
          'lieber',
          'gebrauchte',
          'denn',
          'garantie',
          'reicht',
          'alt',
          'trotzdem',
        ],
        requiredHits: 3,
        minWords: 12,
        modelAnswer: 'Dann nehme ich lieber die gebrauchten Teile, denn der Wagen ist zwölf Jahre alt und ein halbes Jahr Garantie reicht mir völlig.',
        modelAnswerEnglish: 'Then I would rather take the used parts, because the car is twelve years old and six months of warranty is quite enough for me.',
        quickReplies: <String>[
          'Trotzdem nehme ich lieber neue Teile, denn ich möchte die volle Garantie.',
          'Ein halbes Jahr Garantie reicht mir, denn der Wagen ist ohnehin alt.',
        ],
        coachTip: '„lieber“ marks a preference between two offers, and „denn“ adds the reason in normal main-clause order.',
      ),
      DialogueStep(
        tutorGerman: 'In Ordnung, ich notiere gebrauchte Teile. Ein Ersatzwagen kostet bei uns fünfundzwanzig Euro pro Tag. Möchten Sie einen?',
        tutorEnglish: 'All right, I am noting down used parts. A replacement car costs twenty-five euros a day with us. Would you like one?',
        task: 'Ask whether the insurance pays for a replacement car and offer an alternative if it does not.',
        keywords: <String>[
          'versicherung',
          'ersatzwagen',
          'würde ich',
          'um die kosten',
          'falls',
          'rad',
          'zahlt',
        ],
        requiredHits: 3,
        minWords: 12,
        modelAnswer: 'Zahlt die gegnerische Versicherung den Ersatzwagen? Falls nicht, würde ich lieber mit dem Rad fahren, um die Kosten niedrig zu halten.',
        modelAnswerEnglish: 'Does the other party\'s insurance pay for the replacement car? If not, I would rather cycle in order to keep the costs down.',
        quickReplies: <String>[
          'Übernimmt die Versicherung den Ersatzwagen? Falls nein, verzichte ich darauf.',
          'Zahlt die Gegenseite den Ersatzwagen? Sonst würde ich mit dem Bus fahren.',
        ],
        coachTip: 'The „um … zu“ clause names your purpose, while „falls“ sets the condition without needing „wenn“.',
      ),
      DialogueStep(
        tutorGerman: 'Alles klar. Den Kostenvoranschlag schicke ich Ihnen heute noch zu. Sagen Sie mir bitte nur noch, wie wir Sie am besten erreichen.',
        tutorEnglish: 'All right. I will send you the estimate later today. Just tell me how we can best reach you.',
        task: 'Give a way to contact you and confirm the whole arrangement in one clear sentence.',
        keywords: <String>[
          'am besten',
          'tagsüber',
          'also',
          'gebrauchte',
          'ersatzwagen',
          'erreichen',
          'bleiben',
        ],
        requiredHits: 3,
        minWords: 12,
        modelAnswer: 'Am besten per E-Mail; tagsüber bin ich in Besprechungen. Wir bleiben also bei den gebrauchten Teilen, das Auto ist acht Tage in der Werkstatt und einen Ersatzwagen brauche ich nicht.',
        modelAnswerEnglish: 'Best by email; during the day I am in meetings. So we are staying with the used parts, the car is in the workshop for eight days, and I do not need a replacement car.',
        quickReplies: <String>[
          'Sie erreichen mich am besten abends; tagsüber bin ich unterwegs.',
          'Also: gebrauchte Teile, acht Tage, kein Ersatzwagen. Rufen Sie mich bitte an.',
        ],
        coachTip: 'Closing with „also“ marks a summary and signals to your partner that the matter is settled.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-b1-12',
    level: CefrLevel.b1,
    emoji: '🔄',
    title: 'Der neue Ablauf',
    setting: 'The break room at Ostmann Verpackungen, where two colleagues talk about the shift handover.',
    tutorRole: 'Herr Dombrowski, an experienced colleague who is sceptical about anything new.',
    learnerRole: 'You, a colleague who wants the team to try a shared digital handover list for two weeks.',
    goal: 'Win a sceptical colleague over to a two-week trial by answering each of his objections.',
    usefulPhrases: <String>[
      'Darf ich dir kurz zeigen, wie es funktioniert?',
      'Ich verstehe deinen Einwand.',
      'Wir könnten es einfach zwei Wochen testen.',
      'Was müsste passieren, damit du es probierst?',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Du wolltest mit mir über die neue Übergabeliste reden. Ehrlich gesagt läuft es bei uns seit Jahren gut mit dem Papierheft. Also, worum geht es?',
        tutorEnglish: 'You wanted to talk to me about the new handover list. Honestly, things have been going well with the paper book for years. So, what is it about?',
        task: 'Explain in one or two sentences what you are proposing and why.',
        keywords: <String>[
          'schlage vor',
          'digital',
          'weil',
          'übergabe',
          'papierheft',
          'spätschicht',
          'vorschlag',
        ],
        requiredHits: 2,
        minWords: 12,
        modelAnswer: 'Ich schlage vor, dass wir die Übergabe digital machen, weil das Papierheft oft in der Halle liegt und die Spätschicht es nicht findet.',
        modelAnswerEnglish: 'I suggest that we do the handover digitally, because the paper book often lies around in the hall and the late shift cannot find it.',
        quickReplies: <String>[
          'Mein Vorschlag ist eine digitale Übergabe, weil das Heft oft verschwindet.',
          'Ich schlage vor, dass die Spätschicht die Infos digital bekommt.',
        ],
        coachTip: '„Ich schlage vor, dass …“ opens a proposal, and the verb of the dass-clause waits until the end.',
      ),
      DialogueStep(
        tutorGerman: 'Digital, digital. Ich bin siebenundfünfzig und tippe langsam. Am Ende kostet mich das mehr Zeit als das Heft.',
        tutorEnglish: 'Digital, digital. I am fifty-seven and I type slowly. In the end that costs me more time than the book.',
        task: 'Acknowledge his objection and answer it with a concrete benefit.',
        keywords: <String>[
          'verstehe',
          'einwand',
          'aber',
          'anklicken',
          'deshalb',
          'minuten',
          'schneller',
        ],
        requiredHits: 3,
        minWords: 12,
        modelAnswer: 'Ich verstehe deinen Einwand, aber die Liste hat feste Felder, die man nur anklicken muss; deshalb dauert eine Übergabe höchstens zwei Minuten.',
        modelAnswerEnglish: 'I understand your objection, but the list has fixed fields that you only have to click; that is why a handover takes two minutes at most.',
        quickReplies: <String>[
          'Ich verstehe das, aber man muss nur ein paar Felder anklicken.',
          'Dein Einwand ist berechtigt, aber du brauchst dafür höchstens zwei Minuten.',
        ],
        coachTip: 'Naming the objection first with „Ich verstehe deinen Einwand“ makes the „aber“ that follows sound cooperative rather than dismissive.',
      ),
      DialogueStep(
        tutorGerman: 'Und wenn das System ausfällt? Dann stehen wir da und niemand weiß, welche Paletten schon raus sind.',
        tutorEnglish: 'And if the system goes down? Then we are stuck and nobody knows which pallets have already gone out.',
        task: 'Address the risk he names and offer a safeguard.',
        keywords: <String>[
          'falls',
          'könnten wir',
          'ausdrucken',
          'damit',
          'heft',
          'würde',
          'notfall',
        ],
        requiredHits: 3,
        minWords: 12,
        modelAnswer: 'Falls das System ausfällt, könnten wir weiter das Heft benutzen; ich würde außerdem jeden Freitag eine Liste ausdrucken, damit alles doppelt vorhanden ist.',
        modelAnswerEnglish: 'If the system goes down we could carry on using the book; on top of that I would print out a list every Friday so that everything exists twice.',
        quickReplies: <String>[
          'Falls das Netz ausfällt, könnten wir kurz wieder das Heft nehmen.',
          'Ich würde die Liste jede Woche ausdrucken, damit nichts verloren geht.',
        ],
        coachTip: '„damit“ introduces a purpose clause when the two halves have different subjects, where „um … zu“ would not work.',
      ),
      DialogueStep(
        tutorGerman: 'Hm. Die Chefin hat vor drei Jahren auch schon so ein Programm gekauft, und nach einem Monat hat es keiner mehr benutzt.',
        tutorEnglish: 'Hm. Three years ago the boss bought a programme like that too, and after a month nobody used it any more.',
        task: 'Concede his point and propose a small, limited trial.',
        keywords: <String>[
          'hast du recht',
          'deswegen',
          'würde',
          'vorschlag',
          'zwei wochen',
          'test',
          'probieren',
        ],
        requiredHits: 3,
        minWords: 12,
        modelAnswer: 'Da hast du recht, das war damals schlecht vorbereitet. Deswegen würde ich vorschlagen, dass nur unser Team es zwei Wochen lang testet.',
        modelAnswerEnglish: 'You are right there, that was badly prepared at the time. That is why I would suggest that only our team tests it for two weeks.',
        quickReplies: <String>[
          'Da hast du recht, deswegen sollten wir es nur zwei Wochen testen.',
          'Ich würde vorschlagen, dass wir es erst im kleinen Kreis probieren.',
        ],
        coachTip: 'Conceding with „Da hast du recht“ before „deswegen“ turns his objection into the reason for your smaller proposal.',
      ),
      DialogueStep(
        tutorGerman: 'Zwei Wochen, na gut. Aber wer bringt das den Leuten bei? Ich habe keine Zeit, jedem einzeln etwas zu erklären.',
        tutorEnglish: 'Two weeks, fine. But who is going to teach it to people? I have no time to explain things to everyone individually.',
        task: 'Offer concrete help and make the effort sound small.',
        keywords: <String>[
          'übernehme',
          'zeige',
          'anleitung',
          'damit',
          'zehn minuten',
          'helfe',
          'erkläre',
        ],
        requiredHits: 3,
        minWords: 12,
        modelAnswer: 'Das übernehme ich gern. Ich zeige es am Montag allen in zehn Minuten und hänge eine kurze Anleitung an die Tür, damit jeder nachlesen kann.',
        modelAnswerEnglish: 'I will happily take that on. On Monday I will show everyone in ten minutes and hang a short set of instructions on the door so that anyone can look things up.',
        quickReplies: <String>[
          'Ich helfe jedem einzeln und schreibe eine kurze Anleitung, damit nichts unklar bleibt.',
          'Ich zeige es allen einmal, damit du niemandem etwas erklären musst.',
        ],
        coachTip: 'Offering with „Das übernehme ich gern“ takes the cost off your partner and keeps the tone friendly.',
      ),
      DialogueStep(
        tutorGerman: 'Also gut, zwei Wochen probieren wir es. Aber sag mir jetzt schon: Woran messen wir am Ende, ob es wirklich besser war?',
        tutorEnglish: 'All right then, we will try it for two weeks. But tell me now: how will we measure in the end whether it really was better?',
        task: 'Name a clear success criterion and agree what happens afterwards.',
        keywords: <String>[
          'zählen',
          'rückfragen',
          'weniger',
          'wenn',
          'sonst',
          'zurück',
          'messen',
        ],
        requiredHits: 3,
        minWords: 12,
        modelAnswer: 'Wir zählen die Rückfragen, die morgens aus der Frühschicht kommen. Wenn es weniger werden, behalten wir es; sonst gehen wir zurück zum Heft.',
        modelAnswerEnglish: 'We count the queries that come in from the early shift in the morning. If there are fewer of them we keep it; otherwise we go back to the book.',
        quickReplies: <String>[
          'Wir messen die Rückfragen: Wenn sie weniger werden, war es gut.',
          'Wenn es nicht weniger Rückfragen gibt, gehen wir einfach zurück zum Heft.',
        ],
        coachTip: 'The relative clause „die morgens aus der Frühschicht kommen“ pins down exactly which queries you are going to count.',
      ),
    ],
  ),
];
