import 'conversation.dart';
import 'models.dart';

/// B2 role-plays, second batch. Original text written for this
/// app.
const List<ConversationScenario> conversationB2MoreScenarios = <ConversationScenario>[
  ConversationScenario(
    id: 'cv-b2-05',
    level: CefrLevel.b2,
    emoji: '📦',
    title: 'Der zweite Liefertermin',
    setting: 'Ein Videotelefonat mit einem Zulieferer, dessen Liefertermin schon einmal verschoben wurde.',
    tutorRole: 'Vertriebsleiter der Firma Kranzberg Metallteile',
    learnerRole: 'Einkäufer oder Einkäuferin bei Weidhaus Technik',
    goal: 'Einen verbindlichen neuen Termin aushandeln und die Zusagen absichern.',
    usefulPhrases: <String>[
      'Der Termin wurde bereits einmal verschoben.',
      'Grundsätzlich ja, allerdings …',
      'Wir bräuchten eine verbindliche Zusage.',
      'Darauf müsste ich mich verlassen können.',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Schön, dass wir sprechen. Wie Sie wissen, hat sich die Lieferung noch einmal verzögert. Wie sehen Sie die Lage?',
        tutorEnglish: 'Good that we are speaking. As you know, the delivery has been delayed once more. How do you see the situation?',
        task: 'Open by naming the delay factually and saying what it is costing your side.',
        keywords: <String>[
          'verschoben',
          'verzögerung',
          'termin',
          'montage',
          'geliefert',
          'stillstand',
          'verspätung',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Der Termin wurde bereits einmal verschoben, und die zweite Verzögerung trifft uns hart: Unsere Montage steht seit Montag still, weil die Gehäuse nicht geliefert wurden.',
        modelAnswerEnglish: 'The date has already been moved once, and the second delay hits us hard: our assembly line has been idle since Monday because the housings were not delivered.',
        quickReplies: <String>[
          'Die Verzögerung stellt uns vor ein echtes Problem.',
          'Unsere Montage wartet seit Montag auf die Gehäuse.',
          'Der Termin ist schon einmal gerissen worden.',
        ],
        coachTip: 'Naming the consequence rather than your annoyance keeps a complaint negotiable — „trifft uns hart“ states an effect, not a mood.',
      ),
      DialogueStep(
        tutorGerman: 'Das kann ich nachvollziehen. Uns fehlt allerdings ein Vormaterial, und darauf haben wir nur begrenzt Einfluss. Wie stellen Sie sich das weitere Vorgehen vor?',
        tutorEnglish: 'I can understand that. However, a raw material is missing on our side, and we have only limited influence on that. How do you envisage us proceeding?',
        task: 'Concede that the cause lies partly outside their control, then insist on a binding new date.',
        keywords: <String>[
          'gleichwohl',
          'dennoch',
          'trotzdem',
          'verbindlich',
          'termin',
          'planung',
          'zusage',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Dass Ihnen das Vormaterial fehlt, will ich gar nicht bestreiten. Gleichwohl brauchen wir jetzt einen verbindlichen Termin, auf den wir unsere Planung stützen können.',
        modelAnswerEnglish: 'I am not going to dispute that you are missing the raw material. All the same, we now need a binding date on which we can base our planning.',
        quickReplies: <String>[
          'Dass es an einem Vormaterial liegt, verstehe ich.',
          'Wir benötigen dennoch eine verbindliche Zusage.',
          'Ohne festen Termin können wir nicht planen.',
        ],
        coachTip: 'Concession first, claim second: „gleichwohl“ and „dennoch“ signal that your agreement does not cancel your demand.',
      ),
      DialogueStep(
        tutorGerman: 'Verbindlich ist ein großes Wort. Mein Kollege sagt, die Ware könne in vier Wochen bereitstehen, unter Umständen auch erst in fünf.',
        tutorEnglish: 'Binding is a big word. My colleague says the goods could be ready in four weeks, possibly only in five.',
        task: 'Push back on the vagueness and ask what the earlier date depends on.',
        keywords: <String>[
          'könne',
          'allerdings',
          'unterschied',
          'wovon',
          'hängt',
          'wochen',
          'genau',
          'abhängig',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Sie sagen, die Ware könne in vier Wochen bereitstehen. Vier oder fünf Wochen, das ist allerdings ein Unterschied. Wovon genau hängt es ab, ob es vier werden?',
        modelAnswerEnglish: 'You say the goods could be ready in four weeks. Four weeks or five, that is a difference, though. What exactly does it depend on whether it turns out to be four?',
        quickReplies: <String>[
          'Vier Wochen oder fünf Wochen, das ist ein Unterschied.',
          'Wovon hängt der frühere Termin ab?',
          'Sie sagen, es könne vier Wochen dauern.',
        ],
        coachTip: 'Reported speech in Konjunktiv I — „die Ware könne bereitstehen“ — lets you repeat their claim without adopting it as your own.',
      ),
      DialogueStep(
        tutorGerman: 'Es hängt an einer Zusage unseres Walzwerks. Wir könnten Ihnen eine Teilmenge früher schicken und den Rest später nachliefern.',
        tutorEnglish: 'It depends on a commitment from our rolling mill. We could send you a partial quantity earlier and deliver the rest later.',
        task: 'Weigh up the partial delivery: accept it in principle but name the condition that makes it useful.',
        keywords: <String>[
          'teillieferung',
          'teilmenge',
          'grundsätzlich',
          'bedingung',
          'hälfte',
          'sofern',
          'nur wenn',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Eine Teillieferung wäre grundsätzlich hilfreich, allerdings nur unter der Bedingung, dass die erste Hälfte bis zum siebten Mai hier ist. Sonst gewinnen wir nichts.',
        modelAnswerEnglish: 'A partial delivery would in principle be helpful, but only on condition that the first half is here by the seventh of May. Otherwise we gain nothing.',
        quickReplies: <String>[
          'Eine Teilmenge hilft uns nur mit einem festen Datum.',
          'Grundsätzlich ja, sofern die erste Hälfte früh kommt.',
          'Ohne Datum bringt uns die Teillieferung wenig.',
        ],
        coachTip: 'A conditional acceptance — „unter der Bedingung, dass …“ — gives ground and takes it back in the same sentence.',
      ),
      DialogueStep(
        tutorGerman: 'Ein festes Datum müsste ich erst intern prüfen. Was passiert eigentlich, wenn der Termin erneut nicht zu halten ist?',
        tutorEnglish: 'I would first have to check a firm date internally. What actually happens if the date cannot be kept again?',
        task: 'State the consequence of a second slip without turning it into a threat.',
        keywords: <String>[
          'mehrkosten',
          'extern',
          'vermeiden',
          'rückmeldung',
          'wöchentlich',
          'rechnung',
          'ersatz',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Dann müssten wir die Restmenge extern beschaffen und Ihnen die Mehrkosten in Rechnung stellen. Das möchte ich vermeiden, deshalb schlage ich eine kurze wöchentliche Rückmeldung vor.',
        modelAnswerEnglish: 'Then we would have to source the remaining quantity elsewhere and charge you the extra costs. I would like to avoid that, so I suggest a short weekly update.',
        quickReplies: <String>[
          'Dann müssten wir die Restmenge woanders einkaufen.',
          'Die Mehrkosten würden wir Ihnen weitergeben.',
          'Am liebsten wäre mir eine wöchentliche Rückmeldung.',
        ],
        coachTip: 'Putting the consequence in Konjunktiv II („müssten wir“) keeps it a shared scenario rather than an ultimatum.',
      ),
      DialogueStep(
        tutorGerman: 'Gut. Fassen wir zusammen, damit wir beide dasselbe im Protokoll stehen haben.',
        tutorEnglish: 'Good. Let us summarise, so that we both have the same thing in the minutes.',
        task: 'Summarise the agreement in your own words and ask for written confirmation.',
        keywords: <String>[
          'festgehalten',
          'hälfte',
          'schriftlich',
          'bestätigen',
          'wöchentlich',
          'ende mai',
          'zusammengefasst',
        ],
        requiredHits: 3,
        minWords: 15,
        modelAnswer: 'Festgehalten also: Die erste Hälfte kommt bis zum siebten Mai, der Rest bis Ende Mai, und wir hören wöchentlich voneinander. Bitte bestätigen Sie mir das schriftlich.',
        modelAnswerEnglish: 'So, on record: the first half arrives by the seventh of May, the rest by the end of May, and we speak weekly. Please confirm that to me in writing.',
        quickReplies: <String>[
          'Halten wir fest: erste Hälfte im Mai, Rest bis Monatsende.',
          'Schicken Sie mir das bitte noch schriftlich zu.',
          'Dann bestätigen wir beide den Plan per Mail.',
        ],
        coachTip: 'Closing with a recap plus „schriftlich“ turns a spoken concession into something you can point to later.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-b2-06',
    level: CefrLevel.b2,
    emoji: '🏥',
    title: 'Zwei Behandlungswege',
    setting: 'Ein Aufklärungsgespräch in der Ambulanz der Klinik am Auenpark.',
    tutorRole: 'Ärztin in der Ambulanz',
    learnerRole: 'Patient oder Patientin',
    goal: 'Zwei Behandlungswege abwägen, Rückfragen stellen und eine eigene Entscheidung vorbereiten.',
    usefulPhrases: <String>[
      'Was spricht dafür, was dagegen?',
      'Wie lange fällt man dabei aus?',
      'Ich würde das gern in Ruhe abwägen.',
      'Habe ich Sie richtig verstanden, dass …?',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Die Befunde liegen vor. Es gibt zwei sinnvolle Wege: eine längere konservative Behandlung oder einen kleinen Eingriff. Was wissen Sie darüber schon?',
        tutorEnglish: 'The findings are in. There are two sensible routes: a longer conservative treatment or a small procedure. What do you already know about it?',
        task: 'Say how much you have understood so far and ask for the difference to be laid out.',
        keywords: <String>[
          'unterscheiden',
          'unterschied',
          'erklären',
          'alltag',
          'bisher',
          'beiden wege',
          'entscheidend',
          'verstanden',
        ],
        requiredHits: 2,
        minWords: 16,
        modelAnswer: 'Verstanden habe ich bisher nur, dass beides möglich ist. Könnten Sie mir bitte erklären, worin sich die beiden Wege im Alltag unterscheiden? Das ist für mich entscheidend.',
        modelAnswerEnglish: 'So far I have only understood that both are possible. Could you please explain how the two routes differ in everyday life? That is what matters most to me.',
        quickReplies: <String>[
          'Ich weiß bisher nur, dass es zwei Möglichkeiten gibt.',
          'Worin unterscheiden sich die beiden Wege denn genau?',
          'Mich interessiert vor allem der Alltag danach.',
        ],
        coachTip: 'The frame „Könnten Sie mir bitte erklären …“ stays polite while still making a direct request.',
      ),
      DialogueStep(
        tutorGerman: 'Grob gesagt: Die konservative Behandlung dauert länger, greift dafür nicht ein. Der Eingriff geht schneller, bringt aber eine Wundheilung mit sich. Wie sieht Ihr Alltag aus?',
        tutorEnglish: 'Roughly speaking: the conservative treatment takes longer but does not intervene. The procedure is quicker, but brings a healing phase with it. What does your everyday life look like?',
        task: 'Describe your physically demanding job and name which trade-off weighs most for you.',
        keywords: <String>[
          'ausfallzeit',
          'arbeit',
          'schwer',
          'wochen',
          'lager',
          'deshalb',
          'krankschreibung',
          'ausfallen',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Ich arbeite im Lager und hebe täglich schwer, deshalb wiegt für mich die Ausfallzeit am schwersten. Sechs Wochen ohne Arbeit könnte ich mir kaum leisten.',
        modelAnswerEnglish: 'I work in a warehouse and lift heavy loads daily, so the time off work weighs most heavily for me. Six weeks without work I could hardly afford.',
        quickReplies: <String>[
          'Für mich zählt vor allem, wie lange ich ausfalle.',
          'Ich hebe im Beruf täglich schwere Kisten.',
          'Eine lange Krankschreibung wäre für mich schwierig.',
        ],
        coachTip: 'German ranks priorities with verbs of weight — „wiegt am schwersten“ says which factor decides for you.',
      ),
      DialogueStep(
        tutorGerman: 'Das ist ein wichtiger Punkt. Meine Kollegin meint, bei Ihrer Belastung sei der Eingriff häufig die stabilere Lösung. Sicher ist das aber nicht.',
        tutorEnglish: 'That is an important point. My colleague thinks that with your workload the procedure is often the more stable solution. But that is not certain.',
        task: 'Repeat the colleague’s claim in your own words and ask what it rests on.',
        keywords: <String>[
          'sei',
          'einschätzung',
          'stützt',
          'erfahrung',
          'stabiler',
          'worauf',
          'kollegin',
          'woher',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Ihre Kollegin meint also, der Eingriff sei bei schwerer Arbeit stabiler. Worauf stützt sich diese Einschätzung? Mich würde interessieren, ob es dazu Erfahrungswerte gibt.',
        modelAnswerEnglish: 'So your colleague reckons the procedure is more stable with heavy work. What is that assessment based on? I would be interested to know whether there is experience to go by.',
        quickReplies: <String>[
          'Woher kommt diese Einschätzung Ihrer Kollegin?',
          'Sie sagt also, der Eingriff sei stabiler.',
          'Gibt es dazu Erfahrungswerte aus der Klinik?',
        ],
        coachTip: 'Konjunktiv I („sei“) marks the claim as someone else’s, which is exactly what you want before questioning it.',
      ),
      DialogueStep(
        tutorGerman: 'Sie stützt sich auf Erfahrungen aus der Abteilung, nicht auf eine Garantie. Manche Patientinnen und Patienten wählen bewusst den langsameren Weg.',
        tutorEnglish: 'She bases that on experience from the department, not on a guarantee. Some patients deliberately choose the slower route.',
        task: 'Name what still worries you about the procedure and ask one concrete question about recovery.',
        keywords: <String>[
          'narkose',
          'wundheilung',
          'beunruhigt',
          'heben',
          'ehrlich gesagt',
          'wie lange',
          'sorge',
          'risiko',
        ],
        requiredHits: 3,
        minWords: 15,
        modelAnswer: 'Ehrlich gesagt beunruhigt mich vor allem die Narkose. Wie lange dauert die Wundheilung ungefähr, und ab wann dürfte ich wieder schwer heben, wenn alles gut verläuft?',
        modelAnswerEnglish: 'To be honest, the anaesthetic worries me most. Roughly how long does the healing take, and from when could I lift heavy things again if all goes well?',
        quickReplies: <String>[
          'Ehrlich gesagt macht mir die Narkose Sorgen.',
          'Wie lange dauert die Heilung nach dem Eingriff?',
          'Ab wann darf ich wieder schwer tragen?',
        ],
        coachTip: 'Sentence adverbs such as „ehrlich gesagt“ soften a worry and announce that a personal view follows.',
      ),
      DialogueStep(
        tutorGerman: 'Das lässt sich nur ungefähr sagen, meist sind es einige Wochen. Möchten Sie heute entscheiden, oder ist Ihnen Bedenkzeit lieber?',
        tutorEnglish: 'That can only be said approximately, usually it is a few weeks. Would you like to decide today, or would you prefer time to think it over?',
        task: 'Ask for time, but say what you will do with it and by when you will answer.',
        keywords: <String>[
          'abwägen',
          'bedenkzeit',
          'familie',
          'freitag',
          'melde',
          'besprechen',
          'betrieb',
          'in ruhe',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Ich würde das gern in Ruhe abwägen und mit meiner Familie besprechen. Bis Freitag melde ich mich bei Ihnen, dann habe ich auch mit meinem Betrieb gesprochen.',
        modelAnswerEnglish: 'I would like to weigh it up calmly and discuss it with my family. I will get back to you by Friday, by which time I will have spoken to my employer too.',
        quickReplies: <String>[
          'Ich hätte gern ein paar Tage Bedenkzeit.',
          'Das möchte ich zuerst mit meiner Familie besprechen.',
          'Bis Freitag gebe ich Ihnen Bescheid.',
        ],
        coachTip: 'A request for time lands better when you attach a deadline of your own — „Bis Freitag melde ich mich“.',
      ),
      DialogueStep(
        tutorGerman: 'Selbstverständlich. Damit Sie zu Hause in Ruhe nachlesen können: Was soll ich Ihnen mitgeben?',
        tutorEnglish: 'Of course. So that you can read up on it calmly at home: what should I give you to take along?',
        task: 'Ask for the information in writing and check that you have the next step right.',
        keywords: <String>[
          'schriftlich',
          'befunde',
          'übersicht',
          'richtig verstanden',
          'termin',
          'vereinbar',
          'unterlagen',
        ],
        requiredHits: 3,
        minWords: 15,
        modelAnswer: 'Am liebsten hätte ich beides schriftlich, also die Befunde und eine kurze Übersicht zu beiden Wegen. Habe ich richtig verstanden, dass ich den Termin danach selbst vereinbare?',
        modelAnswerEnglish: 'I would prefer both in writing, that is the findings and a short overview of the two routes. Have I understood correctly that I arrange the appointment myself afterwards?',
        quickReplies: <String>[
          'Könnte ich die Befunde bitte schriftlich bekommen?',
          'Habe ich richtig verstanden, dass ich mich selbst melde?',
          'Eine kurze Übersicht zu beiden Wegen wäre hilfreich.',
        ],
        coachTip: 'Checking back with „Habe ich richtig verstanden, dass …?“ turns your guess into something the other side can correct.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-b2-07',
    level: CefrLevel.b2,
    emoji: '🏘️',
    title: 'Die Mieterversammlung',
    setting: 'Eine Versammlung der Mieterinnen und Mieter im Hof des Hauses Lindquellweg 12.',
    tutorRole: 'Hausverwalterin der Firma Brenneke Immobilien',
    learnerRole: 'Mieter oder Mieterin',
    goal: 'Die geplante Mieterhöhung hinterfragen und einen tragbaren Kompromiss vorschlagen.',
    usefulPhrases: <String>[
      'Wie ist die Erhöhung begründet?',
      'Das lässt sich so nicht nachvollziehen.',
      'Ein Teil davon wäre für uns tragbar.',
      'Können wir das schriftlich bekommen?',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Guten Abend zusammen. Die Miete soll zum ersten Oktober um neun Prozent angehoben werden. Wer möchte anfangen?',
        tutorEnglish: 'Good evening everyone. The rent is to be raised by nine percent as of the first of October. Who would like to begin?',
        task: 'Open the discussion by asking what the increase is based on.',
        keywords: <String>[
          'prozent',
          'erhöhung',
          'begründet',
          'begründung',
          'interessieren',
          'einzelnen',
          'warum',
        ],
        requiredHits: 2,
        minWords: 15,
        modelAnswer: 'Ich fange gern an. Neun Prozent sind eine ganze Menge, deshalb würde mich zuerst interessieren, wie die Erhöhung im Einzelnen begründet wird.',
        modelAnswerEnglish: 'I am happy to begin. Nine percent is quite a lot, so I would first be interested in how the increase is justified in detail.',
        quickReplies: <String>[
          'Womit wird die Erhöhung eigentlich begründet?',
          'Neun Prozent auf einmal finde ich viel.',
          'Ich hätte gern die Begründung im Einzelnen.',
        ],
        coachTip: 'The passive „wie die Erhöhung begründet wird“ puts the reasoning, not the person, at the centre of the question.',
      ),
      DialogueStep(
        tutorGerman: 'Sie ergibt sich aus dem Mietspiegel und aus der neuen Dämmung des Dachs. Beides ist zulässig.',
        tutorEnglish: 'It follows from the local rent index and from the new insulation of the roof. Both are permissible.',
        task: 'Accept one of the two grounds, then question the other with a concrete objection.',
        keywords: <String>[
          'dämmung',
          'mietspiegel',
          'allerdings',
          'skeptisch',
          'balkon',
          'aufzug',
          'ausstattung',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Dass die Dämmung etwas kostet, bestreite ich nicht. Beim Mietspiegel bin ich allerdings skeptisch: Unsere Wohnungen haben weder Balkon noch Aufzug, das müsste doch einfließen.',
        modelAnswerEnglish: 'I do not dispute that the insulation costs something. About the rent index, though, I am sceptical: our flats have neither a balcony nor a lift, and that ought to count.',
        quickReplies: <String>[
          'Die Dämmung leuchtet mir ein, der Mietspiegel nicht.',
          'Unsere Wohnungen haben weder Balkon noch Aufzug.',
          'Beim Mietspiegel hätte ich eine Rückfrage.',
        ],
        coachTip: 'Adversative „allerdings“ lets you grant one point and attack the next without sounding hostile.',
      ),
      DialogueStep(
        tutorGerman: 'Die Ausstattung ist eingerechnet, versichert mir der Kollege aus der Verwaltung. Er sagt, das Gutachten liege den Unterlagen bei.',
        tutorEnglish: 'The fittings are included, my colleague in the administration assures me. He says the expert report is enclosed with the documents.',
        task: 'Say that you have not seen that document and ask for it in a usable form.',
        keywords: <String>[
          'gutachten',
          'unterlagen',
          'liege',
          'zwar',
          'zuschicken',
          'niemand',
          'schriftlich',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'In unseren Unterlagen lag kein Gutachten. Er sagt zwar, es liege bei, gesehen hat es hier aber niemand. Könnten Sie es allen Parteien zuschicken?',
        modelAnswerEnglish: 'There was no expert report in our documents. He says it is enclosed, but nobody here has seen it. Could you send it to all the tenants?',
        quickReplies: <String>[
          'Ein Gutachten war bei uns nicht dabei.',
          'Könnten Sie die Unterlagen an alle Parteien schicken?',
          'Gesehen hat das Gutachten hier offenbar niemand.',
        ],
        coachTip: 'Reported Konjunktiv I („es liege bei“) passes the claim on while your main clause quietly disputes it.',
      ),
      DialogueStep(
        tutorGerman: 'Gut, das lasse ich prüfen. Im Grundsatz bleibt die Erhöhung trotzdem bestehen. Wie stellen Sie sich das vor?',
        tutorEnglish: 'Fine, I will have that checked. In principle the increase nevertheless stands. How do you envisage it?',
        task: 'Propose a compromise: offer a lower percentage in two stages, in return for sealing the cellar windows.',
        keywords: <String>[
          'prozent',
          'sofern',
          'schritten',
          'mittragen',
          'kellerfenster',
          'stufen',
          'kompromiss',
        ],
        requiredHits: 3,
        minWords: 15,
        modelAnswer: 'Vier Prozent könnten wir mittragen, sofern die Erhöhung in zwei Schritten kommt und die Kellerfenster endlich abgedichtet werden. So wäre beiden Seiten geholfen.',
        modelAnswerEnglish: 'Four percent we could go along with, provided the increase comes in two stages and the cellar windows are finally sealed. That way both sides would be helped.',
        quickReplies: <String>[
          'Vier Prozent wären für uns tragbar.',
          'In zwei Stufen könnten wir es mittragen.',
          'Wir erwarten dafür, dass die Kellerfenster abgedichtet werden.',
        ],
        coachTip: 'A conditional offer with „sofern“ makes your concession depend on theirs inside one clause.',
      ),
      DialogueStep(
        tutorGerman: 'Zwei Schritte kann ich mir vorstellen, die Fenster stehen auf einer anderen Liste. Was ist Ihnen wichtiger?',
        tutorEnglish: 'Two stages I can imagine; the windows are on a different list. Which matters more to you?',
        task: 'Rank your two demands and justify the ranking.',
        keywords: <String>[
          'fenster',
          'heizkosten',
          'wichtiger',
          'während',
          'ehrlich gesagt',
          'steigen',
          'vorrang',
        ],
        requiredHits: 3,
        minWords: 15,
        modelAnswer: 'Wichtiger sind uns die Fenster, ehrlich gesagt. Die Heizkosten steigen dadurch jedes Jahr, während zwei Schritte bei der Miete am Ende dasselbe Geld kosten.',
        modelAnswerEnglish: 'The windows matter more to us, to be honest. They push up the heating costs every year, whereas two stages of rent cost the same money in the end.',
        quickReplies: <String>[
          'Uns liegt mehr an den Fenstern als an der Stufenregelung.',
          'Die Heizkosten belasten uns jedes Jahr aufs Neue.',
          'Wichtiger ist die Dichtung im Keller.',
        ],
        coachTip: 'Contrastive „während“ sets two options against each other inside a single sentence.',
      ),
      DialogueStep(
        tutorGerman: 'Verstanden. Ich nehme das mit und schreibe es ins Protokoll. Wie halten wir es mit der Rückmeldung?',
        tutorEnglish: 'Understood. I will take that away and put it in the minutes. How shall we handle the feedback?',
        task: 'Agree the next step and say what the tenants will do in the meantime.',
        keywords: <String>[
          'protokoll',
          'gutachten',
          'monatsende',
          'rückmeldung',
          'sammeln',
          'gemeinsam',
          'antworten',
        ],
        requiredHits: 3,
        minWords: 15,
        modelAnswer: 'Schicken Sie uns bitte das Protokoll und das Gutachten bis Monatsende. Wir sammeln bis dahin die Rückmeldungen aus den Wohnungen und antworten dann gemeinsam.',
        modelAnswerEnglish: 'Please send us the minutes and the expert report by the end of the month. In the meantime we will collect the responses from the flats and then reply together.',
        quickReplies: <String>[
          'Wir sammeln die Rückmeldungen aus dem Haus.',
          'Schicken Sie uns bitte das Protokoll zu.',
          'Bis Monatsende antworten wir gemeinsam.',
        ],
        coachTip: 'Closing a meeting means naming who does what by when, and German states such plans in the plain present tense.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-b2-08',
    level: CefrLevel.b2,
    emoji: '📊',
    title: 'Das Budgetgespräch',
    setting: 'Ein Termin mit der Finanzleitung über das Budget für das Projekt Talweg.',
    tutorRole: 'Leiterin Finanzen',
    learnerRole: 'Projektleiter oder Projektleiterin',
    goal: 'Das beantragte Budget verteidigen, Kürzungen abwägen und einen tragbaren Kompromiss finden.',
    usefulPhrases: <String>[
      'Die Summe setzt sich zusammen aus …',
      'Darauf kann ich nicht verzichten.',
      'Kürzen ließe sich am ehesten bei …',
      'Das würde ich ungern streichen.',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Ich habe Ihren Antrag gelesen. Achtzigtausend erscheint mir hoch. Erklären Sie mir bitte, wie die Summe zustande kommt.',
        tutorEnglish: 'I have read your application. Eighty thousand seems high to me. Please explain to me how the sum comes about.',
        task: 'Break the total down into its main parts.',
        keywords: <String>[
          'setzt sich',
          'posten',
          'lizenzen',
          'schulungen',
          'puffer',
          'entwicklung',
          'summe',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Die Summe setzt sich im Wesentlichen aus drei Posten zusammen: zweiundvierzigtausend für externe Entwicklung, dreiundzwanzigtausend für Lizenzen und der Rest für Schulungen und einen Puffer.',
        modelAnswerEnglish: 'The sum is essentially made up of three items: forty-two thousand for external development, twenty-three thousand for licences, and the rest for training and a contingency.',
        quickReplies: <String>[
          'Der größte Posten ist die externe Entwicklung.',
          'Lizenzen und Schulungen machen den Rest aus.',
          'Die Summe besteht aus drei Positionen.',
        ],
        coachTip: 'Nominal style — „Die Summe setzt sich zusammen aus …“ — is the standard German frame for breaking a figure down.',
      ),
      DialogueStep(
        tutorGerman: 'Einen Puffer sehe ich in keinem anderen Antrag. Der Vorstand streicht so etwas erfahrungsgemäß.',
        tutorEnglish: 'I see a contingency in no other application. Experience shows the board cuts such things.',
        task: 'Defend the contingency with a reason drawn from experience.',
        keywords: <String>[
          'puffer',
          'vorjahr',
          'bewusst',
          'nachbeantragen',
          'teurer',
          'zweimal',
          'erfahrung',
        ],
        requiredHits: 3,
        minWords: 15,
        modelAnswer: 'Der Puffer ist bewusst gesetzt, denn im Vorjahr mussten wir zweimal Mittel nachbeantragen. Genau das hat damals Zeit gekostet, und teurer wurde es am Ende trotzdem.',
        modelAnswerEnglish: 'The contingency is there on purpose, because last year we had to apply for extra funds twice. That is precisely what cost us time back then, and it still came out more expensive.',
        quickReplies: <String>[
          'Ohne Puffer mussten wir letztes Jahr zweimal nachfordern.',
          'Der Puffer spart am Ende Zeit und Geld.',
          'Ich habe ihn bewusst eingeplant.',
        ],
        coachTip: 'One concrete precedent defends a line item better than a general appeal to prudence.',
      ),
      DialogueStep(
        tutorGerman: 'Nachvollziehbar. Trotzdem brauche ich Bewegung. Nehmen wir an, ich streiche fünfzehn Prozent. Was passiert dann?',
        tutorEnglish: 'Understandable. Nevertheless I need movement. Suppose I cut fifteen percent. What happens then?',
        task: 'Spell out the consequence of the cut in concrete terms.',
        keywords: <String>[
          'ausbaustufe',
          'entfallen',
          'grundfunktionen',
          'schulungen',
          'prozent',
          'filialen',
          'streichen',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Bei fünfzehn Prozent müsste die zweite Ausbaustufe entfallen. Liefern könnten wir dann nur die Grundfunktionen, und die Schulungen der Filialen würden ins nächste Jahr rutschen.',
        modelAnswerEnglish: 'At fifteen percent the second expansion stage would have to go. We could then deliver only the basic functions, and the branch training would slip into next year.',
        quickReplies: <String>[
          'Dann müsste die zweite Ausbaustufe entfallen.',
          'Die Schulungen der Filialen würden verschoben.',
          'Wir könnten nur die Grundfunktionen liefern.',
        ],
        coachTip: 'Konjunktiv II („müsste entfallen“) presents the consequence as a scenario you are both examining.',
      ),
      DialogueStep(
        tutorGerman: 'Das klingt fast nach einer Drohung, so ist es sicher nicht gemeint. Wo könnten Sie von sich aus sparen?',
        tutorEnglish: 'That almost sounds like a threat, which is surely not how it is meant. Where could you save of your own accord?',
        task: 'Offer a real saving of your own and name what you will not give up.',
        keywords: <String>[
          'lizenzen',
          'sparen',
          'verzichten',
          'dagegen',
          'entwicklung',
          'günstiger',
          'kürzen',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Sparen ließe sich am ehesten bei den Lizenzen, dort finden wir eine günstigere Lösung. Auf die externe Entwicklung kann ich dagegen nicht verzichten, sonst wird der Termin unhaltbar.',
        modelAnswerEnglish: 'Savings would be easiest on the licences, where we can find a cheaper solution. External development, on the other hand, I cannot do without, or the deadline becomes untenable.',
        quickReplies: <String>[
          'Bei den Lizenzen sehe ich Spielraum.',
          'Auf die externe Entwicklung kann ich nicht verzichten.',
          'Kürzen würde ich am ehesten die Softwarekosten.',
        ],
        coachTip: 'Pair a concession with a limit: „bei den Lizenzen ließe sich sparen, auf die Entwicklung kann ich dagegen nicht verzichten“.',
      ),
      DialogueStep(
        tutorGerman: 'Am Freitag fragt der Vorstand nach dem Nutzen, nicht nach einzelnen Posten. Wie begründen wir die Ausgabe dort?',
        tutorEnglish: 'On Friday the board will ask about the benefit, not about individual line items. How do we justify the expenditure there?',
        task: 'Put the benefit into one sentence a board would accept, with a figure in it.',
        keywords: <String>[
          'spart',
          'filiale',
          'stunden',
          'investition',
          'amortisiert',
          'nutzen',
          'rechnet',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Ich würde so argumentieren: Die Umstellung spart pro Filiale etwa vier Arbeitsstunden in der Woche. Über sechzig Filialen gerechnet, hat sich die Investition im zweiten Jahr amortisiert.',
        modelAnswerEnglish: 'I would argue like this: the changeover saves about four working hours a week per branch. Across sixty branches, the investment pays for itself in the second year.',
        quickReplies: <String>[
          'Pro Filiale sparen wir etwa vier Stunden pro Woche.',
          'Die Investition rechnet sich im zweiten Jahr.',
          'Der Nutzen liegt in der eingesparten Arbeitszeit.',
        ],
        coachTip: 'A benefit argument carries further with a unit — hours per branch — than with adjectives like effizienter.',
      ),
      DialogueStep(
        tutorGerman: 'Damit kann ich arbeiten. Halten wir fest, womit ich am Freitag hineingehe.',
        tutorEnglish: 'I can work with that. Let us record what I go in with on Friday.',
        task: 'Summarise the deal you have reached and name what you still owe her.',
        keywords: <String>[
          'festgehalten',
          'puffer',
          'lizenzen',
          'mittwoch',
          'aufstellung',
          'vorstand',
          'schicke',
        ],
        requiredHits: 3,
        minWords: 14,
        modelAnswer: 'Festgehalten: siebzigtausend mit Puffer, dafür günstigere Lizenzen. Bis Mittwoch schicke ich Ihnen die neue Aufstellung und eine Folie zum Nutzen für den Vorstand.',
        modelAnswerEnglish: 'On record: seventy thousand including the contingency, with cheaper licences in return. By Wednesday I will send you the new breakdown and a slide on the benefit for the board.',
        quickReplies: <String>[
          'Halten wir fest: siebzigtausend mit Puffer.',
          'Die neue Aufstellung kommt bis Mittwoch.',
          'Eine Folie zum Nutzen bereite ich vor.',
        ],
        coachTip: 'Ending with a deadline of your own („Bis Mittwoch schicke ich …“) shows the agreement is already in motion.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-b2-09',
    level: CefrLevel.b2,
    emoji: '📄',
    title: 'Bewerbung als Teamleitung',
    setting: 'Ein zweites Gespräch bei der Softwarefirma Halbmond Systeme, für eine Stelle mit Teamverantwortung.',
    tutorRole: 'Abteilungsleiterin',
    learnerRole: 'Bewerber oder Bewerberin',
    goal: 'Fehlende Erfahrung offen benennen und trotzdem überzeugend für sich sprechen.',
    usefulPhrases: <String>[
      'Das bringe ich noch nicht mit, aber …',
      'Meine Erfahrung liegt eher in …',
      'Einarbeiten würde ich mich zügig.',
      'Darf ich dazu ein Beispiel nennen?',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Danke, dass Sie noch einmal gekommen sind. Wir suchen jemanden mit mindestens fünf Jahren Führungserfahrung. Ihre Unterlagen weisen zwei aus. Wie sehen Sie das selbst?',
        tutorEnglish: 'Thank you for coming again. We are looking for someone with at least five years of leadership experience. Your documents show two. How do you see that yourself?',
        task: 'Acknowledge the gap plainly, then reframe what you do bring.',
        keywords: <String>[
          'führung',
          'vorweisen',
          'allerdings',
          'team',
          'umstellung',
          'stimmt',
          'erfahrung',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Fünf Jahre Führung kann ich nicht vorweisen, das stimmt. In den zwei Jahren habe ich allerdings ein Team von neun Personen durch eine komplette Umstellung geführt.',
        modelAnswerEnglish: 'Five years of leadership I cannot show, that is true. In those two years, however, I led a team of nine people through a complete changeover.',
        quickReplies: <String>[
          'Fünf Jahre kann ich tatsächlich nicht vorweisen.',
          'Ich habe zwei Jahre ein Team von neun Leuten geführt.',
          'Meine Erfahrung ist kürzer, dafür sehr dicht.',
        ],
        coachTip: 'Naming the gap first („das stimmt“) buys credibility for the „allerdings“ that follows.',
      ),
      DialogueStep(
        tutorGerman: 'Neun Personen ist überschaubar. Bei uns wären es dreiundzwanzig, verteilt auf zwei Standorte. Was trauen Sie sich da zu?',
        tutorEnglish: 'Nine people is manageable. Here it would be twenty-three, spread over two sites. What do you feel up to there?',
        task: 'Say honestly what would be new for you and how you would approach it.',
        keywords: <String>[
          'standorte',
          'räume ich ein',
          'vertretung',
          'entscheidungen',
          'wochengespräche',
          'zugeben',
          'neu',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Zwei Standorte wären für mich neu, das räume ich ein. Anfangen würde ich mit festen Wochengesprächen und einer klaren Vertretung vor Ort, damit Entscheidungen nicht liegen bleiben.',
        modelAnswerEnglish: 'Two sites would be new for me, I admit that. I would start with fixed weekly meetings and a clear deputy on site, so that decisions do not stall.',
        quickReplies: <String>[
          'Zwei Standorte wären für mich tatsächlich neu.',
          'Ich würde feste Wochengespräche einführen.',
          'Vor Ort bräuchte ich eine klare Vertretung.',
        ],
        coachTip: 'Admitting a limit with „das räume ich ein“ sounds professional, and following it with a plan keeps you in the running.',
      ),
      DialogueStep(
        tutorGerman: 'Mein Kollege aus dem Betrieb meint, ohne Erfahrung mit Schichtplänen sei die Stelle kaum zu schaffen. Wie stehen Sie dazu?',
        tutorEnglish: 'My colleague from operations thinks that without experience of shift plans the role is hardly manageable. What is your position on that?',
        task: 'Handle the reported objection: take it seriously and then answer it.',
        keywords: <String>[
          'schichtpläne',
          'sei',
          'durchaus',
          'allerdings',
          'dienstpläne',
          'logistik',
          'ernst',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Er sagt, ohne Erfahrung mit Schichtplänen sei die Stelle kaum zu schaffen. Ernst nehme ich das durchaus, allerdings habe ich in der Logistik zwei Jahre lang Dienstpläne geschrieben.',
        modelAnswerEnglish: 'He says the role is hardly manageable without experience of shift plans. I do take that seriously, but I wrote duty rosters in logistics for two years.',
        quickReplies: <String>[
          'Den Einwand nehme ich ernst.',
          'Dienstpläne habe ich in der Logistik geschrieben.',
          'Schichtpläne sind mir nicht ganz fremd.',
        ],
        coachTip: 'Repeating an objection in Konjunktiv I before answering shows you heard it exactly as it was meant.',
      ),
      DialogueStep(
        tutorGerman: 'Das stand so nicht in Ihren Unterlagen. Erzählen Sie mir mehr davon, gern an einem Beispiel.',
        tutorEnglish: 'That was not in your documents in that form. Tell me more about it, ideally with an example.',
        task: 'Give one concrete example with a measurable result.',
        keywords: <String>[
          'dienstplan',
          'überstunden',
          'gesunken',
          'verteilzentrum',
          'kollegen',
          'halben jahr',
          'beispiel',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Im Verteilzentrum habe ich den Dienstplan für vierzig Kolleginnen und Kollegen erstellt. Nach einem halben Jahr waren die Überstunden um etwa ein Fünftel gesunken, ohne dass jemand gegangen ist.',
        modelAnswerEnglish: 'At the distribution centre I drew up the duty roster for forty colleagues. After six months the overtime had fallen by roughly a fifth, and nobody left over it.',
        quickReplies: <String>[
          'Ich habe den Dienstplan für vierzig Leute erstellt.',
          'Die Überstunden gingen deutlich zurück.',
          'Nach einem halben Jahr lief der Plan von allein.',
        ],
        coachTip: 'An example needs a measurable result — a share, a figure, a span of time — before it counts as evidence.',
      ),
      DialogueStep(
        tutorGerman: 'Das spricht für Sie. Uns fehlt trotzdem die Erfahrung mit Budgets in dieser Größe. Was schlagen Sie vor?',
        tutorEnglish: 'That speaks in your favour. All the same, the experience with budgets of this size is missing. What do you propose?',
        task: 'Propose an arrangement that lowers the risk for them.',
        keywords: <String>[
          'probezeit',
          'zwischengespräch',
          'budget',
          'abstimmen',
          'finanzabteilung',
          'sechs monaten',
          'vorstellbar',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Vorstellbar wäre eine Probezeit mit einem festen Zwischengespräch nach sechs Monaten. Beim Budget würde ich mich gern anfangs eng mit der Finanzabteilung abstimmen, bis die Zahlen sitzen.',
        modelAnswerEnglish: 'A probation period with a fixed review after six months would be conceivable. On the budget I would gladly coordinate closely with the finance department at first, until the figures sit right.',
        quickReplies: <String>[
          'Ein Zwischengespräch nach sechs Monaten fände ich sinnvoll.',
          'Beim Budget würde ich mich eng abstimmen.',
          'Eine Probezeit mit klaren Zielen wäre in Ordnung.',
        ],
        coachTip: 'Offering a review point turns your weak spot into a risk the employer can manage.',
      ),
      DialogueStep(
        tutorGerman: 'Gut. Bevor wir schließen: Haben Sie noch Fragen an uns?',
        tutorEnglish: 'Good. Before we finish: do you have any questions for us?',
        task: 'Ask one question that shows judgement, and close politely.',
        keywords: <String>[
          'woran',
          'besetzung',
          'merken',
          'einzuschätzen',
          'nach einem jahr',
          'erfolg',
          'erwarten',
        ],
        requiredHits: 2,
        minWords: 15,
        modelAnswer: 'Ja, eine hätte ich noch. Woran würden Sie nach einem Jahr merken, dass die Besetzung richtig war? Das hilft mir einzuschätzen, worauf ich zuerst achten sollte.',
        modelAnswerEnglish: 'Yes, one more. How would you tell after a year that the appointment was the right one? That helps me judge what to pay attention to first.',
        quickReplies: <String>[
          'Woran messen Sie den Erfolg nach einem Jahr?',
          'Was erwarten Sie in den ersten Monaten?',
          'Wie geht es nach dem heutigen Gespräch weiter?',
        ],
        coachTip: 'A closing question about success criteria signals planning rather than mere curiosity.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-b2-10',
    level: CefrLevel.b2,
    emoji: '🤝',
    title: 'Vermittlung im Team',
    setting: 'Ein Gespräch zu zweit, zwei Tage nach einem lauten Wortwechsel in der Teamsitzung.',
    tutorRole: 'Kollege Ansgar Wieland, einer der beiden Beteiligten',
    learnerRole: 'Kollegin oder Kollege, die oder der vermittelt',
    goal: 'Zwischen zwei Streitenden vermitteln, ohne Partei zu ergreifen.',
    usefulPhrases: <String>[
      'Mir geht es nicht darum, wer recht hat.',
      'Wie haben Sie die Sitzung erlebt?',
      'Verstehe ich Sie richtig, dass …?',
      'Was bräuchten Sie, damit es weitergeht?',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Danke, dass Sie sich Zeit nehmen. Ehrlich gesagt weiß ich nicht, warum wir hier sitzen. Für mich ist die Sache erledigt.',
        tutorEnglish: 'Thank you for making time. To be honest I do not know why we are sitting here. As far as I am concerned the matter is settled.',
        task: 'Open the mediation: say why the conversation is happening, without assigning blame.',
        keywords: <String>[
          'wer recht',
          'wortwechsel',
          'stimmung',
          'angespannt',
          'gehört',
          'seitdem',
          'schuld',
        ],
        requiredHits: 2,
        minWords: 16,
        modelAnswer: 'Mir geht es nicht darum, wer recht hatte. Der Wortwechsel wurde von mehreren Leuten gehört, und seitdem ist die Stimmung angespannt. Genau darüber würde ich gern sprechen.',
        modelAnswerEnglish: 'I am not concerned with who was right. The exchange was heard by several people, and the mood has been tense ever since. That is exactly what I would like to talk about.',
        quickReplies: <String>[
          'Es geht mir nicht um Schuld, sondern um die Zusammenarbeit.',
          'Die Stimmung im Team ist seitdem angespannt.',
          'Mehrere Leute haben den Wortwechsel mitbekommen.',
        ],
        coachTip: 'The passive „wurde gehört“ describes the effect without naming anyone as the culprit.',
      ),
      DialogueStep(
        tutorGerman: 'Angespannt ist die Stimmung vor allem, weil Frau Kolm mich vor allen kritisiert hat. Das war unangemessen.',
        tutorEnglish: 'The mood is tense above all because Ms Kolm criticised me in front of everyone. That was inappropriate.',
        task: 'Reflect his view back to him and ask what exactly stung.',
        keywords: <String>[
          'verstehe ich',
          'richtig',
          'kritik',
          'gestört',
          'getroffen',
          'ganzen team',
          'öffentlich',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Verstehe ich Sie richtig, dass vor allem der Ort Sie gestört hat, also die Kritik vor dem ganzen Team? Was genau hat Sie daran am meisten getroffen?',
        modelAnswerEnglish: 'Do I understand you correctly that it was mainly the setting that bothered you, that is, criticism in front of the whole team? What exactly hurt most about it?',
        quickReplies: <String>[
          'Sie stört also vor allem, dass es öffentlich war?',
          'Was hat Sie daran am meisten getroffen?',
          'Habe ich Sie richtig verstanden, dass es um den Rahmen ging?',
        ],
        coachTip: 'Paraphrasing with „Verstehe ich Sie richtig, dass …?“ checks the other person’s meaning instead of assuming it.',
      ),
      DialogueStep(
        tutorGerman: 'Getroffen hat mich, dass sie meine Zahlen angezweifelt hat, ohne vorher mit mir zu reden. Sie sagt, sie habe mich zweimal angeschrieben.',
        tutorEnglish: 'What hurt was that she doubted my figures without talking to me first. She says she wrote to me twice.',
        task: 'Take his point seriously and also give the other side its due.',
        keywords: <String>[
          'nachvollziehen',
          'allerdings',
          'angeschrieben',
          'möglicherweise',
          'nachrichten',
          'angriff',
          'vermutlich',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Dass Sie das ärgert, kann ich gut nachvollziehen. Sie sagt allerdings, sie habe Sie zweimal angeschrieben. Möglicherweise sind die Nachrichten untergegangen, gemeint war es vermutlich nicht als Angriff.',
        modelAnswerEnglish: 'I can well understand that this annoys you. She says, though, that she wrote to you twice. The messages may have got lost, and it was probably not meant as an attack.',
        quickReplies: <String>[
          'Ihren Ärger kann ich gut nachvollziehen.',
          'Möglicherweise sind die Nachrichten untergegangen.',
          'Sie sagt, sie habe Sie vorher angeschrieben.',
        ],
        coachTip: 'Hedging adverbs like „möglicherweise“ and „vermutlich“ let you offer a reading without declaring it the truth.',
      ),
      DialogueStep(
        tutorGerman: 'Untergegangen ist da nichts, ich lese meine Nachrichten. Aber gut, mag sein, dass sie es anders gemeint hat.',
        tutorEnglish: 'Nothing got lost there, I read my messages. But fine, it may be that she meant it differently.',
        task: 'Move the conversation from the past to what should happen next.',
        keywords: <String>[
          'wichtiger',
          'künftig',
          'klären',
          'zahlen',
          'sitzung',
          'nachricht',
          'zukunft',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Ob die Nachricht ankam, lässt sich heute kaum noch klären. Wichtiger wäre mir, wie Sie beide künftig mit Zahlen umgehen wollen, bevor sie in der Sitzung landen.',
        modelAnswerEnglish: 'Whether the message arrived can hardly be established now. More important to me is how the two of you want to handle figures in future, before they reach the meeting.',
        quickReplies: <String>[
          'Das lässt sich rückwirkend kaum klären.',
          'Mich interessiert mehr, wie es künftig laufen soll.',
          'Reden wir über die nächste Sitzung.',
        ],
        coachTip: 'Shifting from „wer hat recht“ to „wie machen wir es künftig“ is the standard move that unblocks a mediation.',
      ),
      DialogueStep(
        tutorGerman: 'Von mir aus. Ich erwarte nur, dass Zweifel vorher bei mir landen und nicht mitten in der Sitzung.',
        tutorEnglish: 'Fine by me. I only expect doubts to reach me beforehand and not in the middle of the meeting.',
        task: 'Turn his expectation into a concrete rule both sides could live with.',
        keywords: <String>[
          'regel',
          'zweifel',
          'einen tag',
          'sitzung',
          'telefonisch',
          'vorher',
          'vereinbaren',
        ],
        requiredHits: 3,
        minWords: 16,
        modelAnswer: 'Halten wir das doch als Regel fest: Zweifel an Zahlen gehen mindestens einen Tag vor der Sitzung direkt an die betreffende Person, und zwar telefonisch, wenn es eilig ist.',
        modelAnswerEnglish: 'Let us record that as a rule: doubts about figures go directly to the person concerned at least one day before the meeting, and by telephone if it is urgent.',
        quickReplies: <String>[
          'Zweifel kommen künftig einen Tag vorher direkt an die Person.',
          'Bei eiligen Fragen greift jemand zum Telefon.',
          'Wollen wir das als feste Regel vereinbaren?',
        ],
        coachTip: 'A workable rule names a time, a channel and a person; vague goodwill does not survive the next meeting.',
      ),
      DialogueStep(
        tutorGerman: 'Damit kann ich leben. Und was ist mit der Sitzung selbst? Zwölf Leute saßen dabei.',
        tutorEnglish: 'I can live with that. And what about the meeting itself? Twelve people were sitting there.',
        task: 'Suggest how to close the matter in front of the team, keeping both sides’ dignity.',
        keywords: <String>[
          'kurzer satz',
          'sitzung',
          'geklärt',
          'künftig',
          'entschuldigen',
          'niemand',
          'gemeinsam',
        ],
        requiredHits: 3,
        minWords: 15,
        modelAnswer: 'Ein kurzer Satz zu Beginn der nächsten Sitzung würde reichen: dass Sie beide die Sache geklärt haben und wie Sie künftig vorgehen. Entschuldigen muss sich dabei niemand.',
        modelAnswerEnglish: 'A short sentence at the start of the next meeting would be enough: that the two of you have settled the matter and how you will proceed in future. Nobody has to apologise.',
        quickReplies: <String>[
          'Ein kurzer Satz vor dem Team würde genügen.',
          'Sie könnten gemeinsam sagen, dass die Sache geklärt ist.',
          'Eine Entschuldigung halte ich nicht für nötig.',
        ],
        coachTip: 'Offering a face-saving exit — nobody has to apologise — is often what makes an agreement acceptable.',
      ),
    ],
  ),
];
