import 'conversation.dart';
import 'models.dart';

/// C1 role-plays, second batch. Original text written for this
/// app.
const List<ConversationScenario> conversationC1MoreScenarios = <ConversationScenario>[
  ConversationScenario(
    id: 'cv-c1-04',
    level: CefrLevel.c1,
    emoji: '🎓',
    title: 'Die Zulassungskommission',
    setting: 'Eine Sitzung der Zulassungskommission der Hochschule Talbrück, in der die Auswahlkriterien für das kommende Jahr überarbeitet werden.',
    tutorRole: 'Vorsitzende der Kommission, die die Tagesordnung straff führt und Widerspruch ausdrücklich einlädt',
    learnerRole: 'Mitglied der Kommission, das die bisherigen Kriterien für zu eng hält',
    goal: 'Eine Position begründen, einen Einwand entkräften und einen konkreten Vorschlag zur Abstimmung stellen.',
    usefulPhrases: <String>[
      'Ich halte das für zu eng gefasst.',
      'Dagegen spricht allerdings, dass …',
      'Ich würde dafür plädieren, …',
      'Damit wäre beiden Seiten gedient.',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Wir kommen zum ersten Punkt. Bisher entscheidet allein die Abiturnote über die Zulassung. Wie beurteilen Sie dieses Verfahren?',
        tutorEnglish: 'We come to the first point. So far the school leaving grade alone decides admission. How do you judge this procedure?',
        task: 'State your position on the current criterion and give the reason it troubles you.',
        keywords: <String>[
          'abiturnote',
          'auswahl',
          'zu eng',
          'benachteiligt',
          'bewerber',
          'geradlinig',
          'kriterien',
          'eignung',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Ich halte die ausschließlich an der Abiturnote orientierte Auswahl für zu eng, weil sie gerade jene Bewerber benachteiligt, deren Schulweg nicht geradlinig verlaufen ist.',
        modelAnswerEnglish: 'I consider a selection oriented exclusively on the leaving grade too narrow, because it disadvantages precisely those applicants whose school path did not run in a straight line.',
        quickReplies: <String>[
          'Das Verfahren erscheint mir zu eng gefasst, weil es nur eine einzige Zahl berücksichtigt.',
          'Ich sehe darin eine Benachteiligung von Bewerbern mit ungewöhnlichem Lebenslauf.',
        ],
        coachTip: 'The participial attribute „die an der Abiturnote orientierte Auswahl“ packs a whole relative clause in front of the noun, which is the register this room speaks in.',
      ),
      DialogueStep(
        tutorGerman: 'Der Einwand ist bekannt. Es wird allerdings entgegengehalten, jede weitere Hürde koste Verwaltungskapazität, die wir schlicht nicht haben.',
        tutorEnglish: 'The objection is familiar. It is countered, however, that every further hurdle costs administrative capacity that we simply do not have.',
        task: 'Acknowledge the objection and then limit it, rather than dismissing it.',
        keywords: <String>[
          'aufwand',
          'zutreffend',
          'allerdings',
          'einmalig',
          'verfahren',
          'dauerhaft',
          'kapazität',
          'einwand',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Der Einwand ist zutreffend, betrifft allerdings vor allem den einmalig anfallenden Aufwand; ist das Verfahren erst eingerichtet, hält sich die dauerhaft gebundene Kapazität in engen Grenzen.',
        modelAnswerEnglish: 'The objection is valid, but it concerns above all the one-off effort; once the procedure is set up, the permanently bound capacity stays within narrow limits.',
        quickReplies: <String>[
          'Das ist zutreffend, gilt aber nur für die Einführungsphase des Verfahrens.',
          'Der Aufwand entsteht vor allem einmalig und nicht dauerhaft.',
        ],
        coachTip: 'Conceding with „zutreffend“ before narrowing with „allerdings“ is how disagreement stays collegial in a German committee.',
      ),
      DialogueStep(
        tutorGerman: 'Nehmen wir an, wir folgen Ihnen. Woran genau wollen Sie Eignung messen, wenn nicht an der Note?',
        tutorEnglish: 'Let us assume we follow you. By what exactly do you want to measure aptitude, if not by the grade?',
        task: 'Name a concrete second criterion and say what it is supposed to show.',
        keywords: <String>[
          'motivationsschreiben',
          'praktikum',
          'gespräch',
          'ergänzen',
          'zeigen',
          'beharrlichkeit',
          'messen',
          'kriterium',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Ich würde die Note um ein kurzes Gespräch und ein einschlägiges Praktikum ergänzen, weil beides zeigen kann, ob jemand die nötige Beharrlichkeit tatsächlich mitbringt.',
        modelAnswerEnglish: 'I would supplement the grade with a short interview and a relevant internship, because both can show whether someone genuinely brings the necessary persistence.',
        quickReplies: <String>[
          'Ein strukturiertes Gespräch würde die Note sinnvoll ergänzen.',
          'Ich würde ein einschlägiges Praktikum als zweites Kriterium heranziehen.',
        ],
        coachTip: '„etwas um etwas ergänzen“ takes the accusative twice and is the standard formulation for adding a criterion.',
      ),
      DialogueStep(
        tutorGerman: 'Ein Gespräch halte ich für heikel. Erfahrungsgemäß bevorzugt es Bewerber, die sich gut verkaufen können, und nicht die fachlich Stärksten.',
        tutorEnglish: 'I consider an interview delicate. Experience shows it favours applicants who can sell themselves well, and not the strongest in the subject.',
        task: 'Accept the risk and propose how it could be contained.',
        keywords: <String>[
          'risiko',
          'besteht',
          'leitfaden',
          'strukturiert',
          'bewertungsbogen',
          'verringern',
          'geschult',
          'gefahr',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Das Risiko besteht, lässt sich aber deutlich verringern, wenn das Gespräch strikt strukturiert geführt und anhand eines vorher festgelegten Bewertungsbogens protokolliert wird.',
        modelAnswerEnglish: 'The risk exists, but it can be reduced considerably if the interview is conducted strictly structured and recorded against a previously fixed assessment sheet.',
        quickReplies: <String>[
          'Die Gefahr besteht, lässt sich mit einem festen Leitfaden aber begrenzen.',
          'Ein strukturiertes Verfahren mit Bewertungsbogen würde das Risiko verringern.',
        ],
        coachTip: 'The passive „geführt und protokolliert wird“ keeps the focus on the procedure rather than on who runs it, which is the impersonal register such minutes use.',
      ),
      DialogueStep(
        tutorGerman: 'Gut. Fassen Sie bitte zusammen, worüber wir abstimmen sollen, und zwar so, dass es ins Protokoll kann.',
        tutorEnglish: 'Good. Please sum up what we are to vote on, in a form that can go into the minutes.',
        task: 'Put your proposal into one clear sentence fit for the record.',
        keywords: <String>[
          'antrag',
          'abstimmung',
          'erprobung',
          'beantrage',
          'zwei jahre',
          'auswertung',
          'protokoll',
          'vorschlag',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Ich beantrage die auf zwei Jahre befristete Erprobung eines strukturierten Gesprächs als zweites Kriterium, verbunden mit einer Auswertung, die der Kommission vor einer Verlängerung vorgelegt wird.',
        modelAnswerEnglish: 'I move for a trial of a structured interview as a second criterion, limited to two years, together with an evaluation to be presented to the committee before any extension.',
        quickReplies: <String>[
          'Mein Antrag lautet: Erprobung des Gesprächs für zwei Jahre mit anschließender Auswertung.',
          'Zur Abstimmung stelle ich eine befristete Erprobung des zweiten Kriteriums.',
        ],
        coachTip: '„Ich beantrage“ plus a nominalised object is the fixed formula for putting something to a vote.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-c1-05',
    level: CefrLevel.c1,
    emoji: '🎙️',
    title: 'Im Radiointerview',
    setting: 'Ein Studiogespräch beim Regionalsender Nordwelle, in dem eine viel kritisierte Studie zur Sprache kommt.',
    tutorRole: 'Moderatorin, die höflich, aber hartnäckig nachfragt und Zuspitzungen anbietet',
    learnerRole: 'Mitautorin oder Mitautor der Studie',
    goal: 'Ein Ergebnis verteidigen, seine Grenzen von sich aus benennen und eine Zuspitzung zurückweisen.',
    usefulPhrases: <String>[
      'So würde ich das nicht formulieren.',
      'Was sich sagen lässt, ist Folgendes: …',
      'Das geht über unsere Daten hinaus.',
      'Darauf lassen unsere Zahlen keinen Schluss zu.',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Ihre Studie wird derzeit heftig kritisiert. Fassen Sie doch einmal zusammen, was Sie überhaupt herausgefunden haben.',
        tutorEnglish: 'Your study is being heavily criticised at the moment. Do sum up what you actually found.',
        task: 'Summarise the finding precisely, without overstating it.',
        keywords: <String>[
          'zusammenhang',
          'beobachtet',
          'untersuchten',
          'gruppe',
          'schwach',
          'belegt',
          'ergebnis',
          'daten',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Wir haben in der untersuchten Gruppe einen statistisch belegten, der Größenordnung nach aber eher schwachen Zusammenhang zwischen Lärmbelastung und Schlafqualität beobachtet.',
        modelAnswerEnglish: 'In the group we examined we observed a statistically supported, but in magnitude rather weak, relationship between noise exposure and sleep quality.',
        quickReplies: <String>[
          'Wir haben einen schwachen, aber belegten Zusammenhang in unserer Gruppe beobachtet.',
          'Das Ergebnis ist statistisch belegt, der Größenordnung nach jedoch klein.',
        ],
        coachTip: '„der Größenordnung nach“ is a postposition: the noun comes first and „nach“ follows it.',
      ),
      DialogueStep(
        tutorGerman: 'Man wirft Ihnen vor, aus einer Korrelation eine Ursache gemacht zu haben. Trifft dieser Vorwurf zu?',
        tutorEnglish: 'You are accused of having turned a correlation into a cause. Is that accusation justified?',
        task: 'Reject the accusation and say precisely what the design does and does not permit.',
        keywords: <String>[
          'vorwurf',
          'ursache',
          'behauptet',
          'querschnitt',
          'erlaubt',
          'keinen',
          'schluss',
          'korrelation',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Diesen Vorwurf weise ich zurück, denn wir haben nirgends eine Ursache behauptet; ein Querschnitt erlaubt schlicht keinen Schluss auf die Richtung des Zusammenhangs.',
        modelAnswerEnglish: 'I reject that accusation, because we nowhere claimed a cause; a cross-sectional design simply permits no conclusion about the direction of the relationship.',
        quickReplies: <String>[
          'Der Vorwurf trifft nicht zu, wir haben keine Ursache behauptet.',
          'Unser Querschnitt erlaubt keinen Schluss auf die Richtung.',
        ],
        coachTip: 'Watch the scope of the negation: „nirgends eine Ursache behauptet“ denies the claim, not the cause.',
      ),
      DialogueStep(
        tutorGerman: 'Nun sagen Kritiker, Ihre Stichprobe sei zu klein, um überhaupt etwas auszusagen. Was entgegnen Sie?',
        tutorEnglish: 'Now critics say your sample is too small to say anything at all. What do you reply?',
        task: 'Concede what is fair in the criticism and defend what survives it.',
        keywords: <String>[
          'stichprobe',
          'klein',
          'einräumen',
          'dennoch',
          'ausreichend',
          'vorsichtig',
          'formulierten',
          'kritik',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Dass die Stichprobe klein ist, räume ich ohne Weiteres ein; für den vorsichtig formulierten Befund, den wir tatsächlich berichten, ist sie dennoch ausreichend.',
        modelAnswerEnglish: 'That the sample is small I concede without further ado; for the cautiously formulated finding we actually report, it is nevertheless sufficient.',
        quickReplies: <String>[
          'Die Kritik an der Stichprobe räume ich ein, sie trifft den Befund aber nicht.',
          'Klein ist die Stichprobe, für unsere vorsichtige Aussage dennoch ausreichend.',
        ],
        coachTip: 'Fronting the „dass“ clause puts the concession first and signals that a qualification is coming.',
      ),
      DialogueStep(
        tutorGerman: 'Wenn ich Sie richtig verstehe, müsste man also nachts die Straßen sperren, damit die Menschen besser schlafen.',
        tutorEnglish: 'If I understand you correctly, one would have to close the roads at night so that people sleep better.',
        task: 'Reject the exaggeration without insulting the interviewer, and redirect.',
        keywords: <String>[
          'so würde',
          'formulieren',
          'weiter',
          'unsere daten',
          'hergeben',
          'maßnahme',
          'abwägung',
          'zuspitzung',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'So würde ich das nicht formulieren; das ginge erheblich weiter, als unsere Daten hergeben, und welche Maßnahme angemessen ist, bleibt eine politische Abwägung.',
        modelAnswerEnglish: 'I would not put it that way; that would go considerably further than our data allow, and which measure is appropriate remains a political judgement.',
        quickReplies: <String>[
          'So würde ich das nicht formulieren, das geht über unsere Daten hinaus.',
          'Diese Zuspitzung geben unsere Daten nicht her.',
        ],
        coachTip: '„So würde ich das nicht formulieren“ rejects the wording rather than the person, which keeps an interview civil.',
      ),
      DialogueStep(
        tutorGerman: 'Zum Schluss: Was müsste geschehen, damit Sie in zwei Jahren mehr sagen können als heute?',
        tutorEnglish: 'Finally: what would have to happen for you to be able to say more in two years than today?',
        task: 'Name what the next study would need and what it would then settle.',
        keywords: <String>[
          'längsschnitt',
          'wiederholt',
          'messen',
          'richtung',
          'klären',
          'nötig',
          'personen',
          'studie',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Nötig wäre ein Längsschnitt, der dieselben Personen über Jahre wiederholt misst; erst damit ließe sich die Richtung des Zusammenhangs überhaupt klären.',
        modelAnswerEnglish: 'What would be needed is a longitudinal design measuring the same people repeatedly over years; only with that could the direction of the relationship be clarified at all.',
        quickReplies: <String>[
          'Ein Längsschnitt wäre nötig, der dieselben Personen wiederholt misst.',
          'Erst eine wiederholte Messung könnte die Richtung klären.',
        ],
        coachTip: '„erst damit ließe sich … klären“ combines a restrictive „erst“ with a passive-like sich-construction.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-c1-06',
    level: CefrLevel.c1,
    emoji: '📝',
    title: 'Die gemeinsame Erklärung',
    setting: 'Ein Arbeitstreffen zweier Verbände, die sich auf den Wortlaut einer gemeinsamen Presseerklärung einigen müssen.',
    tutorRole: 'Verhandlungsführer der Gegenseite, der auf einer schärferen Formulierung besteht',
    learnerRole: 'Verhandlungsführerin oder Verhandlungsführer Ihres Verbandes',
    goal: 'Eine Formulierung abwehren, eine tragfähige Alternative anbieten und den Kompromiss festhalten.',
    usefulPhrases: <String>[
      'Darauf können wir uns nicht einlassen.',
      'Mein Gegenvorschlag lautet …',
      'Damit wäre uns beiden gedient.',
      'Halten wir das so fest?',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Unser Entwurf spricht von einem Versagen der Behörden. Ich gehe davon aus, dass Sie damit leben können.',
        tutorEnglish: 'Our draft speaks of a failure of the authorities. I assume you can live with that.',
        task: 'Reject the word and say why it costs you something.',
        keywords: <String>[
          'versagen',
          'einlassen',
          'wortwahl',
          'zuweisung',
          'schuld',
          'gespräch',
          'erschwert',
          'formulierung',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Auf das Wort Versagen können wir uns nicht einlassen, denn eine derart eindeutige Zuweisung von Schuld erschwert jedes weitere Gespräch mit genau den Stellen, die wir brauchen.',
        modelAnswerEnglish: 'We cannot agree to the word failure, because such an unambiguous assignment of blame makes every further conversation with precisely the offices we need more difficult.',
        quickReplies: <String>[
          'Diese Wortwahl können wir nicht mittragen, sie erschwert das weitere Gespräch.',
          'Auf eine so klare Zuweisung von Schuld lassen wir uns nicht ein.',
        ],
        coachTip: '„sich auf etwas einlassen“ governs the accusative and is the standard verb for accepting a negotiating position.',
      ),
      DialogueStep(
        tutorGerman: 'Ohne ein klares Wort verpufft die Erklärung aber. Unsere Mitglieder erwarten, dass wir das Kind beim Namen nennen.',
        tutorEnglish: 'Without a clear word the statement fizzles out. Our members expect us to call a spade a spade.',
        task: 'Acknowledge their pressure and offer a wording that is still clear.',
        keywords: <String>[
          'verstehe',
          'erwartung',
          'vorschlagen',
          'deutlich',
          'mängel',
          'benennen',
          'ohne',
          'gegenvorschlag',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Ihre Erwartung verstehe ich; ich würde vorschlagen, die Mängel deutlich zu benennen, ohne sie zugleich einer einzelnen Behörde als Versagen zuzurechnen.',
        modelAnswerEnglish: 'I understand your expectation; I would propose naming the shortcomings clearly, without at the same time attributing them to a single authority as failure.',
        quickReplies: <String>[
          'Mein Gegenvorschlag: die Mängel deutlich benennen, aber ohne Schuldzuweisung.',
          'Wir können das deutlich benennen, ohne von Versagen zu sprechen.',
        ],
        coachTip: '„ohne … zu“ takes an infinitive and shares its subject with the main clause.',
      ),
      DialogueStep(
        tutorGerman: 'Das klingt mir zu weich. Wenn niemand genannt wird, liest es sich, als sei nichts geschehen.',
        tutorEnglish: 'That sounds too soft to me. If nobody is named, it reads as if nothing had happened.',
        task: 'Disagree with the reading and show what makes your version strong.',
        keywords: <String>[
          'gegenteil',
          'konkret',
          'zahlen',
          'termine',
          'wirken',
          'schwächer',
          'gerade',
          'belegen',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Das Gegenteil ist der Fall: gerade weil wir konkrete Zahlen und Termine nennen, wirkt die Erklärung nicht schwächer, sondern nachprüfbar.',
        modelAnswerEnglish: 'The opposite is the case: precisely because we name concrete figures and dates, the statement does not read weaker, but verifiable.',
        quickReplies: <String>[
          'Im Gegenteil, konkrete Zahlen wirken stärker als ein hartes Wort.',
          'Gerade die genannten Termine machen die Erklärung nachprüfbar.',
        ],
        coachTip: '„nicht …, sondern …“ corrects the first term rather than merely negating it.',
      ),
      DialogueStep(
        tutorGerman: 'Also gut. Dann brauche ich von Ihnen einen Satz, den ich meinen Leuten heute Abend vorlegen kann.',
        tutorEnglish: 'All right then. Then I need one sentence from you that I can put to my people this evening.',
        task: 'Produce the actual compromise sentence.',
        keywords: <String>[
          'vorschlagen',
          'satz',
          'aufsicht',
          'unzureichend',
          'fordern',
          'beide',
          'verbände',
          'wortlaut',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Ich schlage folgenden Wortlaut vor: Beide Verbände stellen fest, dass die Aufsicht in den geprüften Fällen unzureichend war, und fordern eine unabhängige Untersuchung.',
        modelAnswerEnglish: 'I propose the following wording: both associations state that supervision was inadequate in the cases examined, and call for an independent investigation.',
        quickReplies: <String>[
          'Mein Vorschlag: die Aufsicht war unzureichend, wir fordern eine Untersuchung.',
          'Wir könnten festhalten, dass beide Verbände eine unabhängige Prüfung fordern.',
        ],
        coachTip: '„feststellen, dass …“ reports a shared finding without naming a culprit, which is what a joint statement needs.',
      ),
      DialogueStep(
        tutorGerman: 'Damit kann ich arbeiten. Halten wir es so fest, oder wollen Sie noch etwas ändern?',
        tutorEnglish: 'I can work with that. Shall we record it like this, or do you want to change anything else?',
        task: 'Confirm the agreement and add one condition about how it is published.',
        keywords: <String>[
          'einverstanden',
          'bedingung',
          'gleichzeitig',
          'veröffentlichen',
          'beide',
          'abgestimmt',
          'festhalten',
          'vorab',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Einverstanden, mit einer Bedingung: Wir veröffentlichen den abgestimmten Text gleichzeitig, damit keine Seite ihn vorab in eigener Auslegung weitergibt.',
        modelAnswerEnglish: 'Agreed, with one condition: we publish the agreed text simultaneously, so that neither side passes it on beforehand in its own interpretation.',
        quickReplies: <String>[
          'Einverstanden, sofern wir beide gleichzeitig veröffentlichen.',
          'Halten wir das so fest, mit der Bedingung einer abgestimmten Veröffentlichung.',
        ],
        coachTip: '„damit“ introduces a purpose clause with its own subject, unlike „um … zu“.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-c1-07',
    level: CefrLevel.c1,
    emoji: '⚖️',
    title: 'Vor der Ethikkommission',
    setting: 'Eine Anhörung der Ethikkommission über die Weiterverwendung von Daten, die ursprünglich zu einem anderen Zweck erhoben wurden.',
    tutorRole: 'Vorsitzender der Kommission, der freundlich, aber sehr genau nachfragt',
    learnerRole: 'Antragstellerin oder Antragsteller des Forschungsvorhabens',
    goal: 'Den Antrag begründen, den Einwand der Zweckbindung ernst nehmen und Schutzmaßnahmen zusagen.',
    usefulPhrases: <String>[
      'Der Antrag zielt darauf ab, …',
      'Diesen Einwand nehme ich ernst.',
      'Wir würden uns verpflichten, …',
      'Darauf würde ich verzichten.',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Sie möchten Daten weiterverwenden, die für eine andere Fragestellung erhoben wurden. Begründen Sie bitte, warum das nötig ist.',
        tutorEnglish: 'You wish to reuse data collected for a different question. Please justify why that is necessary.',
        task: 'Justify the reuse in terms of what it avoids as well as what it gains.',
        keywords: <String>[
          'antrag',
          'zielt',
          'erneute',
          'befragung',
          'erspart',
          'belastung',
          'vorhandenen',
          'daten',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Der Antrag zielt darauf ab, aus den bereits vorhandenen Daten eine zweite Frage zu beantworten, und erspart damit den Betroffenen eine erneute Befragung samt der damit verbundenen Belastung.',
        modelAnswerEnglish: 'The application aims to answer a second question from the data already held, and thereby spares those concerned a fresh survey along with the burden that goes with it.',
        quickReplies: <String>[
          'Wir wollen aus vorhandenen Daten eine zweite Frage beantworten.',
          'Eine erneute Befragung würde den Betroffenen unnötige Belastung bringen.',
        ],
        coachTip: '„darauf abzielen, etwas zu tun“ is a functional verb construction: the preposition is fixed and the infinitive follows.',
      ),
      DialogueStep(
        tutorGerman: 'Die Einwilligung bezog sich seinerzeit ausdrücklich auf ein anderes Vorhaben. Wie gehen Sie mit dieser Zweckbindung um?',
        tutorEnglish: 'The consent at the time referred explicitly to a different project. How do you deal with this purpose limitation?',
        task: 'Take the objection seriously and say what you would do about it.',
        keywords: <String>[
          'einwand',
          'ernst',
          'zweckbindung',
          'einwilligung',
          'erneut',
          'einholen',
          'erreichbar',
          'verzichten',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Diesen Einwand nehme ich ernst; wir würden die Einwilligung dort erneut einholen, wo die Betroffenen erreichbar sind, und auf die übrigen Datensätze schlicht verzichten.',
        modelAnswerEnglish: 'I take this objection seriously; we would obtain consent again where those concerned are reachable, and simply forgo the remaining records.',
        quickReplies: <String>[
          'Wir würden die Einwilligung erneut einholen, soweit das möglich ist.',
          'Auf nicht erreichbare Fälle würden wir verzichten.',
        ],
        coachTip: 'Offering to give something up before being asked is what makes a concession credible in a hearing.',
      ),
      DialogueStep(
        tutorGerman: 'Damit schrumpft Ihre Stichprobe erheblich. Es wäre bequemer, die Daten anonymisiert einfach weiterzuverwenden.',
        tutorEnglish: 'That shrinks your sample considerably. It would be more convenient simply to reuse the data anonymised.',
        task: 'Explain why the convenient route is not acceptable to you.',
        keywords: <String>[
          'bequemer',
          'wäre',
          'anonymisierung',
          'rückgängig',
          'vertrauen',
          'verlust',
          'nicht',
          'argument',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Bequemer wäre es zweifellos, doch eine nachträgliche Anonymisierung macht die ursprüngliche Zusage nicht rückgängig, und der Verlust an Vertrauen wöge schwerer als die kleinere Stichprobe.',
        modelAnswerEnglish: 'It would undoubtedly be more convenient, but a subsequent anonymisation does not undo the original promise, and the loss of trust would weigh heavier than the smaller sample.',
        quickReplies: <String>[
          'Bequemer wäre es, doch das Vertrauen wöge schwerer als die Stichprobe.',
          'Anonymisierung macht die ursprüngliche Zusage nicht rückgängig.',
        ],
        coachTip: 'Starting with the concession „Bequemer wäre es“ and turning on „doch“ is a compact way to refuse without sounding rigid.',
      ),
      DialogueStep(
        tutorGerman: 'Nehmen wir an, wir stimmen zu. Welche Auflagen halten Sie selbst für angemessen?',
        tutorEnglish: 'Suppose we agree. Which conditions do you yourself consider appropriate?',
        task: 'Propose the conditions you would accept, before they are imposed.',
        keywords: <String>[
          'verpflichten',
          'löschen',
          'frist',
          'zugriff',
          'beschränken',
          'bericht',
          'auflagen',
          'getrennt',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Wir würden uns verpflichten, den Zugriff auf drei namentlich benannte Personen zu beschränken, die Daten nach Abschluss zu löschen und der Kommission einen Bericht vorzulegen.',
        modelAnswerEnglish: 'We would undertake to restrict access to three named persons, to delete the data on completion, and to submit a report to the committee.',
        quickReplies: <String>[
          'Wir würden den Zugriff beschränken und die Daten nach Abschluss löschen.',
          'Eine Frist zur Löschung und ein Bericht wären für uns selbstverständlich.',
        ],
        coachTip: '„sich verpflichten, etwas zu tun“ takes a reflexive pronoun and a zu-infinitive, and is the register of a formal undertaking.',
      ),
      DialogueStep(
        tutorGerman: 'Eine letzte Frage: Was würden Sie tun, wenn sich während der Auswertung ein Befund ergibt, der einzelne Personen betrifft?',
        tutorEnglish: 'One last question: what would you do if a finding emerged during the analysis that concerns individual persons?',
        task: 'Say what you would do and where you would draw the line.',
        keywords: <String>[
          'befund',
          'einzelne',
          'melden',
          'vorher',
          'festgelegt',
          'verfahren',
          'weder',
          'eigenmächtig',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Ein solcher Befund würde weder eigenmächtig weitergegeben noch stillschweigend übergangen, sondern nach einem vorher festgelegten Verfahren der Kommission gemeldet.',
        modelAnswerEnglish: 'Such a finding would neither be passed on unilaterally nor silently ignored, but reported to the committee according to a previously fixed procedure.',
        quickReplies: <String>[
          'Wir würden das nach einem vorher festgelegten Verfahren melden.',
          'Weder eigenmächtig weitergeben noch verschweigen, sondern der Kommission vorlegen.',
        ],
        coachTip: '„weder … noch …, sondern …“ rules out two options and names the third, and keeps the verb in the bracket at the end.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-c1-08',
    level: CefrLevel.c1,
    emoji: '📊',
    title: 'In der Förderkommission',
    setting: 'Eine Sitzung der Förderkommission der Stiftung Weidmoor, in der über einen Antrag entschieden wird, den Sie selbst nur teilweise überzeugend finden.',
    tutorRole: 'Kommissionsvorsitzende, die Klarheit über Ihre eigene Haltung verlangt',
    learnerRole: 'Berichterstatterin oder Berichterstatter für diesen Antrag',
    goal: 'Für einen Antrag sprechen, dessen Schwächen Sie selbst sehen, ohne die Kommission zu täuschen.',
    usefulPhrases: <String>[
      'Ich berichte über den Antrag …',
      'Uneingeschränkt überzeugt bin ich nicht.',
      'Dafür spricht allerdings …',
      'Ich empfehle die Förderung unter Auflagen.',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Sie berichten heute über den Antrag aus Weidenbach. Geben Sie uns bitte zunächst Ihre Einschätzung.',
        tutorEnglish: 'You are reporting today on the application from Weidenbach. Please give us your assessment first.',
        task: 'Give an assessment that names both the strength and your reservation.',
        keywords: <String>[
          'antrag',
          'fragestellung',
          'tragfähig',
          'methodisch',
          'zurückhaltend',
          'überzeugt',
          'einschätzung',
          'teilweise',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Der Antrag verfolgt eine tragfähige Fragestellung, methodisch bin ich allerdings zurückhaltend; uneingeschränkt überzeugt bin ich von der vorgeschlagenen Erhebung nicht.',
        modelAnswerEnglish: 'The application pursues a viable question, but methodologically I am reserved; I am not unreservedly convinced by the proposed survey.',
        quickReplies: <String>[
          'Die Fragestellung ist tragfähig, die Methode überzeugt mich nur teilweise.',
          'Inhaltlich gut, methodisch bin ich zurückhaltend.',
        ],
        coachTip: 'Fronting „methodisch“ signals which aspect the reservation attaches to before the reservation itself arrives.',
      ),
      DialogueStep(
        tutorGerman: 'Das klingt nach Ablehnung. Sagen Sie doch bitte deutlich, ob Sie dafür oder dagegen sind.',
        tutorEnglish: 'That sounds like rejection. Please say clearly whether you are for or against.',
        task: 'State a clear position while keeping the reservation visible.',
        keywords: <String>[
          'dafür',
          'gleichwohl',
          'empfehle',
          'förderung',
          'obwohl',
          'trage',
          'vorbehalt',
          'dagegen',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Ich bin dafür, gleichwohl mit Vorbehalt: Ich empfehle die Förderung, obwohl ich die Erhebung für die schwächste Stelle des Vorhabens halte.',
        modelAnswerEnglish: 'I am in favour, albeit with reservation: I recommend funding, although I consider the survey the weakest point of the project.',
        quickReplies: <String>[
          'Ich bin dafür, allerdings mit einem klaren Vorbehalt.',
          'Ich empfehle die Förderung, trage die methodische Kritik aber mit.',
        ],
        coachTip: '„gleichwohl“ concedes and continues in one word, which is why committee German reaches for it so often.',
      ),
      DialogueStep(
        tutorGerman: 'Ein Mitglied hat eingewandt, vergleichbare Vorhaben seien mehrfach gescheitert. Wie ordnen Sie das ein?',
        tutorEnglish: 'A member objected that comparable projects have failed several times. How do you place that?',
        task: 'Deal with the comparison rather than dismissing it.',
        keywords: <String>[
          'vergleich',
          'trifft',
          'insofern',
          'unterscheidet',
          'vorarbeiten',
          'gescheitert',
          'allerdings',
          'vorhaben',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Der Vergleich trifft insofern zu, als ähnliche Vorhaben gescheitert sind; er unterschlägt allerdings, dass hier belastbare Vorarbeiten aus zwei Jahren bereits vorliegen.',
        modelAnswerEnglish: 'The comparison holds insofar as similar projects have failed; it overlooks, however, that solid preliminary work from two years already exists here.',
        quickReplies: <String>[
          'Der Vergleich trifft teilweise zu, unterschlägt aber die Vorarbeiten.',
          'Ähnliche Vorhaben sind gescheitert, hier liegen allerdings Vorarbeiten vor.',
        ],
        coachTip: '„insofern …, als …“ limits an agreement to exactly the part you accept.',
      ),
      DialogueStep(
        tutorGerman: 'Und wenn wir Ihrem Vorbehalt folgen wollten, was müsste sich am Antrag ändern?',
        tutorEnglish: 'And if we wanted to follow your reservation, what would have to change in the application?',
        task: 'Name the change you would require and what it would prove.',
        keywords: <String>[
          'vorstudie',
          'verlangen',
          'kleiner',
          'stichprobe',
          'zeigen',
          'verfahren',
          'trägt',
          'auflage',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Ich würde eine Vorstudie an kleiner Stichprobe verlangen, die zeigen müsste, ob das vorgeschlagene Verfahren im Feld überhaupt trägt.',
        modelAnswerEnglish: 'I would require a preliminary study on a small sample, which would have to show whether the proposed procedure holds up in the field at all.',
        quickReplies: <String>[
          'Eine Vorstudie an kleiner Stichprobe wäre die Auflage meiner Wahl.',
          'Der Antrag müsste zeigen, ob das Verfahren im Feld trägt.',
        ],
        coachTip: 'The relative clause with „müsste“ states the condition the preliminary study has to satisfy.',
      ),
      DialogueStep(
        tutorGerman: 'Gut. Formulieren Sie bitte Ihre Empfehlung so, wie sie im Beschluss stehen soll.',
        tutorEnglish: 'Good. Please formulate your recommendation as it should appear in the decision.',
        task: 'Give the recommendation in the form the minutes need.',
        keywords: <String>[
          'empfehle',
          'förderung',
          'auflage',
          'vorstudie',
          'zweite',
          'rate',
          'abhängig',
          'beschluss',
        ],
        requiredHits: 3,
        minWords: 18,
        modelAnswer: 'Ich empfehle die Förderung unter der Auflage einer Vorstudie, wobei die zweite Rate erst nach deren Auswertung und abhängig von ihrem Ergebnis freigegeben wird.',
        modelAnswerEnglish: 'I recommend funding subject to a preliminary study, with the second instalment released only after its evaluation and depending on its result.',
        quickReplies: <String>[
          'Empfehlung: Förderung unter der Auflage einer Vorstudie.',
          'Die zweite Rate sollte erst nach Auswertung der Vorstudie fließen.',
        ],
        coachTip: '„unter der Auflage einer …“ takes the genitive and is the fixed phrase for a conditional grant.',
      ),
    ],
  ),
];
