import 'conversation.dart';
import 'models.dart';

/// A2 role-plays, second batch. Original text written for this
/// app.
const List<ConversationScenario> conversationA2MoreScenarios = <ConversationScenario>[
  ConversationScenario(
    id: 'cv-a2-06',
    level: CefrLevel.a2,
    emoji: '🏦',
    title: 'Ein Konto eröffnen',
    setting: 'A small branch of the Rosenweg Bank on a quiet afternoon. You have been in the country for two months and need an account for your salary.',
    tutorRole: 'Bankberaterin (bank adviser)',
    learnerRole: 'Kunde oder Kundin (customer)',
    goal: 'Say what account you need, answer the adviser\'s questions and ask about costs and dates.',
    usefulPhrases: <String>[
      'Ich möchte ein Konto eröffnen.',
      'Was kostet das im Monat?',
      'Meinen Ausweis habe ich dabei.',
      'Ab wann kann ich das Konto nutzen?',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Guten Tag, willkommen bei der Rosenweg Bank. Wie kann ich Ihnen helfen?',
        tutorEnglish: 'Hello, welcome to Rosenweg Bank. How can I help you?',
        task: 'Say why you have come and what kind of account you want.',
        keywords: <String>[
          'konto',
          'eröffnen',
          'möchte',
          'weil',
          'girokonto',
          'arbeite',
          'brauche',
        ],
        requiredHits: 3,
        minWords: 7,
        modelAnswer: 'Guten Tag. Ich möchte ein Girokonto eröffnen, weil ich hier jetzt arbeite.',
        modelAnswerEnglish: 'Hello. I would like to open a current account, because I work here now.',
        quickReplies: <String>[
          'Ich möchte gern ein Konto eröffnen.',
          'Guten Tag, ich brauche ein Girokonto.',
        ],
        coachTip: 'After „weil“ the finite verb moves to the very end of the clause.',
      ),
      DialogueStep(
        tutorGerman: 'Sehr gern. Haben Sie einen Ausweis und eine Meldebescheinigung dabei?',
        tutorEnglish: 'Gladly. Do you have an ID and a registration certificate with you?',
        task: 'Say which documents you brought and which one is missing.',
        keywords: <String>[
          'ausweis',
          'dabei',
          'vergessen',
          'leider',
          'meldebescheinigung',
          'reisepass',
        ],
        requiredHits: 3,
        minWords: 7,
        modelAnswer: 'Meinen Ausweis habe ich dabei, aber die Meldebescheinigung habe ich leider vergessen.',
        modelAnswerEnglish: 'I have my ID with me, but I have unfortunately forgotten the registration certificate.',
        quickReplies: <String>[
          'Ich habe nur meinen Ausweis dabei.',
          'Beides habe ich hier in der Tasche.',
        ],
        coachTip: 'German lets you open with the object, as in „Meinen Ausweis habe ich dabei“, as long as the verb stays in second position.',
      ),
      DialogueStep(
        tutorGerman: 'Gut, das prüfe ich gleich. Möchten Sie das Konto allein führen oder zusammen mit jemandem?',
        tutorEnglish: 'Good, I will check that in a moment. Would you like the account in your name alone or together with someone?',
        task: 'Say whether the account is just for you, and give a short reason.',
        keywords: <String>[
          'allein',
          'konto',
          'weil',
          'möchte',
          'eigenes',
          'zusammen',
          'partner',
        ],
        requiredHits: 3,
        minWords: 7,
        modelAnswer: 'Ich möchte das Konto allein führen, weil meine Frau schon ein eigenes hat.',
        modelAnswerEnglish: 'I would like the account in my name alone, because my wife already has one of her own.',
        quickReplies: <String>[
          'Nur für mich allein, bitte.',
          'Zusammen mit meinem Mann, bitte.',
        ],
        coachTip: 'A modal verb sends the main verb to the end in its infinitive form: ich möchte das Konto allein führen.',
      ),
      DialogueStep(
        tutorGerman: 'Gut. Das Girokonto kostet vier Euro neunzig im Monat, die Karte ist inklusive.',
        tutorEnglish: 'Good. The current account costs four euros ninety a month, the card is included.',
        task: 'React to the price and ask about one further cost.',
        keywords: <String>[
          'kostet',
          'abheben',
          'automat',
          'ordnung',
          'teuer',
          'gebühren',
        ],
        requiredHits: 2,
        minWords: 7,
        modelAnswer: 'Das finde ich in Ordnung. Kostet das Abheben am Automaten auch etwas?',
        modelAnswerEnglish: 'I think that is fine. Does taking money out at the machine cost something too?',
        quickReplies: <String>[
          'Das ist in Ordnung. Was kostet die Karte?',
          'Das finde ich ein bisschen teuer.',
        ],
        coachTip: 'A yes/no question puts the verb first: „Kostet das Abheben etwas?“',
      ),
      DialogueStep(
        tutorGerman: 'Bei unseren Automaten ist das kostenlos, bei fremden Banken nicht. Haben Sie sonst noch Fragen?',
        tutorEnglish: 'At our own machines it is free, at other banks it is not. Do you have any other questions?',
        task: 'Ask when the account starts working and how the card reaches you.',
        keywords: <String>[
          'ab wann',
          'wann',
          'konto',
          'nutzen',
          'karte',
          'schicken',
        ],
        requiredHits: 3,
        minWords: 7,
        modelAnswer: 'Ja, ab wann kann ich das Konto nutzen und wann kommt die Karte?',
        modelAnswerEnglish: 'Yes, from when can I use the account and when does the card come?',
        quickReplies: <String>[
          'Ab wann kann ich das Konto benutzen?',
          'Wann bekomme ich meine Karte?',
        ],
        coachTip: 'Two questions in one turn are joined with „und“, and the second one keeps its own question word.',
      ),
      DialogueStep(
        tutorGerman: 'Die Karte kommt in etwa einer Woche mit der Post. Ich drucke Ihnen die Unterlagen aus, bitte bringen Sie sie unterschrieben zurück.',
        tutorEnglish: 'The card comes by post in about a week. I will print out the papers for you, please bring them back signed.',
        task: 'Thank her and say when you will bring the papers back.',
        keywords: <String>[
          'dank',
          'unterlagen',
          'bringe',
          'nächste',
          'woche',
          'wiedersehen',
          'tschüss',
        ],
        requiredHits: 3,
        minWords: 6,
        modelAnswer: 'Vielen Dank. Die Unterlagen bringe ich nächste Woche vorbei. Auf Wiedersehen!',
        modelAnswerEnglish: 'Thank you very much. I will bring the papers by next week. Goodbye!',
        quickReplies: <String>[
          'Vielen Dank, ich bringe alles nächste Woche.',
          'Danke schön, auf Wiedersehen!',
        ],
        coachTip: 'Separable verbs split in the present tense: vorbeibringen becomes ich bringe die Unterlagen vorbei.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-a2-07',
    level: CefrLevel.a2,
    emoji: '🧳',
    title: 'Im Fundbüro',
    setting: 'The lost property office at Kleinbergen main station, twenty minutes after you got off your train.',
    tutorRole: 'Mitarbeiter im Fundbüro (lost property clerk)',
    learnerRole: 'Reisende oder Reisender (traveller)',
    goal: 'Report what you lost, describe it clearly and agree what happens next.',
    usefulPhrases: <String>[
      'Ich habe meine Tasche verloren.',
      'Sie ist aus Stoff und dunkelblau.',
      'Können Sie bitte nachsehen?',
      'Ich gebe Ihnen meine Nummer.',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Guten Tag, Fundbüro Kleinbergen. Was kann ich für Sie tun?',
        tutorEnglish: 'Hello, Kleinbergen lost property office. What can I do for you?',
        task: 'Report what you have lost and where it happened.',
        keywords: <String>[
          'tasche',
          'vergessen',
          'zug',
          'verloren',
          'liegen lassen',
          'gepäck',
        ],
        requiredHits: 2,
        minWords: 7,
        modelAnswer: 'Guten Tag. Ich habe meine Tasche im Zug nach Kleinbergen vergessen.',
        modelAnswerEnglish: 'Hello. I left my bag on the train to Kleinbergen.',
        quickReplies: <String>[
          'Ich habe meine Tasche im Zug verloren.',
          'Meine Tasche ist weg, ich habe sie liegen lassen.',
        ],
        coachTip: 'Everyday past events take the Perfekt: haben plus the participle right at the end.',
      ),
      DialogueStep(
        tutorGerman: 'Das tut mir leid. Beschreiben Sie mir bitte die Tasche ganz genau.',
        tutorEnglish: 'I am sorry to hear that. Please describe the bag to me exactly.',
        task: 'Describe the bag: size, colour and material.',
        keywords: <String>[
          'blau',
          'groß',
          'stoff',
          'riemen',
          'leder',
          'schwarz',
          'klein',
        ],
        requiredHits: 3,
        minWords: 7,
        modelAnswer: 'Sie ist ziemlich groß, dunkelblau und aus Stoff, mit einem langen Riemen.',
        modelAnswerEnglish: 'It is quite big, dark blue and made of fabric, with a long strap.',
        quickReplies: <String>[
          'Sie ist braun und ziemlich klein.',
          'Es ist eine große Tasche aus Leder.',
        ],
        coachTip: 'Adjectives after „ist“ take no ending at all: sie ist groß, dunkelblau und alt.',
      ),
      DialogueStep(
        tutorGerman: 'Und was war in der Tasche? Ich schreibe alles mit.',
        tutorEnglish: 'And what was in the bag? I am writing everything down.',
        task: 'List what was inside and name the item that matters most.',
        keywords: <String>[
          'laptop',
          'kleidung',
          'papiere',
          'wichtig',
          'schlüssel',
          'geldbeutel',
        ],
        requiredHits: 3,
        minWords: 7,
        modelAnswer: 'Darin waren ein Laptop und Kleidung, aber am wichtigsten sind meine Papiere.',
        modelAnswerEnglish: 'Inside there were a laptop and clothes, but the most important thing is my papers.',
        quickReplies: <String>[
          'Mein Laptop und meine Papiere waren darin.',
          'Vor allem mein Schlüssel war in der Tasche.',
        ],
        coachTip: 'For was and were German prefers the Präteritum of sein: es war, sie waren.',
      ),
      DialogueStep(
        tutorGerman: 'Heute hat noch niemand eine solche Tasche abgegeben. Meistens kommen die Sachen erst am nächsten Tag zu uns.',
        tutorEnglish: 'Nobody has handed in a bag like that today. Usually things only reach us the next day.',
        task: 'React to the news and ask what you should do now.',
        keywords: <String>[
          'schade',
          'was soll ich',
          'morgen',
          'wiederkommen',
          'was kann ich',
          'anrufen',
        ],
        requiredHits: 2,
        minWords: 7,
        modelAnswer: 'Das ist schade. Was soll ich jetzt machen, und soll ich morgen wiederkommen?',
        modelAnswerEnglish: 'That is a pity. What should I do now, and should I come back tomorrow?',
        quickReplies: <String>[
          'Oh nein. Was kann ich jetzt tun?',
          'Soll ich morgen noch einmal kommen?',
        ],
        coachTip: 'Asking for instructions stays polite with „sollen“: Was soll ich jetzt machen?',
      ),
      DialogueStep(
        tutorGerman: 'Am besten nehme ich Ihre Daten auf. Wie erreichen wir Sie, wenn die Tasche auftaucht?',
        tutorEnglish: 'It is best if I take down your details. How do we reach you if the bag turns up?',
        task: 'Give one way to reach you and the best time of day.',
        keywords: <String>[
          'handy',
          'rufen',
          'nachmittag',
          'nummer',
          'erreichen',
          'mail',
        ],
        requiredHits: 2,
        minWords: 7,
        modelAnswer: 'Rufen Sie mich bitte auf dem Handy an, am besten nachmittags nach vier.',
        modelAnswerEnglish: 'Please call me on my mobile, ideally in the afternoon after four.',
        quickReplies: <String>[
          'Sie können mich auf dem Handy anrufen.',
          'Ich gebe Ihnen meine Nummer und meine Mailadresse.',
        ],
        coachTip: 'Separable verbs split in the Sie-imperative too: anrufen becomes Rufen Sie mich an.',
      ),
      DialogueStep(
        tutorGerman: 'Alles notiert. Wir melden uns sofort, wenn die Tasche hier ankommt.',
        tutorEnglish: 'All noted down. We will get in touch as soon as the bag arrives here.',
        task: 'Thank him and ask him to check again tomorrow morning.',
        keywords: <String>[
          'dank',
          'hilfe',
          'morgen',
          'nachsehen',
          'können sie',
          'schauen',
        ],
        requiredHits: 3,
        minWords: 6,
        modelAnswer: 'Vielen Dank für Ihre Hilfe. Können Sie morgen früh noch einmal nachsehen?',
        modelAnswerEnglish: 'Thank you very much for your help. Could you check again tomorrow morning?',
        quickReplies: <String>[
          'Vielen Dank für Ihre Hilfe!',
          'Können Sie morgen bitte noch einmal schauen?',
        ],
        coachTip: 'A request wrapped in „Können Sie …?“ sounds friendlier than a bare imperative.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-a2-08',
    level: CefrLevel.a2,
    emoji: '💇',
    title: 'Beim Friseur',
    setting: 'A small salon called Haarwerk Nordstern. You walk in without an appointment and hope for a slot today.',
    tutorRole: 'Friseurin (hairdresser)',
    learnerRole: 'Kunde oder Kundin (customer)',
    goal: 'Get an appointment, say exactly what you want and react to the result.',
    usefulPhrases: <String>[
      'Haben Sie heute noch einen Termin frei?',
      'Nur die Spitzen, bitte.',
      'Oben bitte nichts wegnehmen.',
      'Wie lange dauert das ungefähr?',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Hallo, kommen Sie herein! Haben Sie einen Termin bei uns?',
        tutorEnglish: 'Hello, do come in! Do you have an appointment with us?',
        task: 'Say you have no appointment and ask for one today.',
        keywords: <String>[
          'termin',
          'heute',
          'frei',
          'nachmittag',
          'nein',
          'ohne termin',
        ],
        requiredHits: 3,
        minWords: 7,
        modelAnswer: 'Nein, leider nicht. Haben Sie heute Nachmittag vielleicht noch einen Termin frei?',
        modelAnswerEnglish: 'No, unfortunately not. Do you perhaps still have an appointment free this afternoon?',
        quickReplies: <String>[
          'Nein, ich habe keinen Termin.',
          'Haben Sie jetzt gleich Zeit für mich?',
        ],
        coachTip: 'A yes/no question inverts subject and verb: Haben Sie heute noch einen Termin frei?',
      ),
      DialogueStep(
        tutorGerman: 'Da haben Sie Glück: um halb vier ist etwas frei geworden. Was möchten Sie denn machen lassen?',
        tutorEnglish: 'You are in luck: something has come free at half past three. What would you like to have done?',
        task: 'Explain what you want done and how much should come off.',
        keywords: <String>[
          'spitzen',
          'schneiden',
          'zentimeter',
          'möchte',
          'kurz',
          'waschen',
        ],
        requiredHits: 3,
        minWords: 7,
        modelAnswer: 'Ich möchte nur die Spitzen schneiden lassen, bitte höchstens zwei Zentimeter.',
        modelAnswerEnglish: 'I would just like to have the ends cut, at most two centimetres please.',
        quickReplies: <String>[
          'Bitte nur waschen und schneiden.',
          'Ich möchte die Haare kurz schneiden lassen.',
        ],
        coachTip: 'Use „lassen“ when somebody else does the job for you: ich lasse mir die Haare schneiden.',
      ),
      DialogueStep(
        tutorGerman: 'Alles klar. Soll ich oben auch etwas wegnehmen oder alles so lassen?',
        tutorEnglish: 'All right. Should I take something off on top as well, or leave it all as it is?',
        task: 'Answer about the top and say what you definitely do not want.',
        keywords: <String>[
          'oben',
          'lassen',
          'kurz',
          'weil',
          'haare',
          'nicht zu kurz',
        ],
        requiredHits: 3,
        minWords: 7,
        modelAnswer: 'Oben bitte alles so lassen, weil mir kurze Haare überhaupt nicht stehen.',
        modelAnswerEnglish: 'Please leave everything as it is on top, because short hair does not suit me at all.',
        quickReplies: <String>[
          'Oben bitte nichts wegnehmen.',
          'Ja, oben darf es etwas kürzer sein.',
        ],
        coachTip: 'In a „weil“ clause the finite verb lands in last place.',
      ),
      DialogueStep(
        tutorGerman: 'Verstanden. Möchten Sie die Haare vorher gewaschen haben? Das kostet fünf Euro extra.',
        tutorEnglish: 'Understood. Would you like your hair washed first? That costs five euros extra.',
        task: 'Accept or decline the wash and give a short reason.',
        keywords: <String>[
          'gewaschen',
          'nein',
          'danke',
          'schon',
          'heute',
          'ja bitte',
        ],
        requiredHits: 2,
        minWords: 6,
        modelAnswer: 'Nein danke, ich habe sie heute Morgen schon gewaschen, das reicht sicher.',
        modelAnswerEnglish: 'No thank you, I already washed it this morning, that will surely be enough.',
        quickReplies: <String>[
          'Ja, bitte waschen Sie sie.',
          'Nein danke, das ist mir zu teuer.',
        ],
        coachTip: 'The Perfekt participle of waschen is gewaschen, and it closes the sentence.',
      ),
      DialogueStep(
        tutorGerman: 'Gut, setzen Sie sich bitte schon mal hierhin. Wie lange sind Sie eigentlich nicht mehr beim Friseur gewesen?',
        tutorEnglish: 'Good, please take a seat over here already. How long has it actually been since you were at a hairdresser?',
        task: 'Say when you last had a haircut and ask how long today will take.',
        keywords: <String>[
          'monat',
          'wie lange',
          'dauert',
          'winter',
          'jahr',
          'letzte',
        ],
        requiredHits: 3,
        minWords: 8,
        modelAnswer: 'Das war im Winter, also vor etwa acht Monaten. Wie lange dauert es heute?',
        modelAnswerEnglish: 'That was in winter, so about eight months ago. How long does it take today?',
        quickReplies: <String>[
          'Ich war im Sommer das letzte Mal hier.',
          'Wie lange dauert das heute ungefähr?',
        ],
        coachTip: 'A point in the past uses „vor“ plus dative: vor acht Monaten, vor einem Jahr.',
      ),
      DialogueStep(
        tutorGerman: 'Etwa vierzig Minuten. So, fertig! Schauen Sie mal in den Spiegel.',
        tutorEnglish: 'About forty minutes. There, all done! Have a look in the mirror.',
        task: 'React to the result and ask for one small change.',
        keywords: <String>[
          'gefällt',
          'gut',
          'vorne',
          'kürzen',
          'bisschen',
          'danke',
          'perfekt',
        ],
        requiredHits: 2,
        minWords: 6,
        modelAnswer: 'Das gefällt mir sehr gut, aber vorne könnten Sie noch ein bisschen kürzen.',
        modelAnswerEnglish: 'I like it a lot, but at the front you could take off a little more.',
        quickReplies: <String>[
          'Das sieht super aus, vielen Dank!',
          'Können Sie hinten noch etwas kürzen?',
        ],
        coachTip: 'With „gefallen“ the person who likes something stands in the dative: das gefällt mir.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-a2-09',
    level: CefrLevel.a2,
    emoji: '🔧',
    title: 'Die Heizung ist kalt',
    setting: 'A cold November evening. You phone your landlord, Herr Kolbrand, from your flat.',
    tutorRole: 'Vermieter Herr Kolbrand (landlord)',
    learnerRole: 'Mieterin oder Mieter (tenant)',
    goal: 'Describe the problem, say since when, and agree on a repair appointment.',
    usefulPhrases: <String>[
      'Hier ist … aus dem dritten Stock.',
      'Die Heizung funktioniert nicht.',
      'Können Sie jemanden schicken?',
      'Am Donnerstag bin ich zu Hause.',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Kolbrand, guten Abend. Was gibt es denn so spät noch?',
        tutorEnglish: 'Kolbrand speaking, good evening. What is going on so late?',
        task: 'Introduce yourself on the phone and name the problem.',
        keywords: <String>[
          'heizung',
          'funktioniert',
          'hier ist',
          'kaputt',
          'kalt',
          'wohnung',
        ],
        requiredHits: 2,
        minWords: 7,
        modelAnswer: 'Guten Abend, hier ist Frau Adler aus der dritten Etage. Meine Heizung funktioniert nicht.',
        modelAnswerEnglish: 'Good evening, this is Ms Adler from the third floor. My heating is not working.',
        quickReplies: <String>[
          'Guten Abend, hier ist Ihr Mieter aus dem zweiten Stock.',
          'Entschuldigung, meine Heizung ist kaputt.',
        ],
        coachTip: 'On the phone Germans name themselves first with „Hier ist …“ before anything else.',
      ),
      DialogueStep(
        tutorGerman: 'Oh je. Und seit wann ist das so?',
        tutorEnglish: 'Oh dear. And since when has that been the case?',
        task: 'Say since when it has been cold and how cold it is.',
        keywords: <String>[
          'seit',
          'kalt',
          'grad',
          'wohnung',
          'vorgestern',
          'gestern',
        ],
        requiredHits: 3,
        minWords: 7,
        modelAnswer: 'Seit vorgestern bleibt sie kalt, und in der Wohnung sind nur sechzehn Grad.',
        modelAnswerEnglish: 'It has stayed cold since the day before yesterday, and it is only sixteen degrees in the flat.',
        quickReplies: <String>[
          'Seit gestern Abend ist es kalt.',
          'Das Problem habe ich schon seit drei Tagen.',
        ],
        coachTip: 'German keeps the present tense after „seit“: seit zwei Tagen ist es kalt.',
      ),
      DialogueStep(
        tutorGerman: 'Haben Sie denn schon am Thermostat gedreht? Manchmal ist nur Luft im System.',
        tutorEnglish: 'Have you already turned the thermostat? Sometimes there is just air in the system.',
        task: 'Say what you have already tried, using the Perfekt.',
        keywords: <String>[
          'thermostat',
          'aufgedreht',
          'entlüftet',
          'heizung',
          'probiert',
          'versucht',
        ],
        requiredHits: 2,
        minWords: 7,
        modelAnswer: 'Ja, ich habe den Thermostat aufgedreht und die Heizung auch schon entlüftet.',
        modelAnswerEnglish: 'Yes, I turned the thermostat up and I have already bled the radiator too.',
        quickReplies: <String>[
          'Ja, ich habe alles schon probiert.',
          'Ich habe die Heizung gestern entlüftet.',
        ],
        coachTip: 'Separable verbs build the Perfekt with ge- in the middle: aufdrehen becomes aufgedreht.',
      ),
      DialogueStep(
        tutorGerman: 'Verstehe. Dann muss der Installateur kommen. Der hat aber erst nächste Woche Zeit.',
        tutorEnglish: 'I see. Then the plumber has to come. But he only has time next week.',
        task: 'Say that this is too late for you and explain why.',
        keywords: <String>[
          'zu spät',
          'weil',
          'kalt',
          'nachts',
          'leider',
          'früher',
          'geht nicht',
        ],
        requiredHits: 2,
        minWords: 7,
        modelAnswer: 'Das ist mir leider zu spät, weil die Wohnung nachts richtig kalt wird.',
        modelAnswerEnglish: 'That is unfortunately too late for me, because the flat gets really cold at night.',
        quickReplies: <String>[
          'Nächste Woche ist mir leider zu spät.',
          'Geht das nicht früher? In der Wohnung ist es sehr kalt.',
        ],
        coachTip: 'Put the reason in a „weil“ clause and the verb slips to the end.',
      ),
      DialogueStep(
        tutorGerman: 'Gut, ich rufe ihn gleich morgen früh an und frage nach einem Notdienst. Wann sind Sie zu Hause?',
        tutorEnglish: 'All right, I will call him first thing tomorrow and ask about an emergency service. When are you at home?',
        task: 'Offer two times when you are at home.',
        keywords: <String>[
          'zu hause',
          'morgen',
          'donnerstag',
          'ab drei',
          'nachmittag',
          'freitag',
        ],
        requiredHits: 2,
        minWords: 7,
        modelAnswer: 'Morgen bin ich ab drei zu Hause, am Donnerstag den ganzen Tag.',
        modelAnswerEnglish: 'Tomorrow I am at home from three, on Thursday all day.',
        quickReplies: <String>[
          'Am Mittwoch bin ich den ganzen Tag da.',
          'Ab siebzehn Uhr bin ich immer zu Hause.',
        ],
        coachTip: 'Days of the week take „am“: am Donnerstag, while morgen and heute stand alone.',
      ),
      DialogueStep(
        tutorGerman: 'Alles klar, ich gebe ihm Ihre Zeiten durch. Ich melde mich, sobald ich einen Termin habe.',
        tutorEnglish: 'All right, I will pass your times on to him. I will get in touch as soon as I have an appointment.',
        task: 'Thank him and ask for confirmation by text message.',
        keywords: <String>[
          'dank',
          'sms',
          'schicken',
          'termin',
          'nachricht',
          'schreiben',
        ],
        requiredHits: 2,
        minWords: 6,
        modelAnswer: 'Vielen Dank. Können Sie mir den Termin bitte kurz per SMS schicken?',
        modelAnswerEnglish: 'Thank you very much. Could you send me the appointment briefly by text message?',
        quickReplies: <String>[
          'Danke, schicken Sie mir bitte eine Nachricht.',
          'Vielen Dank für Ihre Hilfe.',
        ],
        coachTip: 'Keeping „bitte“ in the middle of the question is what keeps the request polite.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-a2-10',
    level: CefrLevel.a2,
    emoji: '🏊',
    title: 'Der Schwimmkurs',
    setting: 'The course desk of the Blaue Welle indoor pool in Hartenberg, on a quiet Thursday afternoon.',
    tutorRole: 'Frau Nowak, Kursbüro (course office)',
    learnerRole: 'Elternteil (parent of a young child)',
    goal: 'Register your child for a swimming course, choose a time and sort out the details.',
    usefulPhrases: <String>[
      'Ich möchte mein Kind anmelden.',
      'Wann findet der Kurs statt?',
      'Was kostet der Kurs?',
      'Was müssen wir mitbringen?',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Guten Tag, willkommen im Kursbüro. Was kann ich für Sie tun?',
        tutorEnglish: 'Hello, welcome to the course office. What can I do for you?',
        task: 'Say why you are here and who you want to register.',
        keywords: <String>[
          'möchte',
          'anmelden',
          'schwimmkurs',
          'tochter',
          'sieben jahre',
          'meinen sohn',
          'kurs',
        ],
        requiredHits: 3,
        minWords: 8,
        modelAnswer: 'Guten Tag, ich möchte meine Tochter für einen Schwimmkurs anmelden, sie ist sieben Jahre alt.',
        modelAnswerEnglish: 'Hello, I would like to register my daughter for a swimming course, she is seven years old.',
        quickReplies: <String>[
          'Ich möchte meinen Sohn für den Schwimmkurs anmelden.',
          'Guten Tag, ich suche einen Kurs für Anfänger.',
        ],
        coachTip: 'After the modal möchte the second verb stays whole at the end, so the prefix does not split: „ich möchte sie anmelden“.',
      ),
      DialogueStep(
        tutorGerman: 'Sehr gern. Sagen Sie mir bitte, wie gut Ihr Kind schon schwimmen kann und ob es schon einmal in einem Kurs war.',
        tutorEnglish: 'Gladly. Please tell me how well your child can already swim and whether it has been in a course before.',
        task: 'Describe how much your child can already swim, using the Perfekt for anything finished.',
        keywords: <String>[
          'gemacht',
          'letztes jahr',
          'kann noch nicht',
          'anfänger',
          'schwimmen',
          'gelernt',
          'hat',
        ],
        requiredHits: 3,
        minWords: 8,
        modelAnswer: 'Sie hat letztes Jahr einen Anfängerkurs gemacht, aber sie kann noch nicht richtig schwimmen.',
        modelAnswerEnglish: 'She did a beginners course last year, but she still cannot really swim.',
        quickReplies: <String>[
          'Sie kann noch gar nicht schwimmen.',
          'Er hat schon einen Kurs gemacht, aber das ist lange her.',
        ],
        coachTip: 'Finished experiences take the Perfekt with haben plus a ge-form: „sie hat einen Kurs gemacht“.',
      ),
      DialogueStep(
        tutorGerman: 'Alles klar, ich notiere das. Wir haben zwei Anfängergruppen: dienstags um sechzehn Uhr und samstags um zehn Uhr, jeweils zehn Wochen lang.',
        tutorEnglish: 'All right, I am noting that down. We have two beginner groups: Tuesdays at four and Saturdays at ten, ten weeks each.',
        task: 'Choose one of the two times and give a reason with weil.',
        keywords: <String>[
          'samstag',
          'dienstag',
          'passt',
          'weil',
          'arbeiten',
          'besser',
          'muss',
        ],
        requiredHits: 3,
        minWords: 7,
        modelAnswer: 'Samstags passt uns besser, weil ich dienstags bis sechs Uhr arbeiten muss.',
        modelAnswerEnglish: 'Saturdays suit us better, because on Tuesdays I have to work until six.',
        quickReplies: <String>[
          'Der Kurs am Dienstag passt uns besser.',
          'Wir nehmen den Samstag, weil ich da frei habe.',
        ],
        coachTip: 'weil sends the conjugated verb to the end, so muss comes last in „weil ich arbeiten muss“.',
      ),
      DialogueStep(
        tutorGerman: 'Gut, ich trage Sie für die Gruppe ein. Der Kurs kostet achtzig Euro, und eine Begleitperson zahlt den normalen Eintritt. Haben Sie noch Fragen?',
        tutorEnglish: 'Good, I will put you down for the group. The course costs eighty euros, and an accompanying adult pays the normal entrance fee. Do you have any questions?',
        task: 'Ask two questions about the course, for example about paying and about what to bring.',
        keywords: <String>[
          'bezahlen',
          'karte',
          'mitbringen',
          'müssen wir',
          'handtuch',
          'brauchen',
          'kostet',
        ],
        requiredHits: 3,
        minWords: 8,
        modelAnswer: 'Kann ich mit Karte bezahlen? Und was müssen wir mitbringen, außer Badesachen und Handtuch?',
        modelAnswerEnglish: 'Can I pay by card? And what do we have to bring, apart from swimming things and a towel?',
        quickReplies: <String>[
          'Was kostet der Kurs für zehn Wochen?',
          'Müssen wir eine Badekappe mitbringen?',
        ],
        coachTip: 'A yes-no question starts with the verb and needs no question word at all: „Kann ich mit Karte bezahlen?“',
      ),
      DialogueStep(
        tutorGerman: 'Das kläre ich gleich für Sie. Jetzt brauche ich noch die Daten Ihres Kindes, also Name und Geburtsdatum, bitte.',
        tutorEnglish: 'I will sort that out for you in a moment. Now I still need your child\'s details, so name and date of birth, please.',
        task: 'Give your child\'s name and date of birth.',
        keywords: <String>[
          'heißt',
          'geboren',
          'tochter',
          'märz',
          'sie ist am',
          'name',
          'sohn',
        ],
        requiredHits: 3,
        minWords: 7,
        modelAnswer: 'Meine Tochter heißt Lena Brunner und sie ist am zwölften März zweitausendachtzehn geboren.',
        modelAnswerEnglish: 'My daughter is called Lena Brunner and she was born on the twelfth of March two thousand eighteen.',
        quickReplies: <String>[
          'Mein Sohn heißt Tobias Brunner.',
          'Sie ist im Mai zweitausendneunzehn geboren.',
        ],
        coachTip: 'Dates take am plus an ordinal ending in -en, so a birthday is „am zwölften März“.',
      ),
      DialogueStep(
        tutorGerman: 'Danke, alles eingetragen. Der erste Termin ist am siebten Oktober um sechzehn Uhr. Wenn Ihr Kind einmal nicht kommen kann, geben Sie uns bitte vorher Bescheid.',
        tutorEnglish: 'Thank you, everything is entered. The first session is on the seventh of October at four. If your child cannot come one week, please let us know beforehand.',
        task: 'Thank her and say what you will do if your child cannot come one week.',
        keywords: <String>[
          'wenn',
          'krank',
          'rufe ich',
          'bescheid',
          'vielen dank',
          'sage',
          'absagen',
        ],
        requiredHits: 3,
        minWords: 7,
        modelAnswer: 'Vielen Dank. Wenn Lena krank ist, rufe ich am Morgen an und sage Bescheid.',
        modelAnswerEnglish: 'Thank you very much. If Lena is ill, I will call in the morning and let you know.',
        quickReplies: <String>[
          'Vielen Dank für Ihre Hilfe.',
          'Wenn wir nicht kommen können, schreibe ich eine E-Mail.',
        ],
        coachTip: 'wenn also sends its verb to the end, and the main clause then begins with its own verb: „Wenn sie krank ist, rufe ich an.“',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-a2-11',
    level: CefrLevel.a2,
    emoji: '🤒',
    title: 'Die Krankmeldung',
    setting: 'Ten past seven in the morning. You phone the office of Wegmüller Logistik before your shift starts.',
    tutorRole: 'Herr Grabner, Teamleiter (team leader)',
    learnerRole: 'Angestellte oder Angestellter (employee)',
    goal: 'Report sick, explain the situation and hand over what is urgent today.',
    usefulPhrases: <String>[
      'Hier ist … am Apparat.',
      'Ich bin leider krank.',
      'Ich kann heute nicht kommen.',
      'Ich melde mich morgen wieder.',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Wegmüller Logistik, Grabner am Apparat. Guten Morgen!',
        tutorEnglish: 'Wegmüller Logistics, Grabner speaking. Good morning!',
        task: 'Greet him, say who is calling and report that you are sick.',
        keywords: <String>[
          'guten morgen',
          'hier ist',
          'krank',
          'nicht kommen',
          'leider',
          'mein name',
          'krankmelden',
        ],
        requiredHits: 3,
        minWords: 8,
        modelAnswer: 'Guten Morgen, Herr Grabner, hier ist Nina Kolb. Ich bin krank und kann heute leider nicht kommen.',
        modelAnswerEnglish: 'Good morning, Mr Grabner, this is Nina Kolb. I am ill and unfortunately cannot come in today.',
        quickReplies: <String>[
          'Hier spricht Nina Kolb, ich muss mich leider krankmelden.',
          'Guten Morgen, mir geht es heute gar nicht gut.',
        ],
        coachTip: 'On the phone you introduce yourself with „hier ist“ plus your name, not with a form of sein.',
      ),
      DialogueStep(
        tutorGerman: 'Oh, das klingt nicht gut. Was fehlt Ihnen denn, und waren Sie schon beim Arzt?',
        tutorEnglish: 'Oh, that does not sound good. What is wrong with you, and have you been to the doctor yet?',
        task: 'Say what is wrong and whether you have seen a doctor.',
        keywords: <String>[
          'fieber',
          'schmerzen',
          'ich war',
          'beim arzt',
          'habe',
          'gehe',
          'erkältet',
        ],
        requiredHits: 3,
        minWords: 8,
        modelAnswer: 'Ich habe Fieber und Halsschmerzen. Ich war noch nicht beim Arzt, aber ich gehe heute Mittag hin.',
        modelAnswerEnglish: 'I have a fever and a sore throat. I have not been to the doctor yet, but I am going at midday.',
        quickReplies: <String>[
          'Ich bin stark erkältet und habe Kopfschmerzen.',
          'Ich war heute Morgen schon beim Arzt.',
        ],
        coachTip: 'For states in the past, spoken German prefers the Präteritum of sein: „ich war beim Arzt“.',
      ),
      DialogueStep(
        tutorGerman: 'Verstehe. Sagen Sie mir bitte noch, wie lange Sie ungefähr ausfallen. Ab dem dritten Tag brauchen wir eine Krankschreibung.',
        tutorEnglish: 'I see. Please also tell me roughly how long you will be off. From the third day we need a sick note.',
        task: 'Estimate how long you will be away and say what you will do about the certificate.',
        keywords: <String>[
          'glaube',
          'drei tage',
          'krankschreibung',
          'schicke',
          'brauche',
          'attest',
          'zwei tage',
        ],
        requiredHits: 3,
        minWords: 8,
        modelAnswer: 'Ich glaube, ich brauche zwei oder drei Tage. Die Krankschreibung schicke ich Ihnen per Post.',
        modelAnswerEnglish: 'I think I need two or three days. I will send you the sick note by post.',
        quickReplies: <String>[
          'Wahrscheinlich bin ich bis Freitag zu Hause.',
          'Die Krankschreibung bringe ich morgen vorbei.',
        ],
        coachTip: 'The person who receives something stands in the dative, so it is „ich schicke Ihnen die Krankschreibung“.',
      ),
      DialogueStep(
        tutorGerman: 'Danke, ich notiere das. Heute kommt die Lieferung aus Rosenheim. Was ist dringend, und wer kann das übernehmen?',
        tutorEnglish: 'Thanks, I am noting that down. The delivery from Rosenheim arrives today. What is urgent, and who can take it over?',
        task: 'Say what is urgent today and name a colleague who can take over.',
        keywords: <String>[
          'liste',
          'schreibtisch',
          'übernehmen',
          'kann',
          'lieferung',
          'frau',
          'kollege',
        ],
        requiredHits: 3,
        minWords: 8,
        modelAnswer: 'Die Liste für Rosenheim liegt auf meinem Schreibtisch. Frau Bendig kann die Lieferung bestimmt übernehmen.',
        modelAnswerEnglish: 'The list for Rosenheim is on my desk. Ms Bendig can certainly take over the delivery.',
        quickReplies: <String>[
          'Der Ordner mit den Lieferscheinen liegt im Regal.',
          'Herr Tolksdorf kennt die Route und kann einspringen.',
        ],
        coachTip: 'können sends its infinitive to the end, and separable übernehmen keeps its prefix attached there: „sie kann das übernehmen“.',
      ),
      DialogueStep(
        tutorGerman: 'Gut, das regele ich. Soll ich das Team informieren, oder schreiben Sie selbst kurz in die Gruppe?',
        tutorEnglish: 'Good, I will sort that out. Shall I inform the team, or will you write a short message in the group yourself?',
        task: 'Choose one of the two options and say what happens, using a dass clause.',
        keywords: <String>[
          'dass',
          'team',
          'melde mich',
          'morgen',
          'bitte',
          'schreibe',
          'nachricht',
        ],
        requiredHits: 3,
        minWords: 8,
        modelAnswer: 'Schreiben Sie bitte dem Team, dass ich krank bin. Ich melde mich morgen früh wieder.',
        modelAnswerEnglish: 'Please write to the team that I am ill. I will get in touch again tomorrow morning.',
        quickReplies: <String>[
          'Sagen Sie dem Team bitte, dass ich heute fehle.',
          'Ich schreibe selbst kurz in die Gruppe, dass ich krank bin.',
        ],
        coachTip: 'dass reports a fact and pushes the verb to the very end: „dass ich krank bin“.',
      ),
      DialogueStep(
        tutorGerman: 'In Ordnung. Kurieren Sie sich richtig aus, wir schaffen das hier schon. Gute Besserung!',
        tutorEnglish: 'All right. Get properly better, we will manage here. Get well soon!',
        task: 'Thank him and end the call politely.',
        keywords: <String>[
          'vielen dank',
          'verständnis',
          'wiederhören',
          'melde mich',
          'mittwoch',
          'tschüss',
          'danke',
        ],
        requiredHits: 3,
        minWords: 7,
        modelAnswer: 'Vielen Dank für Ihr Verständnis. Ich melde mich spätestens am Mittwoch. Auf Wiederhören, Herr Grabner.',
        modelAnswerEnglish: 'Thank you very much for your understanding. I will be in touch by Wednesday at the latest. Goodbye, Mr Grabner.',
        quickReplies: <String>[
          'Danke schön, ich melde mich morgen wieder.',
          'Vielen Dank, auf Wiederhören.',
        ],
        coachTip: 'danke für takes the accusative, so you thank someone „für Ihr Verständnis“.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-a2-12',
    level: CefrLevel.a2,
    emoji: '🚲',
    title: 'Das gebrauchte Fahrrad',
    setting: 'A courtyard in Kleinmoos. You answered a small ad for a used city bike and came to look at it.',
    tutorRole: 'Herr Semmler, Privatverkäufer (private seller)',
    learnerRole: 'Käuferin oder Käufer (buyer)',
    goal: 'Look the bike over, ask questions and agree on a fair price.',
    usefulPhrases: <String>[
      'Ich habe die Anzeige gesehen.',
      'Wie alt ist das Rad?',
      'Das ist mir leider zu teuer.',
      'Ich biete Ihnen …',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Hallo, Sie haben wegen des Fahrrads geschrieben. Da drüben steht es. Schauen Sie es sich in Ruhe an.',
        tutorEnglish: 'Hello, you wrote about the bike. There it is over there. Take your time and have a look.',
        task: 'Greet the seller, say why you have come and ask a first question about the bike.',
        keywords: <String>[
          'anzeige',
          'gesehen',
          'wie alt',
          'fahrrad',
          'guten tag',
          'rad',
          'interessiert',
        ],
        requiredHits: 3,
        minWords: 7,
        modelAnswer: 'Guten Tag, ich habe die Anzeige gesehen. Wie alt ist das Fahrrad denn?',
        modelAnswerEnglish: 'Hello, I saw the advert. How old is the bike, then?',
        quickReplies: <String>[
          'Hallo, ich komme wegen des Fahrrads.',
          'Guten Tag, ist das Rad noch zu haben?',
        ],
        coachTip: 'The Perfekt of sehen is irregular with gesehen, and the participle closes the sentence: „ich habe die Anzeige gesehen“.',
      ),
      DialogueStep(
        tutorGerman: 'Es ist fünf Jahre alt, ich habe es damals neu gekauft. Die Reifen sind neu und die Gangschaltung läuft sauber. Wofür brauchen Sie das Rad denn?',
        tutorEnglish: 'It is five years old, I bought it new back then. The tyres are new and the gears run smoothly. What do you need the bike for?',
        task: 'Say what you need the bike for and mention something you noticed on it.',
        keywords: <String>[
          'zur arbeit',
          'jeden tag',
          'bremsen',
          'fahre',
          'hinten',
          'brauche',
          'kaputt',
        ],
        requiredHits: 3,
        minWords: 8,
        modelAnswer: 'Ich fahre damit jeden Tag zur Arbeit. Die Bremsen hinten quietschen ein bisschen, oder?',
        modelAnswerEnglish: 'I would ride it to work every day. The rear brakes squeak a little, don\'t they?',
        quickReplies: <String>[
          'Ich brauche ein Rad für den Weg zur Uni.',
          'Der Sattel ist ziemlich abgenutzt, oder?',
        ],
        coachTip: 'zur is short for zu der, and zu always takes the dative, so the phrase is „zur Arbeit“ and never zu die Arbeit.',
      ),
      DialogueStep(
        tutorGerman: 'Da haben Sie recht, ganz neu ist es nicht mehr. Die Bremsbeläge müsste man bald wechseln, das kostet in der Werkstatt vielleicht zwanzig Euro. Ich möchte hundertsechzig Euro für das Rad.',
        tutorEnglish: 'You are right, it is not brand new any more. The brake pads should be replaced soon, that costs maybe twenty euros at a shop. I want a hundred and sixty euros for the bike.',
        task: 'Offer less than he is asking and give a reason with weil.',
        keywords: <String>[
          'zu viel',
          'weil',
          'bremsen',
          'biete',
          'reparieren',
          'hundert',
          'zu teuer',
        ],
        requiredHits: 3,
        minWords: 8,
        modelAnswer: 'Hundertsechzig ist mir zu viel, weil ich noch die Bremsen reparieren muss. Ich biete hundertdreißig.',
        modelAnswerEnglish: 'A hundred and sixty is too much for me, because I still have to repair the brakes. I offer a hundred and thirty.',
        quickReplies: <String>[
          'Das ist mir leider zu teuer.',
          'Würden Sie es für hundertvierzig Euro verkaufen?',
        ],
        coachTip: 'In a weil clause the modal muss lands right at the end, after the infinitive: „weil ich die Bremsen reparieren muss“.',
      ),
      DialogueStep(
        tutorGerman: 'Hmm, so weit runter möchte ich nicht gehen. Bei hundertfünfzig könnten wir uns einigen, und das gute Schloss lege ich dazu.',
        tutorEnglish: 'Hmm, I do not want to go down that far. At a hundred and fifty we could come to an agreement, and I will throw in the good lock.',
        task: 'React to his counter-offer and either agree or ask for one more thing.',
        keywords: <String>[
          'einverstanden',
          'schloss',
          'können sie',
          'luftpumpe',
          'bitte',
          'dazu',
          'in ordnung',
        ],
        requiredHits: 3,
        minWords: 7,
        modelAnswer: 'Einverstanden, hundertfünfzig mit Schloss. Können Sie mir bitte auch die Luftpumpe dazugeben?',
        modelAnswerEnglish: 'Agreed, a hundred and fifty with the lock. Could you also throw in the pump, please?',
        quickReplies: <String>[
          'In Ordnung, dann nehme ich es für hundertfünfzig.',
          'Geht auch hundertvierzig, wenn ich sofort bar zahle?',
        ],
        coachTip: 'A polite request is a können question with bitte tucked into the middle: „Können Sie mir bitte die Pumpe geben?“',
      ),
      DialogueStep(
        tutorGerman: 'Das lässt sich machen. Fahren Sie doch erst einmal eine kleine Runde, dann wissen Sie mehr.',
        tutorEnglish: 'That can be arranged. Why not ride a short lap first, then you will know more.',
        task: 'Accept the test ride and say what you want to try out.',
        keywords: <String>[
          'gern',
          'fahre',
          'probiere',
          'gänge',
          'bremsen',
          'runde',
          'ausprobieren',
        ],
        requiredHits: 3,
        minWords: 8,
        modelAnswer: 'Ja, gern. Ich fahre einmal um den Block und probiere die Gänge und die Bremsen aus.',
        modelAnswerEnglish: 'Yes, gladly. I will ride around the block and try out the gears and the brakes.',
        quickReplies: <String>[
          'Ja, gern, ich fahre kurz die Straße hoch.',
          'Darf ich die Gangschaltung ausprobieren?',
        ],
        coachTip: 'Separable ausprobieren splits in the present tense, so the prefix aus waits at the very end: „ich probiere die Gänge aus“.',
      ),
      DialogueStep(
        tutorGerman: 'Und, wie war die Runde? Wenn alles passt, hole ich den Kaufvertrag und die alte Rechnung aus dem Haus.',
        tutorEnglish: 'So, how was the ride? If everything is fine, I will fetch the sales contract and the old receipt from the house.',
        task: 'Say how the ride was and settle payment and the paperwork.',
        keywords: <String>[
          'bar',
          'geld',
          'vertrag',
          'unterschreiben',
          'gut',
          'überweisen',
          'nehme',
        ],
        requiredHits: 3,
        minWords: 8,
        modelAnswer: 'Das Rad fährt gut. Ich habe das Geld bar dabei, und den Vertrag unterschreiben wir gleich.',
        modelAnswerEnglish: 'The bike rides well. I have the money in cash with me, and we can sign the contract right away.',
        quickReplies: <String>[
          'Das Rad fährt sehr gut, ich nehme es.',
          'Kann ich Ihnen das Geld auch überweisen?',
        ],
        coachTip: 'Manner adverbs like bar stand after the object, so it is „ich zahle das Rad bar“.',
      ),
    ],
  ),
];
