import 'conversation.dart';
import 'models.dart';

/// C2 role-plays, second batch. Original text written for this
/// app.
const List<ConversationScenario> conversationC2MoreScenarios = <ConversationScenario>[
  ConversationScenario(
    id: 'cv-c2-03',
    level: CefrLevel.c2,
    emoji: '⚖️',
    title: 'Die Zeugenaussage',
    setting: 'A lawyer records your statement about an evening at a neighbouring building; every word goes into the file.',
    tutorRole: 'Rechtsanwältin',
    learnerRole: 'Zeugin/Zeuge',
    goal: 'Say only what you actually know, and correct the record without hostility.',
    usefulPhrases: <String>[
      'Das entzieht sich meiner Kenntnis.',
      'Ich bitte, das so zu protokollieren.',
      'Ich habe präzisiert, nicht verändert.',
      'Darüber könnte ich nur mutmaßen.',
      'So möchte ich es nicht stehen lassen.',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Ich danke Ihnen für Ihr Erscheinen. Schildern Sie bitte zunächst, was Sie am fraglichen Abend beobachtet haben.',
        tutorEnglish: 'Thank you for coming. Please describe first what you observed on the evening in question.',
        task: 'Give a precise account and mark clearly where your own perception ends.',
        keywords: <String>[
          'wahrgenommen',
          'vermutung',
          'meiner kenntnis',
          'beobachtet',
          'ausschließlich',
          'selbst',
        ],
        requiredHits: 3,
        minWords: 24,
        modelAnswer: 'Ich schildere ausschließlich, was ich selbst wahrgenommen habe: Gegen halb neun sah ich zwei Personen am Seiteneingang. Ob sie zum Gebäude gehörten, entzieht sich meiner Kenntnis. Alles Weitere wäre eine Vermutung, und die möchte ich vom Beobachteten ausdrücklich getrennt wissen.',
        modelAnswerEnglish: 'I will describe only what I perceived myself: at about half past eight I saw two people at the side entrance. Whether they belonged to the building is beyond my knowledge. Anything further would be conjecture, and I want that kept expressly separate from what I observed.',
        quickReplies: <String>[
          'Ich beschränke mich auf das, was ich selbst gesehen habe.',
          'Alles Übrige wäre eine Vermutung und gehört nicht ins Protokoll.',
        ],
        coachTip: 'Marking the edge of your own perception with „was ich selbst wahrgenommen habe“ is what makes a statement precise rather than merely confident.',
      ),
      DialogueStep(
        tutorGerman: 'Im Entwurf des Protokolls steht, Sie hätten den Mann erkannt. Können wir das so stehen lassen?',
        tutorEnglish: 'The draft record says you recognised the man. Can we leave it like that?',
        task: 'Correct the wording in the record without questioning the recorder\'s good faith.',
        keywords: <String>[
          'wiedererkannt',
          'identifiziert',
          'formulierung',
          'unterschied',
          'protokoll',
          'bitte um',
        ],
        requiredHits: 3,
        minWords: 26,
        modelAnswer: 'So kann es nicht stehen bleiben, ohne dass ich Ihnen eine Absicht unterstellen möchte. Ich habe die Person wiedererkannt, nicht identifiziert; das ist ein Unterschied. Ich bitte um die Formulierung: Der Zeuge meint, die Person schon einmal gesehen zu haben.',
        modelAnswerEnglish: 'It cannot stand like that, without my imputing any intention to you. I recognised the person again, I did not identify them; that is a difference. I ask for the wording: the witness believes he has seen the person before.',
        quickReplies: <String>[
          'So möchte ich das nicht protokolliert sehen.',
          'Bitte halten Sie fest: Ich habe die Person wiedererkannt, nicht identifiziert.',
        ],
        coachTip: 'The contrast pair „wiedererkannt, nicht identifiziert“ corrects the record without accusing anyone of bad faith.',
      ),
      DialogueStep(
        tutorGerman: 'Können Sie ausschließen, dass sich der Vorgang ganz anders zugetragen hat?',
        tutorEnglish: 'Can you rule out that the incident happened quite differently?',
        task: 'Refuse to go beyond your knowledge without sounding evasive.',
        keywords: <String>[
          'ausschließen',
          'zeitraum',
          'wahrnehmung',
          'zugegen',
          'aufgefallen',
          'erinnern',
        ],
        requiredHits: 3,
        minWords: 26,
        modelAnswer: 'Ausschließen kann ich es nicht, denn ich war nicht durchgehend zugegen. Was ich sagen kann, ist dies: In dem Zeitraum, den ich überblicke, ist mir nichts Abweichendes aufgefallen. Weiter reicht meine Wahrnehmung schlicht nicht, und ich möchte sie auch nicht überdehnen.',
        modelAnswerEnglish: 'I cannot rule it out, since I was not present throughout. What I can say is this: in the period I can survey, nothing divergent struck me. My perception simply reaches no further, and I do not wish to overstretch it.',
        quickReplies: <String>[
          'Ausschließen kann ich nichts, was ich nicht beobachtet habe.',
          'In dem Zeitraum, den ich überblicke, ist mir nichts aufgefallen.',
        ],
        coachTip: 'Answering an impossible question by naming its scope, as in „in dem Zeitraum, den ich überblicke“, avoids both bluffing and evasion.',
      ),
      DialogueStep(
        tutorGerman: 'Sie sprachen vorhin von einem lauten Streit. Was verstehen Sie unter laut?',
        tutorEnglish: 'You spoke earlier of a loud quarrel. What do you mean by loud?',
        task: 'Define your own term operationally and stand by the distinction.',
        keywords: <String>[
          'stimmen',
          'geschlossenem fenster',
          'wortwechsel',
          'unterscheidung',
          'behauptet',
          'lautstärke',
        ],
        requiredHits: 3,
        minWords: 26,
        modelAnswer: 'Unter laut verstehe ich, dass ich die Stimmen bei geschlossenem Fenster hören konnte, ohne einzelne Wörter zu verstehen. Ob es ein Streit war, habe ich nicht behauptet; ich sprach von einem erregten Wortwechsel. Diese Unterscheidung ist mir wichtig, weil sie über die Bewertung mitentscheidet.',
        modelAnswerEnglish: 'By loud I mean that I could hear the voices with the window shut, without making out individual words. Whether it was a quarrel I have not claimed; I spoke of a heated exchange. This distinction matters to me because it partly determines the assessment.',
        quickReplies: <String>[
          'Von einem Streit habe ich nicht gesprochen, sondern von einem Wortwechsel.',
          'Laut heißt für mich: durch das geschlossene Fenster hörbar.',
        ],
        coachTip: 'Defining your own word before someone else defines it for you is a core C2 move in any formal setting.',
      ),
      DialogueStep(
        tutorGerman: 'Die Gegenseite wird Ihnen vorhalten, Sie hätten Ihre Aussage im Laufe des Vormittags verändert.',
        tutorEnglish: 'The other side will put it to you that you changed your statement over the course of the morning.',
        task: 'Reject the charge of inconsistency while conceding that you corrected something.',
        keywords: <String>[
          'präzisiert',
          'widerspruch',
          'korrektur',
          'protokoll',
          'verändert',
          'ungenau',
        ],
        requiredHits: 3,
        minWords: 26,
        modelAnswer: 'Verändert habe ich nichts; präzisiert habe ich durchaus. Genau dafür ist ein Protokoll da. Wenn eine Formulierung meine Wahrnehmung nur ungenau wiedergab, war die Korrektur geboten. Einen Widerspruch vermag ich darin nicht zu erkennen, und ich bleibe bei allem, was ich zu Protokoll gegeben habe.',
        modelAnswerEnglish: 'I have changed nothing; I have certainly made things more precise. That is exactly what a record is for. If a formulation rendered my perception only imprecisely, the correction was called for. I am unable to see a contradiction in that, and I stand by everything I have put on record.',
        quickReplies: <String>[
          'Ich habe präzisiert, nicht verändert.',
          'Einen Widerspruch kann ich darin beim besten Willen nicht erkennen.',
        ],
        coachTip: 'Fronting the disputed verb in „Verändert habe ich nichts“ throws the whole weight of the sentence onto the denial.',
      ),
      DialogueStep(
        tutorGerman: 'Wir kommen zum Schluss. Möchten Sie dem Protokoll noch etwas hinzufügen?',
        tutorEnglish: 'We are coming to the end. Would you like to add anything to the record?',
        task: 'Close by attaching one qualification that applies to your whole statement.',
        keywords: <String>[
          'anmerkung',
          'schätzungen',
          'uhrzeiten',
          'festzuhalten',
          'protokoll',
          'angaben',
        ],
        requiredHits: 3,
        minWords: 24,
        modelAnswer: 'Nur eine Anmerkung, die für das Ganze gilt: Meine Angaben zu Uhrzeiten beruhen auf Schätzungen, nicht auf einem Blick auf die Uhr. Ich bitte, das im Protokoll so festzuhalten. Im Übrigen bleibt es bei dem, was ich ausgesagt habe.',
        modelAnswerEnglish: 'Only one remark, which applies to the whole: my statements about times rest on estimates, not on a look at the clock. I ask for that to be recorded. For the rest, what I have testified stands.',
        quickReplies: <String>[
          'Meine Zeitangaben beruhen auf Schätzungen, nicht auf einem Blick auf die Uhr.',
          'Bitte nehmen Sie diese Anmerkung noch ins Protokoll auf.',
        ],
        coachTip: 'A final qualification introduced with „nur eine Anmerkung, die für das Ganze gilt“ retroactively attaches to everything said before it.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-c2-04',
    level: CefrLevel.c2,
    emoji: '🤝',
    title: 'Die Kompromissformel',
    setting: 'Two district delegations draft a joint text on summer water use in the Weiherbach valley.',
    tutorRole: 'Delegationsleiterin',
    learnerRole: 'Verhandlungsführerin/Verhandlungsführer',
    goal: 'Reach a wording both sides can present at home as their own.',
    usefulPhrases: <String>[
      'Das ist zur Kenntnis genommen.',
      'Mir wäre es recht, wenn …',
      'Vielleicht hilft ein anderer Zuschnitt.',
      'Darauf könnten wir uns verständigen.',
      'Ich möchte Ihnen nichts zumuten.',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Guten Morgen. Bevor wir in die Sache gehen: Eine Formulierung, die uns die Verantwortung zuschreibt, kann unsere Seite nicht mittragen.',
        tutorEnglish: 'Good morning. Before we get to the substance: our side cannot support any wording that attributes responsibility to us.',
        task: 'Acknowledge their red line without accepting their framing.',
        keywords: <String>[
          'zur kenntnis',
          'festhalten',
          'verantwortung',
          'zuschreibung',
          'beschreibung',
          'zugleich',
        ],
        requiredHits: 3,
        minWords: 24,
        modelAnswer: 'Guten Morgen. Dass Sie diese Grenze deutlich machen, ist hilfreich; sie ist zur Kenntnis genommen. Zugleich möchte ich festhalten, dass wir von Verantwortung bisher gar nicht gesprochen haben. Uns geht es um die Beschreibung eines Zustands, nicht um deren Zuschreibung an eine Seite.',
        modelAnswerEnglish: 'Good morning. That you state this limit clearly is helpful; it is noted. At the same time I would like to record that we have not spoken of responsibility at all so far. We are concerned with describing a state of affairs, not with attributing it to one side.',
        quickReplies: <String>[
          'Ihre Grenze ist zur Kenntnis genommen, unsere Lesart bleibt davon unberührt.',
          'Von Verantwortung war bislang überhaupt nicht die Rede.',
        ],
        coachTip: 'The passive „ist zur Kenntnis genommen“ registers the other side without agreeing to anything.',
      ),
      DialogueStep(
        tutorGerman: 'Dann sagen Sie uns doch bitte, was Sie konkret erwarten. Wir haben heute wenig Zeit.',
        tutorEnglish: 'Then please tell us what exactly you expect. We have little time today.',
        task: 'State your interest without naming a demand you could not later drop.',
        keywords: <String>[
          'interesse',
          'forderung',
          'planbar',
          'quoten',
          'frühwarnsystem',
          'zweitrangig',
        ],
        requiredHits: 3,
        minWords: 26,
        modelAnswer: 'Ich nenne Ihnen lieber unser Interesse als eine Forderung, die uns beide bindet. Uns liegt daran, dass die Entnahmemengen im Sommer planbar werden. Ob das über feste Quoten oder über ein Frühwarnsystem geschieht, ist für uns zweitrangig; entscheidend ist die Planbarkeit für die Betriebe.',
        modelAnswerEnglish: 'I would rather name our interest than a demand that binds us both. What matters to us is that withdrawal volumes become predictable in summer. Whether that happens through fixed quotas or an early warning system is secondary for us; what is decisive is predictability for the farms.',
        quickReplies: <String>[
          'Uns geht es um Planbarkeit, nicht um eine bestimmte Formel.',
          'Ich möchte Ihnen unser Interesse nennen, keine Forderung.',
        ],
        coachTip: 'Naming an interest rather than a demand keeps every later concession from looking like a retreat.',
      ),
      DialogueStep(
        tutorGerman: 'Feste Quoten wären bei uns im Kreistag nicht vermittelbar. Das müssen Sie verstehen.',
        tutorEnglish: 'Fixed quotas could not be sold in our district council. You must understand that.',
        task: 'Show you understand their constraint and reshape the idea so it becomes sayable at home.',
        keywords: <String>[
          'richtwert',
          'zuschnitt',
          'trockenphasen',
          'zumuten',
          'keine quote',
          'überprüfen',
        ],
        requiredHits: 3,
        minWords: 26,
        modelAnswer: 'Das verstehe ich, und ich würde Ihnen auch nicht zumuten, etwas zu vertreten, was Sie zu Hause nicht erklären können. Vielleicht hilft ein anderer Zuschnitt: keine Quote, sondern ein Richtwert, der nur in Trockenphasen greift und den Sie jederzeit überprüfen lassen können.',
        modelAnswerEnglish: 'I understand that, and I would not ask you to defend something you cannot explain at home. Perhaps a different cut would help: not a quota but a guide value that applies only in dry spells and that you can have reviewed at any time.',
        quickReplies: <String>[
          'Was wäre, wenn wir statt einer Quote von einem Richtwert sprächen?',
          'Ich möchte Ihnen nichts zumuten, was Sie zu Hause nicht vertreten können.',
        ],
        coachTip: 'Konjunktiv II plus a softener such as „vielleicht hilft“ turns a counter-proposal into an offer of help.',
      ),
      DialogueStep(
        tutorGerman: 'Ein Richtwert klingt schon eher machbar. Als Zugeständnis könnten wir ihn allerdings nicht verkaufen.',
        tutorEnglish: 'A guide value already sounds more feasible. But we could not sell it as a concession.',
        task: 'Offer a face-saving frame that lets them present the idea as their own.',
        keywords: <String>[
          'gemeinsame initiative',
          'vorarbeit',
          'anschließen',
          'messreihen',
          'ihrer seite',
          'kommuniqué',
        ],
        requiredHits: 3,
        minWords: 26,
        modelAnswer: 'Dann sollte er auch keines sein. Mir wäre es recht, wenn der Vorschlag als gemeinsame Initiative erschiene, angeregt von Ihrer Seite, weil Ihre Fachleute die Messreihen führen. Wir würden uns anschließen und im Kommuniqué ausdrücklich auf Ihre Vorarbeit verweisen.',
        modelAnswerEnglish: 'Then it should not be one. I would be glad if the proposal appeared as a joint initiative, prompted by your side, because your specialists keep the measurement series. We would join it and refer expressly to your preparatory work in the communiqué.',
        quickReplies: <String>[
          'Dann stellen Sie den Vorschlag doch bitte als Ihre Initiative vor.',
          'Wir würden im Text ausdrücklich auf Ihre Vorarbeit verweisen.',
        ],
        coachTip: 'Letting the other side own the idea, with „angeregt von Ihrer Seite“, is the classic face-saving construction.',
      ),
      DialogueStep(
        tutorGerman: 'Das ließe sich machen. Nur: Sollte der Richtwert je überschritten werden, verlangen wir, dass niemand daraus Ansprüche ableitet.',
        tutorEnglish: 'That could be done. Only, should the guide value ever be exceeded, we require that nobody derive claims from it.',
        task: 'Accept a limit on the consequences while keeping the mechanism meaningful.',
        keywords: <String>[
          'keine sanktion',
          'überschreitung',
          'gemeinsame prüfung',
          'verzichten',
          'ansprüche',
          'wirksam',
        ],
        requiredHits: 3,
        minWords: 26,
        modelAnswer: 'Auf Ansprüche im rechtlichen Sinne können wir verzichten, auf Folgen nicht ganz. Mein Vorschlag: Eine Überschreitung löst keine Sanktion aus, sondern lediglich eine gemeinsame Prüfung binnen vier Wochen. Damit bleibt der Richtwert wirksam, ohne dass er irgendjemanden vor Gericht bringt.',
        modelAnswerEnglish: 'We can do without claims in the legal sense, but not entirely without consequences. My proposal: an exceedance triggers no sanction, merely a joint review within four weeks. That keeps the guide value effective without taking anyone to court.',
        quickReplies: <String>[
          'Auf rechtliche Ansprüche können wir verzichten, auf eine Prüfung nicht.',
          'Eine Überschreitung sollte niemanden vor Gericht bringen.',
        ],
        coachTip: 'The pair „nicht …, sondern lediglich“ narrows a consequence without abolishing it.',
      ),
      DialogueStep(
        tutorGerman: 'Gut. Fassen Sie bitte zusammen, worauf wir uns verständigt haben, damit unsere Häuser dasselbe lesen.',
        tutorEnglish: 'Good. Please summarise what we have agreed, so that both our offices read the same thing.',
        task: 'Summarise the compromise in wording both sides can take home unchanged.',
        keywords: <String>[
          'richtwert',
          'überschreitung',
          'prüfung',
          'sanktionen',
          'beide seiten',
          'übernehmen',
        ],
        requiredHits: 3,
        minWords: 24,
        modelAnswer: 'Gern. Beide Seiten empfehlen gemeinsam einen saisonalen Richtwert, angeregt durch Ihre Messreihen. Eine Überschreitung führt zu einer gemeinsamen Prüfung, nicht zu Sanktionen. Von Verantwortung ist an keiner Stelle die Rede. Ich schlage vor, dass wir genau diese vier Sätze in den Text übernehmen.',
        modelAnswerEnglish: 'Gladly. Both sides jointly recommend a seasonal guide value, prompted by your measurement series. An exceedance leads to a joint review, not to sanctions. Responsibility is mentioned nowhere. I suggest we take exactly these four sentences into the text.',
        quickReplies: <String>[
          'Halten wir fest: ein gemeinsamer Richtwert, keine Sanktionen, keine Schuldfrage.',
          'Diese Punkte sollten wortgleich in beide Fassungen gehen.',
        ],
        coachTip: 'A closing summary in bare present-tense sentences leaves no room for two different readings later.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-c2-05',
    level: CefrLevel.c2,
    emoji: '🔬',
    title: 'Das Gutachtergespräch',
    setting: 'An editorial call about a manuscript on farm soil sampling; the other reviewer recommends acceptance.',
    tutorRole: 'Herausgeberin',
    learnerRole: 'Gutachterin/Gutachter',
    goal: 'Hold a methodological objection with unfailing courtesy.',
    usefulPhrases: <String>[
      'Ich möchte das als Ergänzung verstanden wissen.',
      'Er mag damit recht behalten, nur …',
      'Ich würde es als Bitte formulieren, nicht als Mangel.',
      'Daran hängt allerdings die Aussagekraft.',
      'In den meisten Punkten folge ich Ihnen.',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Danke, dass Sie sich Zeit nehmen. Herr Ostermann empfiehlt Annahme; Sie sehen das offenbar anders.',
        tutorEnglish: 'Thank you for making time. Mr Ostermann recommends acceptance; you evidently see it differently.',
        task: 'State your dissent plainly while crediting the other reviewer.',
        keywords: <String>[
          'bedenken',
          'stichprobe',
          'gutachten',
          'ergänzung',
          'widerspruch',
          'schätze',
        ],
        requiredHits: 3,
        minWords: 24,
        modelAnswer: 'Zunächst: Ich schätze das Gutachten von Herrn Ostermann sehr, und in vielen Punkten stimme ich ihm zu. Meine Bedenken betreffen einen einzigen, allerdings tragenden Punkt: die Stichprobenziehung. Ich möchte das nicht als Widerspruch verstanden wissen, sondern als Ergänzung.',
        modelAnswerEnglish: 'First of all: I think very highly of the report by Mr Ostermann, and on many points I agree with him. My reservations concern a single but load-bearing point: the drawing of the sample. I would not want that understood as contradiction, but as a supplement.',
        quickReplies: <String>[
          'In den meisten Punkten folge ich dem Gutachten meines Kollegen.',
          'Mein Vorbehalt betrifft allein die Auswahl der Stichprobe.',
        ],
        coachTip: 'Praising the colleague before the „allerdings“ makes the dissent audible as collegial rather than competitive.',
      ),
      DialogueStep(
        tutorGerman: 'Können Sie das an einer Stelle im Text festmachen?',
        tutorEnglish: 'Can you pin that down to a particular place in the text?',
        task: 'Name the exact passage and the problem without implying carelessness.',
        keywords: <String>[
          'abschnitt drei',
          'auswahlverzerrung',
          'nachvollziehbar',
          'keineswegs',
          'erreichbarkeit',
          'verzerrung',
        ],
        requiredHits: 3,
        minWords: 26,
        modelAnswer: 'Gern, Abschnitt drei, wo die Betriebe nach Erreichbarkeit ausgewählt wurden. Das ist praktisch nachvollziehbar, führt aber zu einer Auswahlverzerrung, die im Text nicht diskutiert wird. Ich unterstelle keineswegs Nachlässigkeit; vermutlich war die Feldphase schlicht zu kurz bemessen.',
        modelAnswerEnglish: 'Gladly, section three, where the farms were selected by accessibility. That is practically understandable, but it produces a selection bias which is not discussed in the text. I by no means impute negligence; the field phase was probably simply too short.',
        quickReplies: <String>[
          'Der entscheidende Punkt steht in Abschnitt drei.',
          'Die Auswahl nach Erreichbarkeit erzeugt eine Verzerrung, die unerwähnt bleibt.',
        ],
        coachTip: 'Attributing the flaw to circumstance with „vermutlich war die Feldphase zu kurz“ keeps the criticism off the person.',
      ),
      DialogueStep(
        tutorGerman: 'Herr Ostermann hält die Verzerrung für vernachlässigbar. Wie gehen wir damit um?',
        tutorEnglish: 'Mr Ostermann considers the bias negligible. How do we deal with that?',
        task: 'Disagree with a colleague\'s judgement while leaving him room.',
        keywords: <String>[
          'einwand',
          'verzerrung',
          'recht behalten',
          'verfasserin',
          'nicht kennen',
          'zurückgeben',
        ],
        requiredHits: 3,
        minWords: 26,
        modelAnswer: 'Er mag damit recht behalten, nur lässt sich das aus den vorliegenden Daten nicht zeigen. Genau darin liegt mein Einwand: Nicht dass die Verzerrung groß wäre, sondern dass wir ihre Größe nicht kennen. Ich würde die Frage deshalb an die Verfasserin zurückgeben.',
        modelAnswerEnglish: 'He may turn out to be right, only that cannot be shown from the available data. That is precisely where my objection lies: not that the bias is large, but that we do not know its size. I would therefore hand the question back to the author.',
        quickReplies: <String>[
          'Möglicherweise hat er recht, belegen lässt es sich aber nicht.',
          'Mein Einwand zielt nicht auf die Größe der Verzerrung, sondern auf unser Nichtwissen.',
        ],
        coachTip: 'The concessive „er mag recht behalten, nur …“ grants the possibility and withholds the conclusion.',
      ),
      DialogueStep(
        tutorGerman: 'Die Verfasserin hat auf die erste Runde recht gereizt reagiert. Wie formulieren wir es diesmal?',
        tutorEnglish: 'The author reacted rather irritably to the first round. How do we phrase it this time?',
        task: 'Propose wording that is exacting but impossible to take as an attack.',
        keywords: <String>[
          'als bitte',
          'mangel',
          'überzeugungskraft',
          'begründet',
          'reichweite',
          'formulieren',
        ],
        requiredHits: 3,
        minWords: 26,
        modelAnswer: 'Ich würde es als Bitte formulieren, nicht als Mangel: Die Arbeit gewänne an Überzeugungskraft, wenn die Auswahl der Betriebe in einem Absatz begründet und ihre Reichweite offen benannt würde. So steht die Sache im Vordergrund und niemand muss sich verteidigen.',
        modelAnswerEnglish: 'I would put it as a request, not as a defect: the paper would gain in persuasiveness if the selection of farms were justified in a paragraph and its reach stated openly. That way the matter stays in the foreground and nobody has to defend themselves.',
        quickReplies: <String>[
          'Formulieren wir es als Bitte um Ergänzung, nicht als Vorwurf.',
          'Ein einziger Absatz zur Auswahl der Betriebe würde genügen.',
        ],
        coachTip: 'Turning a defect into a request with Konjunktiv II, as in „die Arbeit gewänne an Überzeugungskraft“, is the standard courteous review register.',
      ),
      DialogueStep(
        tutorGerman: 'Und wenn sie sich weigert? Dann müssten wir ablehnen, und das wäre schade.',
        tutorEnglish: 'And if she refuses? Then we would have to reject, and that would be a pity.',
        task: 'Suggest a middle path without conceding the substance.',
        keywords: <String>[
          'überarbeitung',
          'auflage',
          'einschränkung',
          'plädiere',
          'sensitivität',
          'einwand',
        ],
        requiredHits: 3,
        minWords: 26,
        modelAnswer: 'Ablehnen müssten wir nur, wenn der Einwand unbeantwortet bliebe. Ich plädiere für eine grundlegende Überarbeitung mit klarer Auflage: eine Sensitivitätsanalyse oder wenigstens eine ehrliche Einschränkung im Fazit. Beides wäre mit vertretbarem Aufwand zu leisten, und die Arbeit verdient es.',
        modelAnswerEnglish: 'We would only have to reject if the objection remained unanswered. I argue for a major revision with a clear requirement: a sensitivity analysis, or at least an honest limitation in the conclusion. Either could be done with reasonable effort, and the paper deserves it.',
        quickReplies: <String>[
          'Eine grundlegende Überarbeitung wäre mir lieber als eine Ablehnung.',
          'Mit einer Einschränkung im Fazit wäre uns allen gedient.',
        ],
        coachTip: 'Offering a graded outcome instead of a verdict shows you are arguing about the work and not about winning.',
      ),
      DialogueStep(
        tutorGerman: 'Gut. Ich schreibe der Verfasserin heute noch. Geben Sie mir einen Satz für die Mail?',
        tutorEnglish: 'Good. I will write to the author today. Will you give me a sentence for the mail?',
        task: 'Give one sentence that carries respect and the requirement together.',
        keywords: <String>[
          'würdigt',
          'feldarbeit',
          'transparent',
          'reichweite',
          'auswahl',
          'sorgfältige',
        ],
        requiredHits: 3,
        minWords: 24,
        modelAnswer: 'Schreiben Sie gern: Das Gutachten würdigt die sorgfältige Feldarbeit ausdrücklich und bittet lediglich darum, die Auswahl der Betriebe und deren Folgen für die Reichweite der Aussagen transparent darzulegen. Über alles Weitere lässt sich dann in Ruhe sprechen.',
        modelAnswerEnglish: 'Do write: the report expressly acknowledges the careful field work and asks only that the selection of farms and its consequences for the reach of the findings be set out transparently. Everything else can then be discussed calmly.',
        quickReplies: <String>[
          'Bitte schreiben Sie, dass wir die Feldarbeit ausdrücklich würdigen.',
          'Ein Satz zur Reichweite der Aussagen genügt uns völlig.',
        ],
        coachTip: 'Coupling explicit praise with one non-negotiable request in a single sentence is the most economical courteous form.',
      ),
    ],
  ),
  ConversationScenario(
    id: 'cv-c2-06',
    level: CefrLevel.c2,
    emoji: '📉',
    title: 'Das Ende einer Baureihe',
    setting: 'A supervisory board meeting at Vollmer und Kranz AG on ending the Aurin appliance line.',
    tutorRole: 'Aufsichtsratsvorsitzende',
    learnerRole: 'Vorständin/Vorstand für Produkt',
    goal: 'Defend an unwelcome recommendation without hardening the room.',
    usefulPhrases: <String>[
      'Gerade deshalb schlage ich das vor.',
      'In einem Punkt teile ich die Einschätzung nicht.',
      'Die Entscheidung liegt selbstverständlich bei Ihnen.',
      'Das möchte ich nicht miteinander vermengen.',
      'Nach heutigem Stand sieht es so aus.',
    ],
    steps: <DialogueStep>[
      DialogueStep(
        tutorGerman: 'Sie beantragen, die Baureihe Aurin einzustellen. Das ist unser Aushängeschild. Begründen Sie das bitte.',
        tutorEnglish: 'You are moving to discontinue the Aurin line. That is our flagship. Please justify it.',
        task: 'Make the case for withdrawal while acknowledging what the product means here.',
        keywords: <String>[
          'deckungsbeitrag',
          'rückzug',
          'baureihe',
          'nachfolger',
          'quartalen',
          'gerade deshalb',
        ],
        requiredHits: 3,
        minWords: 24,
        modelAnswer: 'Mir ist bewusst, was diese Baureihe für das Haus bedeutet; leichtfertig steht sie nicht zur Debatte. Gerade deshalb schlage ich den Rückzug vor: Der Deckungsbeitrag ist seit sechs Quartalen negativ, und jeder weitere Monat bindet Mittel, die wir für den Nachfolger brauchen.',
        modelAnswerEnglish: 'I am aware what this line means for the company; it is not up for discussion lightly. Precisely for that reason I propose withdrawal: the contribution margin has been negative for six quarters, and every further month ties up funds we need for the successor.',
        quickReplies: <String>[
          'Ich stelle den Antrag nicht leichtfertig, sondern aus Verbundenheit mit dem Haus.',
          'Die Zahlen der letzten sechs Quartale lassen keine andere Empfehlung zu.',
        ],
        coachTip: 'Beginning with „mir ist bewusst“ and continuing with „gerade deshalb“ converts sentiment into an argument instead of an obstacle.',
      ),
      DialogueStep(
        tutorGerman: 'Der Vertrieb sagt, mit einem Preisnachlass ließe sich das drehen. Was halten Sie dem entgegen?',
        tutorEnglish: 'Sales say a price cut could turn this around. What do you say to that?',
        task: 'Refute the cheaper option with figures without dismissing the sales team.',
        keywords: <String>[
          'nachlass',
          'absatz',
          'einschätzung',
          'gesenkt',
          'verschiebt',
          'prozent',
        ],
        requiredHits: 3,
        minWords: 26,
        modelAnswer: 'Der Vertrieb kennt den Markt besser als ich, in einem Punkt teile ich die Einschätzung aber nicht. Wir haben den Preis vor einem Jahr bereits um zwölf Prozent gesenkt; der Absatz zog kurz an und fiel danach unter das Ausgangsniveau. Ein zweiter Nachlass verschiebt das Problem nur.',
        modelAnswerEnglish: 'Sales know the market better than I do, yet on one point I do not share the assessment. We already cut the price by twelve per cent a year ago; sales picked up briefly and then fell below the starting level. A second discount only postpones the problem.',
        quickReplies: <String>[
          'Wir haben den Preis bereits gesenkt, ohne dass der Absatz gehalten hätte.',
          'Ein weiterer Nachlass verschiebt das Problem, statt es zu lösen.',
        ],
        coachTip: 'Conceding expertise in one clause and withholding agreement in the next keeps a disagreement from becoming a slight.',
      ),
      DialogueStep(
        tutorGerman: 'Und die Belegschaft in Werk zwei? Dort hängen achtzig Stellen an der Aurin.',
        tutorEnglish: 'And the workforce in plant two? Eighty jobs there depend on the Aurin.',
        task: 'Address the human consequence honestly without letting it settle the question.',
        keywords: <String>[
          'stellen',
          'fertigung',
          'überführen',
          'wirtschaftlichkeit',
          'ernst',
          'entscheiden',
        ],
        requiredHits: 3,
        minWords: 26,
        modelAnswer: 'Diese Frage nehme ich ernst, und ich möchte sie nicht mit der Wirtschaftlichkeit vermengen. Nach heutigem Stand lassen sich rund sechzig Stellen in die neue Fertigung überführen, wenn wir jetzt entscheiden. Warten wir noch ein Jahr, werden es deutlich weniger sein.',
        modelAnswerEnglish: 'I take that question seriously, and I do not want to mix it up with profitability. As things stand today about sixty jobs can be transferred to the new production if we decide now. If we wait another year, it will be considerably fewer.',
        quickReplies: <String>[
          'Je früher wir entscheiden, desto mehr Stellen lassen sich überführen.',
          'Die Frage nach dem Werk gehört getrennt behandelt, nicht verrechnet.',
        ],
        coachTip: 'The verb „vermengen“ signals that you are separating two questions rather than dodging the harder one.',
      ),
      DialogueStep(
        tutorGerman: 'Ein Mitglied des Gremiums fragt, ob Sie sich mit dieser Empfehlung nicht selbst ein Denkmal für Ihr Nachfolgeprojekt setzen wollen.',
        tutorEnglish: 'A member of the board asks whether this recommendation is not you building a monument to your own successor project.',
        task: 'Deflect an insinuation about your motives without indignation.',
        keywords: <String>[
          'sachlich',
          'vergütung',
          'unabhängige prüfung',
          'legitim',
          'empfehlung',
          'zahlen',
        ],
        requiredHits: 3,
        minWords: 26,
        modelAnswer: 'Die Frage ist legitim, deshalb beantworte ich sie sachlich. Der Nachfolger trägt nicht meinen Namen, und meine Vergütung hängt an keiner der beiden Baureihen. Sollten Sie eine unabhängige Prüfung der Zahlen wünschen, unterstütze ich das ausdrücklich; an meiner Empfehlung ändert sie vermutlich nichts.',
        modelAnswerEnglish: 'The question is legitimate, so I will answer it factually. The successor does not bear my name, and my remuneration depends on neither of the two lines. Should you wish an independent review of the figures, I expressly support it; it will probably not change my recommendation.',
        quickReplies: <String>[
          'Die Frage ist legitim, und ich beantworte sie gern sachlich.',
          'Eine unabhängige Prüfung der Zahlen wäre mir sehr willkommen.',
        ],
        coachTip: 'Answering an insinuation with an offer of verification is stronger than any protestation of innocence.',
      ),
      DialogueStep(
        tutorGerman: 'Angenommen, wir vertagen die Entscheidung auf das nächste Quartal. Was kostet uns das?',
        tutorEnglish: 'Suppose we postpone the decision to next quarter. What does that cost us?',
        task: 'Quantify the cost of delay while leaving the decision formally with the board.',
        keywords: <String>[
          'vertagung',
          'millionen',
          'lieferzusagen',
          'entscheidung',
          'bei ihnen',
          'preis',
        ],
        requiredHits: 3,
        minWords: 26,
        modelAnswer: 'Rechnerisch etwa zwei Millionen an weiterem Mittelabfluss, dazu die Lieferzusagen, die wir in der Zwischenzeit eingehen müssten. Die Entscheidung liegt selbstverständlich bei Ihnen; ich bitte nur darum, die Vertagung als das zu behandeln, was sie ist: eine Entscheidung mit eigenem Preis.',
        modelAnswerEnglish: 'In arithmetic terms about two million in further cash outflow, plus the delivery commitments we would have to enter into in the meantime. The decision of course rests with you; I only ask that the postponement be treated as what it is: a decision with a price of its own.',
        quickReplies: <String>[
          'Auch eine Vertagung ist eine Entscheidung, und sie hat ihren Preis.',
          'Jedes weitere Quartal bindet Mittel, die uns anderswo fehlen.',
        ],
        coachTip: 'Calling a postponement „eine Entscheidung mit eigenem Preis“ hands responsibility back to the room without pressing.',
      ),
      DialogueStep(
        tutorGerman: 'Gut. Formulieren Sie uns bitte den Beschlussvorschlag, über den wir abstimmen können.',
        tutorEnglish: 'Good. Please formulate for us the resolution we can vote on.',
        task: 'Put the proposal into one clean resolution the board can vote on.',
        keywords: <String>[
          'auslaufen',
          'jahresende',
          'serviceverträge',
          'überführung',
          'beauftragt',
          'beschäftigten',
        ],
        requiredHits: 3,
        minWords: 24,
        modelAnswer: 'Der Vorstand wird beauftragt, die Baureihe Aurin zum Jahresende auslaufen zu lassen, bestehende Serviceverträge über fünf Jahre zu erfüllen und dem Aufsichtsrat bis März ein Konzept zur Überführung der Beschäftigten vorzulegen. Über den Nachfolger entscheiden wir gesondert.',
        modelAnswerEnglish: 'The management board is instructed to let the Aurin line run out at the end of the year, to honour existing service contracts for five years, and to submit to the supervisory board by March a plan for transferring the staff. We will decide on the successor separately.',
        quickReplies: <String>[
          'Der Beschluss sollte das Auslaufen zum Jahresende und die Serviceverträge umfassen.',
          'Über den Nachfolger sollten wir gesondert abstimmen.',
        ],
        coachTip: 'Resolution German lives on the passive „wird beauftragt“ and on infinitive clauses that state each obligation in turn.',
      ),
    ],
  ),
];
