import 'models.dart';

ChoiceQuestion _xq(
  String prompt,
  List<String> options,
  int correctIndex,
  String explanation,
) =>
    ChoiceQuestion(
      prompt: prompt,
      options: options,
      correctIndex: correctIndex,
      explanation: explanation,
    );

/// Additional original receptive/productive practice.
/// Together with the core curriculum this gives six listening, six reading
/// and six writing lessons per CEFR level.
final List<ListeningLesson> supplementalListeningLessons = <ListeningLesson>[
  ListeningLesson(id:'lx-a1-01', level:CefrLevel.a1, title:'At the bakery', transcript:'Guten Morgen. Ich möchte zwei Brötchen und ein Brot, bitte. Das macht vier Euro zwanzig.', translation:'Good morning. I would like two rolls and a loaf of bread, please. That is €4.20.', questions:<ChoiceQuestion>[_xq('What does the customer buy?', const ['Two rolls and bread','Coffee and cake','Milk only'],0,'The order is stated directly.'), _xq('How much does it cost?', const ['€4.20','€2.40','€14.20'],0,'“vier Euro zwanzig” = €4.20.')]),
  ListeningLesson(id:'lx-a1-02', level:CefrLevel.a1, title:'Meeting time', transcript:'Hallo Nina. Wir treffen uns morgen nicht um acht, sondern um neun Uhr vor der Bibliothek.', translation:'Hello Nina. We are meeting tomorrow not at eight but at nine in front of the library.', questions:<ChoiceQuestion>[_xq('When is the meeting?', const ['09:00','08:00','10:00'],0,'The corrected time is nine.'), _xq('Where?', const ['In front of the library','At the station','At home'],0,'“vor der Bibliothek”.')]),
  ListeningLesson(id:'lx-a1-03', level:CefrLevel.a1, title:'Daily routine', transcript:'Ich stehe um halb sieben auf. Um sieben frühstücke ich und um acht beginnt meine Arbeit.', translation:'I get up at 6:30. At seven I have breakfast and at eight my work begins.', questions:<ChoiceQuestion>[_xq('When does work begin?', const ['08:00','07:00','06:30'],0,'“um acht beginnt meine Arbeit”.'), _xq('What happens at seven?', const ['Breakfast','Work begins','Going to bed'],0,'Breakfast is at seven.')]),

  ListeningLesson(id:'lx-a2-01', level:CefrLevel.a2, title:'Doctor appointment', transcript:'Ihr Termin am Dienstag muss leider verschoben werden. Wir können Ihnen Mittwoch um elf Uhr oder Freitag um halb drei anbieten.', translation:'Your Tuesday appointment unfortunately has to be moved. We can offer Wednesday at 11 or Friday at 2:30.', questions:<ChoiceQuestion>[_xq('Why is the call being made?', const ['To reschedule an appointment','To order medicine','To cancel insurance'],0,'The Tuesday appointment must be moved.'), _xq('Which is an offered time?', const ['Wednesday 11:00','Thursday 11:00','Friday 13:30'],0,'Wednesday at eleven is offered.')]),
  ListeningLesson(id:'lx-a2-02', level:CefrLevel.a2, title:'Train disruption', transcript:'Der Regionalzug nach Berlin hat heute ungefähr zwanzig Minuten Verspätung. Reisende nach Potsdam benutzen bitte Gleis vier.', translation:'The regional train to Berlin is about twenty minutes late today. Passengers to Potsdam should use platform four.', questions:<ChoiceQuestion>[_xq('How late is the Berlin train?', const ['About 20 minutes','Exactly 2 hours','It is on time'],0,'The announcement says about twenty minutes.'), _xq('Which platform for Potsdam?', const ['4','2','14'],0,'“Gleis vier”.')]),
  ListeningLesson(id:'lx-a2-03', level:CefrLevel.a2, title:'Weekend plan', transcript:'Am Samstag wollen wir zuerst auf den Markt gehen. Wenn es regnet, besuchen wir stattdessen das Museum. Am Abend essen wir bei Freunden.', translation:'On Saturday we first want to go to the market. If it rains, we will visit the museum instead. In the evening we eat at friends’ place.', questions:<ChoiceQuestion>[_xq('What is the bad-weather alternative?', const ['Museum','Beach','Cinema'],0,'The museum is the rain plan.'), _xq('Where do they eat in the evening?', const ['At friends’ place','At the market','At work'],0,'They eat with friends.')]),

  ListeningLesson(id:'lx-b1-01', level:CefrLevel.b1, title:'Work arrangement', transcript:'Seit wir zwei Tage pro Woche im Homeoffice arbeiten können, spare ich viel Fahrzeit. Für kreative Besprechungen komme ich aber lieber ins Büro, weil der direkte Austausch dort besser funktioniert.', translation:'Since we can work from home two days per week, I save a lot of commuting time. But for creative meetings I prefer the office because direct exchange works better there.', questions:<ChoiceQuestion>[_xq('What advantage of home office is mentioned?', const ['Less commuting time','Higher salary','Shorter meetings'],0,'The speaker saves travel time.'), _xq('Why prefer the office for creative meetings?', const ['Direct exchange works better','The internet is forbidden at home','The office is quieter'],0,'Direct interaction is the reason.')]),
  ListeningLesson(id:'lx-b1-02', level:CefrLevel.b1, title:'Course feedback', transcript:'Der Kurs war fachlich sehr gut, aber ich hätte mir mehr praktische Übungen gewünscht. Besonders hilfreich fand ich die Beispiele aus dem Berufsalltag.', translation:'The course was very good in terms of content, but I would have liked more practical exercises. I found the examples from professional life especially helpful.', questions:<ChoiceQuestion>[_xq('What was missing?', const ['More practical exercises','Theory','Professional examples'],0,'The speaker wanted more practical exercises.'), _xq('What was especially helpful?', const ['Workplace examples','The price','The room'],0,'Examples from professional life.')]),
  ListeningLesson(id:'lx-b1-03', level:CefrLevel.b1, title:'Local initiative', transcript:'Die Stadt sucht Freiwillige für ein neues Nachbarschaftsprojekt. Man muss keine besondere Ausbildung haben, sollte aber regelmäßig zwei Stunden pro Woche Zeit mitbringen.', translation:'The city is looking for volunteers for a new neighborhood project. No special training is required, but volunteers should have two hours per week regularly.', questions:<ChoiceQuestion>[_xq('Is special training required?', const ['No','Yes','Only for students'],0,'No special training is needed.'), _xq('What commitment is expected?', const ['Two hours weekly','Two days daily','One hour monthly'],0,'Two hours per week.')]),

  ListeningLesson(id:'lx-b2-01', level:CefrLevel.b2, title:'Research interview', transcript:'Die Studie zeigt zwar einen deutlichen Zusammenhang zwischen Bewegung und Wohlbefinden, erlaubt aber keine eindeutige Aussage über Ursache und Wirkung. Dafür wäre ein anderes Studiendesign erforderlich.', translation:'The study shows a clear relationship between exercise and well-being, but it does not allow a clear statement about cause and effect. A different study design would be required for that.', questions:<ChoiceQuestion>[_xq('What cannot be concluded?', const ['Definite causality','A relationship exists','The design matters'],0,'The speaker explicitly rejects a definite causal conclusion.'), _xq('What would be needed?', const ['A different study design','More advertising','No data'],0,'A different design is mentioned.')]),
  ListeningLesson(id:'lx-b2-02', level:CefrLevel.b2, title:'Policy discussion', transcript:'Eine höhere Parkgebühr allein wird den Verkehr kaum grundlegend verändern. Wir brauchen zugleich zuverlässige Alternativen, sonst trifft die Maßnahme vor allem Menschen, die auf das Auto angewiesen sind.', translation:'A higher parking fee alone will hardly fundamentally change traffic. We also need reliable alternatives; otherwise the measure mainly affects people who depend on cars.', questions:<ChoiceQuestion>[_xq('What is the main argument?', const ['Fees need viable alternatives alongside them','Parking should always be free','Public transport is already perfect'],0,'The speaker argues for complementary alternatives.'), _xq('Who could be disproportionately affected?', const ['People dependent on cars','Only tourists','No one'],0,'This group is named directly.')]),
  ListeningLesson(id:'lx-b2-03', level:CefrLevel.b2, title:'Project retrospective', transcript:'Technisch haben wir das Ziel erreicht, organisatorisch war der Aufwand jedoch höher als geplant. Beim nächsten Durchlauf sollten Zuständigkeiten früher geklärt und Schnittstellen eindeutiger dokumentiert werden.', translation:'Technically we achieved the goal, but organizational effort was higher than planned. Next time responsibilities should be clarified earlier and interfaces documented more clearly.', questions:<ChoiceQuestion>[_xq('What succeeded?', const ['The technical goal','The budget','The schedule perfectly'],0,'The technical goal was reached.'), _xq('What should improve?', const ['Responsibilities and interface documentation','Office furniture','Marketing only'],0,'Both are explicitly recommended.')]),

  ListeningLesson(id:'lx-c1-01', level:CefrLevel.c1, title:'Scientific caution', transcript:'Die Effekte sind statistisch robust, ihre praktische Größenordnung bleibt allerdings begrenzt. Für politische Entscheidungen wäre deshalb zu prüfen, ob der erwartete Nutzen die Umsetzungskosten tatsächlich rechtfertigt.', translation:'The effects are statistically robust, but their practical magnitude remains limited. For policy decisions it should therefore be examined whether expected benefits justify implementation costs.', questions:<ChoiceQuestion>[_xq('What distinction is emphasized?', const ['Statistical robustness versus practical magnitude','Science versus language','Cost versus legality only'],0,'The speaker distinguishes statistical evidence from practical importance.'), _xq('What additional question matters for policy?', const ['Whether benefits justify costs','Whether statistics exist','Whether the study is German'],0,'Cost-benefit relevance is required.')]),
  ListeningLesson(id:'lx-c1-02', level:CefrLevel.c1, title:'Institutional change', transcript:'Die Reform verändert nicht nur einzelne Verfahren, sondern verschiebt auch Verantwortung. Gerade deshalb sollte vor der Einführung geklärt werden, wer Entscheidungen nachvollziehbar begründen und im Fehlerfall korrigieren kann.', translation:'The reform changes not only individual procedures but also shifts responsibility. Therefore it should be clarified who can justify decisions transparently and correct them in case of error.', questions:<ChoiceQuestion>[_xq('What deeper change is identified?', const ['A shift of responsibility','Only new software colors','No procedural change'],0,'Responsibility shifts as well.'), _xq('What must be clarified?', const ['Who can justify and correct decisions','Who owns the building','Who speaks first'],0,'Accountability and correction are the focus.')]),
  ListeningLesson(id:'lx-c1-03', level:CefrLevel.c1, title:'Media argument', transcript:'Die Debatte wird häufig so geführt, als müsse man sich zwischen Innovation und Schutz entscheiden. Diese Gegenüberstellung ist zu grob, denn kluge Regeln können Innovation gerade dadurch ermöglichen, dass sie Erwartungen und Haftung klären.', translation:'The debate is often framed as if one had to choose between innovation and protection. This opposition is too crude, because good rules can enable innovation precisely by clarifying expectations and liability.', questions:<ChoiceQuestion>[_xq('What framing is criticized?', const ['Innovation versus protection as a simple either-or','Rules can clarify liability','Innovation needs expectations'],0,'The speaker calls the binary opposition too crude.'), _xq('How can rules support innovation?', const ['By clarifying expectations and liability','By banning all experimentation','By removing responsibility'],0,'This is the proposed mechanism.')]),

  ListeningLesson(id:'lx-c2-01', level:CefrLevel.c2, title:'Conceptual precision', transcript:'Dass ein Begriff im Alltag unscharf verwendet wird, ist noch kein Einwand gegen seine analytische Brauchbarkeit. Entscheidend ist vielmehr, ob die gewählte Definition für die jeweilige Fragestellung Unterschiede sichtbar macht, die sonst verborgen blieben.', translation:'The fact that a term is used vaguely in everyday language is not yet an objection to its analytical usefulness. What matters is whether the chosen definition reveals distinctions relevant to the question.', questions:<ChoiceQuestion>[_xq('What determines analytical usefulness?', const ['Whether the definition reveals relevant distinctions','Everyday vagueness alone','How long the word is'],0,'Usefulness is tied to the research question and distinctions.'), _xq('What is NOT automatically a fatal objection?', const ['Vague everyday use','No definition at all','Contradictory evidence'],0,'Everyday vagueness alone is not decisive.')]),
  ListeningLesson(id:'lx-c2-02', level:CefrLevel.c2, title:'Normative trade-off', transcript:'Die Forderung nach vollständiger Sicherheit klingt zunächst plausibel, setzt aber einen Maßstab, der selbst folgenreich ist. Wer jedes Restrisiko ausschließen will, kann dadurch Handlungsoptionen blockieren, deren Verzicht ebenfalls Risiken erzeugt.', translation:'The demand for complete safety initially sounds plausible but establishes a consequential standard. Excluding every residual risk can block options whose absence itself creates risks.', questions:<ChoiceQuestion>[_xq('What paradox is identified?', const ['Avoiding all risk can itself create risk','Safety has no value','Every action is equally safe'],0,'Risk avoidance can have opportunity costs and risks.'), _xq('What is being challenged?', const ['A zero-risk standard','All safety regulation','The existence of choices'],0,'The speaker questions complete elimination of residual risk.')]),
  ListeningLesson(id:'lx-c2-03', level:CefrLevel.c2, title:'Rhetorical concession', transcript:'Der Einwand trifft insofern zu, als kurzfristige Kosten bislang unterschätzt wurden. Daraus folgt jedoch nicht, dass das langfristige Ziel aufgegeben werden sollte; vielmehr spricht es für eine andere Reihenfolge der Maßnahmen.', translation:'The objection is valid insofar as short-term costs have been underestimated. It does not follow, however, that the long-term goal should be abandoned; rather, it argues for a different sequencing of measures.', questions:<ChoiceQuestion>[_xq('How is the objection handled?', const ['Partly accepted, but used to revise sequencing rather than the goal','Completely dismissed','Accepted as proof the goal is wrong'],0,'The concession changes implementation, not the goal.'), _xq('What is recommended?', const ['A different order of measures','No action','A different language'],0,'The sequencing should change.')]),
];

final List<ReadingLesson> supplementalReadingLessons = <ReadingLesson>[
  ReadingLesson(id:'rx-a1-01', level:CefrLevel.a1, title:'Library notice', passage:'Bibliothek: Montag bis Freitag 9–18 Uhr. Samstag 10–14 Uhr. Sonntag geschlossen.', questions:<ChoiceQuestion>[_xq('When is the library closed?', const ['Sunday','Saturday','Friday'],0,'Sunday is closed.'), _xq('When does it open Saturday?', const ['10:00','09:00','14:00'],0,'Saturday hours begin at 10.')]),
  ReadingLesson(id:'rx-a1-02', level:CefrLevel.a1, title:'Short message', passage:'Hallo Tom, ich bin schon im Café. Ich sitze am Fenster. Bis gleich! Lea', questions:<ChoiceQuestion>[_xq('Where is Lea?', const ['In a café','At home','At school'],0,'She says she is in the café.'), _xq('Where is she sitting?', const ['By the window','Outside','At the door'],0,'“am Fenster”.')]),
  ReadingLesson(id:'rx-a1-03', level:CefrLevel.a1, title:'Course poster', passage:'Deutschkurs A1: Dienstag und Donnerstag, 18–20 Uhr. Start: 5. September. Raum 204.', questions:<ChoiceQuestion>[_xq('How often per week?', const ['Twice','Once','Five times'],0,'Tuesday and Thursday.'), _xq('Which room?', const ['204','205','18'],0,'Room 204 is given.')]),

  ReadingLesson(id:'rx-a2-01', level:CefrLevel.a2, title:'Apartment notice', passage:'Wegen Reparaturarbeiten gibt es am Mittwoch zwischen 9 und 12 Uhr kein warmes Wasser. Bitte planen Sie entsprechend. Ab Mittag funktioniert die Versorgung wieder normal.', questions:<ChoiceQuestion>[_xq('What is unavailable?', const ['Hot water','Electricity','Internet'],0,'Warm water is interrupted.'), _xq('When should it work normally again?', const ['From noon','Next week','At 9:00'],0,'“Ab Mittag”.')]),
  ReadingLesson(id:'rx-a2-02', level:CefrLevel.a2, title:'Return policy', passage:'Sie können unbenutzte Artikel innerhalb von 30 Tagen zurückgeben. Bitte bringen Sie den Kassenbon mit. Personalisierte Produkte sind von der Rückgabe ausgeschlossen.', questions:<ChoiceQuestion>[_xq('What should customers bring?', const ['Receipt','Passport','Photo'],0,'The receipt is required.'), _xq('What cannot be returned?', const ['Personalized products','All unused products','Shoes'],0,'Personalized products are excluded.')]),
  ReadingLesson(id:'rx-a2-03', level:CefrLevel.a2, title:'Event update', passage:'Das Straßenfest findet wegen des Wetters nicht im Park, sondern in der Stadthalle statt. Beginn und Eintrittspreis bleiben unverändert.', questions:<ChoiceQuestion>[_xq('What changes?', const ['The location','The price','The starting time'],0,'Only the venue changes.'), _xq('Where will it happen?', const ['City hall/event hall','Park','Station'],0,'It moves to the Stadthalle.')]),

  ReadingLesson(id:'rx-b1-01', level:CefrLevel.b1, title:'Bike sharing', passage:'Die Stadt erweitert ihr Fahrradverleihsystem. Neue Stationen entstehen vor allem in Wohngebieten, die bisher schlecht an Bus und Bahn angebunden sind. Damit soll nicht nur der Autoverkehr reduziert, sondern auch der Weg zur nächsten Haltestelle erleichtert werden.', questions:<ChoiceQuestion>[_xq('Why are new stations focused on certain neighborhoods?', const ['They have weak public-transport connections','They have too many trains','Bicycles are forbidden downtown'],0,'The text targets poorly connected areas.'), _xq('What second goal is mentioned?', const ['Easier access to transit stops','Higher car sales','Fewer bus stops'],0,'Bikes can bridge the trip to public transport.')]),
  ReadingLesson(id:'rx-b1-02', level:CefrLevel.b1, title:'Training policy', passage:'Mitarbeitende können jährlich drei Weiterbildungstage beantragen. Die Schulung muss einen Bezug zur aktuellen oder geplanten Tätigkeit haben. Über die Kostenübernahme entscheidet die Abteilungsleitung nach Prüfung des Antrags.', questions:<ChoiceQuestion>[_xq('How many training days are possible?', const ['Three per year','Three per month','Unlimited'],0,'Three annual days.'), _xq('Who decides about costs?', const ['Department management','The trainer automatically','The city'],0,'The department leadership decides.')]),
  ReadingLesson(id:'rx-b1-03', level:CefrLevel.b1, title:'Community repair café', passage:'Im Repair-Café helfen Ehrenamtliche dabei, defekte Alltagsgegenstände zu untersuchen und wenn möglich zu reparieren. Eine Garantie für eine erfolgreiche Reparatur gibt es nicht. Ziel ist vor allem, Wissen zu teilen und unnötigen Abfall zu vermeiden.', questions:<ChoiceQuestion>[_xq('Is a successful repair guaranteed?', const ['No','Yes','Only for phones'],0,'There is explicitly no guarantee.'), _xq('What is a main goal?', const ['Share knowledge and reduce waste','Sell new products','Collect fees'],0,'Both goals are stated.')]),

  ReadingLesson(id:'rx-b2-01', level:CefrLevel.b2, title:'Algorithmic decisions', passage:'Automatisierte Entscheidungen können Prozesse beschleunigen, doch ihre Effizienz sagt wenig darüber aus, ob die zugrunde liegenden Kriterien angemessen sind. Besonders problematisch wird es, wenn Betroffene weder nachvollziehen können, welche Daten verwendet wurden, noch eine wirksame Möglichkeit haben, fehlerhafte Entscheidungen anzufechten.', questions:<ChoiceQuestion>[_xq('What is the central concern?', const ['Efficiency does not guarantee appropriate or contestable decisions','Automation is always slower','Data never matter'],0,'The text distinguishes efficiency from legitimacy and contestability.'), _xq('What safeguard is implied?', const ['Transparency and an appeal mechanism','More hidden criteria','No human review'],0,'Understanding and contesting decisions are key.')]),
  ReadingLesson(id:'rx-b2-02', level:CefrLevel.b2, title:'Urban housing', passage:'Eine Mietpreisbremse kann kurzfristig Haushalte entlasten, löst aber nicht automatisch den Mangel an Wohnungen. Wird gleichzeitig zu wenig gebaut, verschärft sich die Konkurrenz um das knappe Angebot. Befürworter zusätzlicher Maßnahmen fordern deshalb, Preisregeln mit schnellerem Wohnungsbau zu verbinden.', questions:<ChoiceQuestion>[_xq('What limitation of price controls is described?', const ['They do not automatically increase housing supply','They always raise rents','They eliminate demand'],0,'Supply shortage remains.'), _xq('What combined approach is proposed?', const ['Price rules plus more construction','Only fewer tenants','No regulation'],0,'The final sentence combines both.')]),
  ReadingLesson(id:'rx-b2-03', level:CefrLevel.b2, title:'Evidence and headlines', passage:'Medienberichte reduzieren komplexe Studienergebnisse häufig auf eine eindeutige Schlagzeile. Dabei gehen Einschränkungen verloren, etwa kleine Stichproben, unsichere Schätzungen oder die Tatsache, dass eine beobachtete Korrelation keine Kausalität beweist. Gute Wissenschaftskommunikation macht solche Grenzen sichtbar, ohne die Ergebnisse dadurch wertlos erscheinen zu lassen.', questions:<ChoiceQuestion>[_xq('What can headlines obscure?', const ['Methodological limitations','The title of the study only','All findings are false'],0,'Several limitations are listed.'), _xq('What should good communication do?', const ['Explain limits without dismissing the findings','Hide uncertainty','Claim causality'],0,'The last sentence states this balance.')]),

  ReadingLesson(id:'rx-c1-01', level:CefrLevel.c1, title:'Proxy metrics', passage:'Kennzahlen erleichtern Vergleiche, doch sobald sie zum unmittelbaren Ziel werden, verändern sie häufig das Verhalten derjenigen, die bewertet werden. Eine hohe Zahl abgeschlossener Vorgänge kann etwa Effizienz signalisieren, zugleich aber Anreize schaffen, schwierige Fälle zu vermeiden. Entscheidend ist daher, Messgrößen nicht mit dem eigentlichen Zweck einer Organisation zu verwechseln.', questions:<ChoiceQuestion>[_xq('What risk arises when a metric becomes a target?', const ['Behavior may optimize the metric rather than the real purpose','Measurements become impossible','Difficult cases disappear naturally'],0,'The text describes distorted incentives.'), _xq('What distinction should be maintained?', const ['Metric versus organizational purpose','Numbers versus words only','Employees versus customers'],0,'The final sentence makes this distinction.')]),
  ReadingLesson(id:'rx-c1-02', level:CefrLevel.c1, title:'Public consultation', passage:'Beteiligungsverfahren erhöhen nicht automatisch die Legitimität einer Entscheidung. Werden nur besonders ressourcenstarke Gruppen erreicht, kann eine formal offene Konsultation bestehende Ungleichgewichte sogar verstärken. Entscheidend ist daher nicht nur, ob Beteiligung angeboten wird, sondern wer tatsächlich teilnehmen kann und wie Beiträge in die Entscheidung einfließen.', questions:<ChoiceQuestion>[_xq('Why can an open consultation still be problematic?', const ['Participation may be socially uneven','It always has too many votes','Legitimacy never matters'],0,'Resource differences can skew participation.'), _xq('What else besides offering participation matters?', const ['Who can participate and how input is used','Only the venue','The logo'],0,'Both are explicitly stated.')]),
  ReadingLesson(id:'rx-c1-03', level:CefrLevel.c1, title:'Risk communication', passage:'Wer Unsicherheit kommuniziert, riskiert missverstanden zu werden: Zahlenbereiche können als Unwissen erscheinen, obwohl sie gerade eine präzisere Aussage über den Stand der Erkenntnis erlauben. Umgekehrt erzeugen scheinbar exakte Einzelwerte leicht eine Sicherheit, die die Daten nicht hergeben. Gute Risikokommunikation muss daher Präzision und Verständlichkeit zugleich organisieren.', questions:<ChoiceQuestion>[_xq('What problem can a single exact number create?', const ['False certainty','More uncertainty by definition','No comprehension'],0,'It may imply confidence unsupported by data.'), _xq('What balance is required?', const ['Precision and comprehensibility','Speed and secrecy','Certainty and advertising'],0,'The final sentence names both.')]),

  ReadingLesson(id:'rx-c2-01', level:CefrLevel.c2, title:'Institutional neutrality', passage:'Neutralität wird häufig als Abwesenheit von Wertentscheidungen missverstanden. Institutionelle Verfahren kommen jedoch nicht ohne Auswahl aus: Schon die Festlegung dessen, was als relevanter Sachverhalt gilt, strukturiert mögliche Ergebnisse. Der Anspruch auf Neutralität ist deshalb sinnvoller als Verpflichtung zu nachvollziehbaren, konsistenten und revidierbaren Begründungen zu verstehen denn als Behauptung völliger Wertfreiheit.', questions:<ChoiceQuestion>[_xq('How is neutrality reframed?', const ['As transparent, consistent and revisable justification rather than value-free absence of choices','As no rules at all','As personal preference'],0,'The passage proposes a procedural understanding.'), _xq('Why is total value-freedom questioned?', const ['Selecting relevant facts already structures outcomes','Facts never matter','Institutions make no selections'],0,'Selection itself has consequences.')]),
  ReadingLesson(id:'rx-c2-02', level:CefrLevel.c2, title:'Explanation and prediction', passage:'Eine Erklärung gewinnt nicht schon dadurch an Qualität, dass sie im Nachhinein mit jedem möglichen Ergebnis vereinbar gemacht werden kann. Gerade die Bereitschaft, unter bestimmten Bedingungen scheitern zu können, begrenzt interpretative Beliebigkeit. Das bedeutet nicht, dass jede gute Theorie punktgenaue Prognosen liefern muss, wohl aber, dass sie unterscheidbare Erwartungen erzeugen sollte.', questions:<ChoiceQuestion>[_xq('What quality criterion is defended?', const ['A theory should generate distinguishable expectations and risk failure','A theory should fit every outcome','Exact prediction is always mandatory'],0,'The text emphasizes constraints and distinguishable expectations.'), _xq('What is NOT claimed?', const ['Every theory must predict exact numbers','Post-hoc flexibility can be problematic','Failure conditions matter'],0,'The final sentence explicitly qualifies exact prediction.')]),
  ReadingLesson(id:'rx-c2-03', level:CefrLevel.c2, title:'Policy language', passage:'Metaphern sind in politischen Debatten nicht bloß Schmuck. Wer etwa von einer „Welle“ spricht, legt Bewegung, Richtung und Überwältigung nahe und prägt damit, welche Reaktionen intuitiv plausibel erscheinen. Eine kritische Analyse fragt daher nicht nur, ob einzelne Aussagen wahr sind, sondern auch, welche Problemstruktur die verwendete Sprache voraussetzt.', questions:<ChoiceQuestion>[_xq('What role do metaphors play?', const ['They frame the structure of a problem and plausible responses','They are purely decorative','They replace all facts'],0,'The passage treats metaphor as framing.'), _xq('What does critical analysis additionally examine?', const ['The problem structure implied by language','Only spelling','Only whether a sentence is long'],0,'That is the final claim.')]),
];

final List<WritingLesson> supplementalWritingLessons = <WritingLesson>[
  WritingLesson(id:'wx-a1-01', level:CefrLevel.a1, title:'Introduce yourself', prompt:'Write a short self-introduction: name, city, job/study and one hobby.', guidance:const ['Use complete simple sentences','Use ich + verb','Include four pieces of information'], minWords:30, keywords:const ['ich','wohne','arbeite','gern'], example:'Ich heiße Samir. Ich wohne in Rostock. Ich arbeite an einer Universität. In meiner Freizeit lese ich gern und gehe spazieren.'),
  WritingLesson(id:'wx-a1-02', level:CefrLevel.a1, title:'Change a meeting', prompt:'Write a short message: you cannot meet today, give one simple reason and suggest tomorrow.', guidance:const ['Greeting','Reason','New time','Closing'], minWords:30, keywords:const ['heute','nicht','morgen','uhr'], example:'Hallo Lea, heute kann ich leider nicht kommen, weil ich arbeiten muss. Können wir uns morgen um 18 Uhr treffen? Viele Grüße!'),
  WritingLesson(id:'wx-a1-03', level:CefrLevel.a1, title:'My day', prompt:'Describe your normal weekday with morning, work/study and evening.', guidance:const ['Use time expressions','Use present tense','Write at least four sentences'], minWords:40, keywords:const ['morgens','dann','abends'], example:'Morgens stehe ich um sieben Uhr auf. Dann frühstücke ich. Um acht Uhr beginne ich mit der Arbeit. Abends koche ich und lese ein Buch.'),

  WritingLesson(id:'wx-a2-01', level:CefrLevel.a2, title:'Request information', prompt:'Write to a language school asking about course dates, price and timetable.', guidance:const ['Polite opening','Three questions','Reason for interest','Closing'], minWords:70, keywords:const ['kurs','kosten','wann','freundlichen'], example:'Sehr geehrte Damen und Herren, ich interessiere mich für Ihren Deutschkurs. Wann beginnt der nächste Kurs, wie viel kostet er und an welchen Tagen findet der Unterricht statt? Vielen Dank. Mit freundlichen Grüßen'),
  WritingLesson(id:'wx-a2-02', level:CefrLevel.a2, title:'Past weekend', prompt:'Write about last weekend: where you went, what you did, and what you liked.', guidance:const ['Use Perfekt','Sequence events','Give an opinion'], minWords:75, keywords:const ['am wochenende','habe','bin','gefallen'], example:'Am Wochenende bin ich nach Hamburg gefahren. Dort habe ich Freunde besucht und wir haben zusammen gegessen. Danach sind wir am Hafen spazieren gegangen. Der Ausflug hat mir sehr gut gefallen.'),
  WritingLesson(id:'wx-a2-03', level:CefrLevel.a2, title:'Problem at home', prompt:'Write to your landlord about a household problem and ask for a repair appointment.', guidance:const ['Describe problem','Say since when','Ask for appointment','Be polite'], minWords:80, keywords:const ['leider','seit','termin','bitte'], example:'Guten Tag, leider funktioniert die Heizung seit gestern nicht mehr. Die Wohnung ist sehr kalt. Könnten Sie bitte einen Reparaturtermin organisieren? Am Mittwoch bin ich ab 15 Uhr zu Hause.'),

  WritingLesson(id:'wx-b1-01', level:CefrLevel.b1, title:'Course evaluation', prompt:'Write feedback on a course: strengths, one problem and one improvement proposal.', guidance:const ['Balanced tone','Specific example','Concrete suggestion','Conclusion'], minWords:120, keywords:const ['besonders','allerdings','vorschlagen','insgesamt'], example:'Insgesamt hat mir der Kurs gut gefallen. Besonders hilfreich waren die praktischen Beispiele. Allerdings war für die Übungen oft zu wenig Zeit. Ich würde vorschlagen, den Theorieblock etwas zu kürzen und mehr Gruppenarbeit einzuplanen.'),
  WritingLesson(id:'wx-b1-02', level:CefrLevel.b1, title:'Public transport opinion', prompt:'Should city public transport be cheaper? Give your view, reasons and one limitation.', guidance:const ['State position','Give two reasons','Acknowledge limitation','Conclude'], minWords:130, keywords:const ['meiner meinung','außerdem','allerdings','deshalb'], example:'Meiner Meinung nach sollte der öffentliche Nahverkehr günstiger sein. Dadurch könnten mehr Menschen auf das Auto verzichten. Außerdem würden Personen mit geringem Einkommen entlastet. Allerdings muss eine gute Finanzierung gesichert sein. Deshalb halte ich günstigere Tickets zusammen mit verlässlichen Verbindungen für sinnvoll.'),
  WritingLesson(id:'wx-b1-03', level:CefrLevel.b1, title:'Unexpected change', prompt:'Narrate a situation in which an important plan changed unexpectedly and explain how you solved the problem.', guidance:const ['Set context','Describe unexpected event','Explain solution','Reflect on result'], minWords:130, keywords:const ['zuerst','plötzlich','daraufhin','schließlich'], example:'Zuerst wollten wir mit dem Auto fahren. Plötzlich sprang der Motor nicht mehr an. Daraufhin riefen wir einen Freund an und fuhren gemeinsam zum Bahnhof. Schließlich erreichten wir unser Ziel mit dem Zug und kamen nur etwas später an.'),

  WritingLesson(id:'wx-b2-01', level:CefrLevel.b2, title:'Forum contribution', prompt:'Discuss whether universities should require attendance in lectures.', guidance:const ['Introduce controversy','Develop both sides','Use examples','Take a reasoned position'], minWords:190, keywords:const ['einerseits','andererseits','dennoch','meines erachtens'], example:'Eine allgemeine Anwesenheitspflicht wird kontrovers diskutiert. Einerseits kann regelmäßige Teilnahme den Austausch fördern. Andererseits lernen Erwachsene unterschiedlich und tragen Verantwortung für ihren Studienerfolg. Dennoch können verpflichtende Termine dort sinnvoll sein, wo praktische Zusammenarbeit zentral ist. Meines Erachtens sollte deshalb zwischen Vorlesungen und interaktiven Übungen unterschieden werden.'),
  WritingLesson(id:'wx-b2-02', level:CefrLevel.b2, title:'Formal recommendation', prompt:'Recommend measures to reduce unnecessary meetings in an organization.', guidance:const ['Define problem','Propose at least two measures','Discuss trade-offs','Prioritize'], minWords:190, keywords:const ['maßnahme','zudem','voraussetzung','empfehlen'], example:'Als erste Maßnahme empfehle ich, für jede Besprechung ein klares Ziel und eine Agenda zu verlangen. Zudem sollten reine Informationsupdates standardmäßig schriftlich erfolgen. Voraussetzung ist allerdings, dass Entscheidungen weiterhin transparent dokumentiert werden. Priorität sollte daher auf der Trennung von Informationsweitergabe und echter Abstimmung liegen.'),
  WritingLesson(id:'wx-b2-03', level:CefrLevel.b2, title:'Study interpretation', prompt:'Explain a fictional correlation without overclaiming causality and propose one follow-up study.', guidance:const ['Report association','Name limitations','Avoid causal language','Propose better design'], minWords:200, keywords:const ['zusammenhang','jedoch','ursache','untersuchung'], example:'Die Daten zeigen einen Zusammenhang zwischen Arbeitsweg und berichteter Zufriedenheit. Daraus folgt jedoch nicht, dass ein längerer Arbeitsweg unmittelbar die Ursache geringerer Zufriedenheit ist. Denkbar sind etwa Unterschiede bei Beruf, Einkommen oder Arbeitszeit. Eine weitere Untersuchung könnte diese Faktoren kontrollieren und dieselben Personen über längere Zeit beobachten.'),

  WritingLesson(id:'wx-c1-01', level:CefrLevel.c1, title:'Policy brief', prompt:'Write a short policy brief on algorithmic decision systems: benefits, risks, safeguards and recommendation.', guidance:const ['Executive opening','Differentiate efficiency and fairness','Concrete safeguards','Prioritized recommendation'], minWords:260, keywords:const ['effizienz','fairness','transparenz','kontrolle'], example:'Automatisierte Entscheidungssysteme können Effizienz und Konsistenz erhöhen, doch beides garantiert keine Fairness. Risiken entstehen insbesondere durch ungeeignete Trainingsdaten, intransparente Kriterien und fehlende Einspruchsmöglichkeiten. Eine verantwortliche Nutzung erfordert daher dokumentierte Ziele, regelmäßige Prüfungen, transparente Begründungen und wirksame menschliche Kontrolle. Empfehlenswert ist eine stufenweise Einführung in Bereichen mit reversiblen Entscheidungen.'),
  WritingLesson(id:'wx-c1-02', level:CefrLevel.c1, title:'Research critique', prompt:'Critique a study whose large sample yields a statistically significant but very small effect.', guidance:const ['Distinguish significance/effect size','Discuss practical relevance','Mention uncertainty','Avoid dismissiveness'], minWords:260, keywords:const ['signifikant','effektgröße','relevanz','konfidenz'], example:'Der statistisch signifikante Befund ist aufgrund der großen Stichprobe erwartbar, sollte aber nicht mit praktischer Relevanz gleichgesetzt werden. Entscheidend ist die Effektgröße, die hier nur gering ausfällt. Zusätzlich sollte die Unsicherheit der Schätzung anhand eines Konfidenzintervalls betrachtet werden. Der Befund ist somit informativ, rechtfertigt allein aber noch keine weitreichende Intervention.'),
  WritingLesson(id:'wx-c1-03', level:CefrLevel.c1, title:'Mediated argument', prompt:'Present two serious positions in a dispute over remote work and propose a compromise that addresses both.', guidance:const ['Represent both fairly','Identify underlying interests','Propose compromise','State limits'], minWords:270, keywords:const ['befürworter','kritiker','zugleich','kompromiss'], example:'Befürworter flexibler Heimarbeit verweisen auf Autonomie und eingesparte Pendelzeit, während Kritiker den Verlust informeller Abstimmung und erschwerte Einarbeitung betonen. Beide Positionen adressieren legitime Bedürfnisse. Ein tragfähiger Kompromiss könnte flexible Heimarbeit mit wenigen klar begründeten Präsenztagen verbinden. Zugleich sollte regelmäßig geprüft werden, ob diese Regel für unterschiedliche Tätigkeiten gleichermaßen funktioniert.'),

  WritingLesson(id:'wx-c2-01', level:CefrLevel.c2, title:'Conceptual essay', prompt:'Examine whether procedural neutrality can exist without substantive value choices.', guidance:const ['Define terms carefully','Develop tension','Address strongest objection','Reach qualified conclusion'], minWords:360, keywords:const ['neutralität','verfahren','wertentscheidung','gleichwohl'], example:'Verfahrensneutralität ist plausibel, wenn sie als konsistente Anwendung öffentlich begründbarer Regeln verstanden wird. Sie wird problematisch, sobald daraus Wertfreiheit abgeleitet wird: Schon die Auswahl relevanter Kriterien enthält normative Vorentscheidungen. Gleichwohl folgt daraus nicht, dass jedes Verfahren beliebig wäre. Neutralität kann vielmehr als institutionelle Disziplin verstanden werden, Gründe transparent, symmetrisch und revidierbar zu behandeln.'),
  WritingLesson(id:'wx-c2-02', level:CefrLevel.c2, title:'Synthesis under uncertainty', prompt:'Synthesize conflicting evidence about a policy and distinguish disagreement about facts, values and risk tolerance.', guidance:const ['Separate empirical/normative claims','Explain uncertainty','Compare risk tolerance','Synthesize rather than list'], minWords:380, keywords:const ['evidenz','unsicherheit','wert','risiko'], example:'Die scheinbare Uneinigkeit lässt sich teilweise entflechten. Empirisch unterscheiden sich die Studien in der geschätzten Effektgröße; normativ gewichten die Positionen Verteilungsgerechtigkeit unterschiedlich; zusätzlich variiert ihre Toleranz gegenüber seltenen, aber schweren Risiken. Eine Synthese sollte diese Ebenen nicht vermengen: Evidenz reduziert Unsicherheit, entscheidet jedoch nicht allein, welche Risiken gesellschaftlich akzeptabel sind.'),
  WritingLesson(id:'wx-c2-03', level:CefrLevel.c2, title:'Rhetorical reframing', prompt:'Write an editorial that identifies a false binary in a public debate and reframes the underlying question.', guidance:const ['Expose binary','Steelman both sides','Identify hidden premise','Offer better question','Control register'], minWords:380, keywords:const ['gegenüberstellung','einerseits','andererseits','stattdessen'], example:'Die übliche Gegenüberstellung von Innovation und Regulierung suggeriert, Schutz könne nur auf Kosten technischer Entwicklung entstehen. Einerseits ist die Sorge vor Überregulierung berechtigt; andererseits schafft völlige Regelungsunsicherheit eigene Investitionsrisiken. Versteckt bleibt die Annahme, Regeln seien ausschließlich Bremsen. Stattdessen sollte gefragt werden, welche Regeln verlässliche Erwartungen schaffen, ohne Lernprozesse unnötig zu blockieren.'),
];
