import 'models.dart';

const List<SpeakingLesson> speakingLessons = <SpeakingLesson>[
  SpeakingLesson(id: 'sp-a1-01', level: CefrLevel.a1, title: 'Introduce yourself', prompt: 'Introduce yourself: name, origin, city, job/studies and one hobby.', guidance: <String>['Speak in short complete sentences.', 'Use ich bin / ich komme / ich wohne / ich arbeite.', 'Aim for clear pronunciation rather than speed.'], modelPhrases: <String>['Ich heiße …', 'Ich komme aus …', 'Ich wohne in …', 'In meiner Freizeit …'], targetSeconds: 45),
  SpeakingLesson(id: 'sp-a1-02', level: CefrLevel.a1, title: 'At a café', prompt: 'Order a drink and something to eat, ask the price and thank the server.', guidance: <String>['Use polite requests.', 'Ask at least one question.', 'Finish the interaction naturally.'], modelPhrases: <String>['Ich hätte gern …', 'Was kostet …?', 'Noch einen Kaffee, bitte.', 'Vielen Dank.'], targetSeconds: 45),
  SpeakingLesson(id: 'sp-a1-03', level: CefrLevel.a1, title: 'My day', prompt: 'Describe a normal weekday from morning to evening.', guidance: <String>['Use clock times.', 'Use first/then/later.', 'Mention at least four activities.'], modelPhrases: <String>['Um sieben Uhr …', 'Dann …', 'Am Nachmittag …', 'Abends …'], targetSeconds: 60),

  SpeakingLesson(id: 'sp-a2-01', level: CefrLevel.a2, title: 'Make an appointment', prompt: 'Call a doctor’s office, explain a simple problem and arrange a suitable appointment.', guidance: <String>['State the reason for calling.', 'React to one unsuitable time.', 'Confirm the final time.'], modelPhrases: <String>['Ich möchte einen Termin vereinbaren.', 'Seit zwei Tagen …', 'Da kann ich leider nicht.', 'Dann komme ich am …'], targetSeconds: 75),
  SpeakingLesson(id: 'sp-a2-02', level: CefrLevel.a2, title: 'Plan a weekend', prompt: 'Suggest a weekend activity to a friend, compare two options and agree on a plan.', guidance: <String>['Make and respond to suggestions.', 'Give a simple reason.', 'Agree on time and place.'], modelPhrases: <String>['Wollen wir …?', 'Ich finde … besser, weil …', 'Das passt mir.', 'Treffen wir uns um …'], targetSeconds: 90),
  SpeakingLesson(id: 'sp-a2-03', level: CefrLevel.a2, title: 'Describe a past event', prompt: 'Tell a friend about a recent trip, celebration or problem.', guidance: <String>['Use Perfekt.', 'Give the order of events.', 'Say how you felt.'], modelPhrases: <String>['Letztes Wochenende habe ich …', 'Danach sind wir …', 'Am Ende …', 'Ich fand es …'], targetSeconds: 90),

  SpeakingLesson(id: 'sp-b1-01', level: CefrLevel.b1, title: 'Give and support an opinion', prompt: 'Should people work from home several days per week? Give your view with reasons and one counterargument.', guidance: <String>['State your position clearly.', 'Give at least two reasons.', 'Acknowledge a disadvantage.'], modelPhrases: <String>['Meiner Meinung nach …', 'Ein wichtiger Grund dafür ist …', 'Allerdings muss man berücksichtigen, dass …', 'Insgesamt …'], targetSeconds: 120),
  SpeakingLesson(id: 'sp-b1-02', level: CefrLevel.b1, title: 'Solve a problem together', prompt: 'A group event has been cancelled. Propose an alternative plan, divide tasks and agree on next steps.', guidance: <String>['Make concrete proposals.', 'Ask for the other person’s view.', 'Summarise the agreement.'], modelPhrases: <String>['Ich schlage vor, dass …', 'Was hältst du davon?', 'Ich könnte … übernehmen.', 'Dann machen wir es so: …'], targetSeconds: 150),
  SpeakingLesson(id: 'sp-b1-03', level: CefrLevel.b1, title: 'Present an experience', prompt: 'Describe a learning or work experience that changed how you do something.', guidance: <String>['Give background.', 'Describe what happened.', 'Explain the consequence or lesson.'], modelPhrases: <String>['Damals …', 'Dabei habe ich gemerkt, dass …', 'Seitdem …', 'Heute würde ich …'], targetSeconds: 150),

  SpeakingLesson(id: 'sp-b2-01', level: CefrLevel.b2, title: 'Structured argument', prompt: 'Discuss whether cities should restrict private cars in their centres.', guidance: <String>['Frame the issue.', 'Compare benefits and costs.', 'Use examples and qualify your conclusion.'], modelPhrases: <String>['Dafür spricht zunächst …', 'Dem steht jedoch entgegen, dass …', 'Entscheidend ist meines Erachtens …', 'Unter der Voraussetzung, dass …'], targetSeconds: 210),
  SpeakingLesson(id: 'sp-b2-02', level: CefrLevel.b2, title: 'Professional negotiation', prompt: 'Negotiate a project deadline when your team lacks enough time and staff.', guidance: <String>['Describe constraints objectively.', 'Offer at least two alternatives.', 'Negotiate a compromise.'], modelPhrases: <String>['Unter den aktuellen Bedingungen …', 'Eine Möglichkeit wäre …', 'Könnten wir uns darauf verständigen, dass …?', 'Damit könnten wir … sicherstellen.'], targetSeconds: 210),
  SpeakingLesson(id: 'sp-b2-03', level: CefrLevel.b2, title: 'Compare sources', prompt: 'Imagine two reports disagree about remote work productivity. Explain possible reasons for the difference.', guidance: <String>['Identify assumptions.', 'Compare methods or groups.', 'Avoid claiming certainty without evidence.'], modelPhrases: <String>['Die Abweichung könnte darauf zurückzuführen sein, dass …', 'Während die eine Untersuchung …, berücksichtigt die andere …', 'Daraus lässt sich nicht ohne Weiteres schließen, dass …'], targetSeconds: 240),

  SpeakingLesson(id: 'sp-c1-01', level: CefrLevel.c1, title: 'Academic mini-presentation', prompt: 'Present a nuanced position on the opportunities and risks of generative AI in higher education.', guidance: <String>['Define the issue precisely.', 'Build a multi-part argument.', 'Distinguish evidence, inference and personal judgement.'], modelPhrases: <String>['Zunächst ist zwischen … zu unterscheiden.', 'Die vorliegenden Befunde legen nahe …', 'Daraus folgt allerdings nicht zwangsläufig …', 'Unter Abwägung dieser Aspekte …'], targetSeconds: 300),
  SpeakingLesson(id: 'sp-c1-02', level: CefrLevel.c1, title: 'Chair a discussion', prompt: 'Open a discussion on a controversial workplace policy, invite positions, mediate disagreement and summarise.', guidance: <String>['Use neutral framing.', 'Signal turn-taking and clarification.', 'Reformulate competing views fairly.'], modelPhrases: <String>['Zur Diskussion steht die Frage, ob …', 'Wenn ich Ihren Punkt richtig verstehe …', 'Darin scheint ein zentraler Unterschied zu liegen.', 'Als Zwischenfazit lässt sich festhalten …'], targetSeconds: 300),
  SpeakingLesson(id: 'sp-c1-03', level: CefrLevel.c1, title: 'Critical response', prompt: 'Respond to the claim: “More data automatically leads to better decisions.”', guidance: <String>['Interrogate the premise.', 'Give a counterexample.', 'Offer a more defensible reformulation.'], modelPhrases: <String>['Die Aussage greift insofern zu kurz, als …', 'Ein Gegenbeispiel wäre …', 'Treffender wäre die Formulierung …', 'Voraussetzung dafür ist allerdings …'], targetSeconds: 300),

  SpeakingLesson(id: 'sp-c2-01', level: CefrLevel.c2, title: 'Nuanced policy defence', prompt: 'Defend a policy you only partly agree with, accurately representing objections while explaining why it may still be justified.', guidance: <String>['Use calibrated certainty.', 'Distinguish principle from implementation.', 'Anticipate and answer a sophisticated objection.'], modelPhrases: <String>['Der Einwand ist keineswegs von der Hand zu weisen.', 'Gleichwohl wäre zu unterscheiden zwischen …', 'Die Rechtfertigung hängt letztlich davon ab, ob …', 'In dieser eingeschränkten Lesart …'], targetSeconds: 360),
  SpeakingLesson(id: 'sp-c2-02', level: CefrLevel.c2, title: 'Register shift', prompt: 'Explain the same complex research result first to specialists and then to a non-specialist audience.', guidance: <String>['Preserve the factual core.', 'Change terminology and sentence density.', 'Use analogy only where it remains accurate.'], modelPhrases: <String>['Fachsprachlich lässt sich dies als … beschreiben.', 'Vereinfacht gesagt bedeutet das …', 'Dabei darf die Vereinfachung nicht darüber hinwegtäuschen, dass …'], targetSeconds: 360),
  SpeakingLesson(id: 'sp-c2-03', level: CefrLevel.c2, title: 'Synthesis under pressure', prompt: 'Synthesize three imagined viewpoints on automation—economic, ethical and technical—and formulate a conditional conclusion.', guidance: <String>['Integrate rather than list viewpoints.', 'Show tensions and common assumptions.', 'Conclude with explicit conditions and limits.'], modelPhrases: <String>['Die drei Perspektiven widersprechen einander nur teilweise.', 'Gemeinsam ist ihnen die Annahme, dass …', 'Der eigentliche Zielkonflikt liegt zwischen …', 'Eine tragfähige Schlussfolgerung wäre daher nur dann …'], targetSeconds: 420),
];
