/// How each pictogram moves. Generated by tool/build_vocab_motion.py.
///
/// Do not edit by hand: the record is tool/vocab_line_icons.tsv, and
/// tool/check_line_icons.py fails the build when this file disagrees with it.
///
/// Motion is here because a verb is not a thing. A still pictogram of a plane
/// says "plane"; the same pictogram travelling says "to fly". That is the part
/// a picture of a noun never had to do, and it is why animated stock footage
/// looked worth having -- but the motion is the meaningful half, and we can
/// author that ourselves for nothing.
library;

/// The kinds of movement a pictogram can carry.
enum VocabMotion {
  /// Still. Plenty of words are better served by not moving.
  none,

  /// Crosses the tile and comes back: going, sending, arriving.
  travel,

  /// Tips side to side: working, cleaning, using a thing.
  rock,

  /// Breathes: speaking, mattering, being noticed.
  pulse,

  /// Lifts: getting up, learning, improving.
  rise,

  /// Dims: sleeping, tiring, ending.
  fade,

  /// Turns: time, repetition, exchange.
  spin,
}

/// Card id to the movement its pictogram carries.
const Map<String, VocabMotion> vocabMotions = <String, VocabMotion>{
  'x10009': VocabMotion.none, // wohnen
  'x10010': VocabMotion.rock, // arbeiten
  'x10011': VocabMotion.rise, // lernen
  'x10012': VocabMotion.pulse, // sprechen
  'x10013': VocabMotion.pulse, // verstehen
  'x10014': VocabMotion.pulse, // fragen
  'x10015': VocabMotion.travel, // antworten
  'x10016': VocabMotion.pulse, // sagen
  'x10018': VocabMotion.travel, // gehen
  'x10019': VocabMotion.travel, // fahren
  'x10021': VocabMotion.travel, // kaufen
  'x10022': VocabMotion.pulse, // bezahlen
  'x10023': VocabMotion.pulse, // kosten
  'x10024': VocabMotion.rock, // essen
  'x10025': VocabMotion.rock, // trinken
  'x10027': VocabMotion.fade, // schlafen
  'x10028': VocabMotion.rock, // aufstehen
  'x10029': VocabMotion.pulse, // anfangen
  'x10030': VocabMotion.none, // aufhören
  'x10031': VocabMotion.rock, // öffnen
  'x10032': VocabMotion.none, // schließen
  'x10041': VocabMotion.none, // heute
  'x10043': VocabMotion.spin, // jetzt
  'x10045': VocabMotion.rise, // früh
  'x10046': VocabMotion.fade, // spät
  'x10047': VocabMotion.spin, // immer
  'x10050': VocabMotion.none, // nie
  'x10051': VocabMotion.pulse, // hier
  'x10053': VocabMotion.travel, // links
  'x10054': VocabMotion.travel, // rechts
  'x10055': VocabMotion.rise, // geradeaus
  'x10058': VocabMotion.pulse, // groß
  'x10059': VocabMotion.pulse, // klein
  'x10060': VocabMotion.rise, // gut
  'x10061': VocabMotion.none, // schlecht
  'x10062': VocabMotion.pulse, // neu
  'x10063': VocabMotion.spin, // alt
  'x10064': VocabMotion.pulse, // schön
  'x10065': VocabMotion.travel, // schnell
  'x10067': VocabMotion.rise, // warm
  'x10068': VocabMotion.spin, // kalt
  'x10069': VocabMotion.pulse, // heiß
  'x10070': VocabMotion.fade, // müde
  'x10071': VocabMotion.pulse, // krank
  'x10072': VocabMotion.pulse, // gesund
  'x10073': VocabMotion.rock, // hungrig
  'x10074': VocabMotion.fade, // durstig
  'x10076': VocabMotion.pulse, // fertig
  'x10077': VocabMotion.pulse, // wichtig
  'x10078': VocabMotion.pulse, // richtig
  'x10079': VocabMotion.rock, // falsch
  'x10080': VocabMotion.none, // zusammen
  'x10081': VocabMotion.none, // allein
  'x10102': VocabMotion.rock, // absagen
  'x10104': VocabMotion.pulse, // reservieren
  'x10105': VocabMotion.none, // bestellen
  'x10107': VocabMotion.pulse, // erklären
  'x10115': VocabMotion.none, // planen
  'x10117': VocabMotion.spin, // versuchen
  'x10120': VocabMotion.rock, // besuchen
  'x10121': VocabMotion.pulse, // treffen
  'x10122': VocabMotion.travel, // einladen
  'x10123': VocabMotion.pulse, // feiern
  'x10124': VocabMotion.pulse, // helfen
  'x10125': VocabMotion.pulse, // zeigen
  'x10126': VocabMotion.travel, // schicken
  'x10127': VocabMotion.rise, // bekommen
  'x10128': VocabMotion.travel, // bringen
  'x10131': VocabMotion.travel, // ankommen
  'x10132': VocabMotion.travel, // abfahren
  'x10133': VocabMotion.travel, // umsteigen
  'x10135': VocabMotion.travel, // reisen
  'x10136': VocabMotion.travel, // fliegen
  'x10137': VocabMotion.rock, // mieten
  'x10138': VocabMotion.travel, // umziehen
  'x10139': VocabMotion.rock, // reparieren
  'x10140': VocabMotion.rock, // putzen
  'x10141': VocabMotion.spin, // waschen
  'x10142': VocabMotion.rock, // einkaufen
  'x10143': VocabMotion.rock, // verkaufen
  'x10146': VocabMotion.pulse, // sparen
  'x10147': VocabMotion.spin, // verdienen
  'x10148': VocabMotion.pulse, // zahlen
  'x10149': VocabMotion.travel, // überweisen
  'x10150': VocabMotion.rock, // anrufen
};
