"""Scratch batch file: card tuples in, JSON out. Overwritten per batch."""
import io
import json
import sys

# (article, german, plural, english, exampleGerman, exampleEnglish, category, level)
CARDS = [
    ("die", "Tragweite", "—", "significance, scope", "Die Tragweite dieser Entscheidung ist noch nicht absehbar.", "The significance of this decision is not yet foreseeable.", "Abstract", "C1"),
    ("die", "Zurückhaltung", "—", "restraint, reticence", "Die Behörde übt bewusst Zurückhaltung.", "The authority is deliberately exercising restraint.", "Stance", "C1"),
    ("die", "Nachdrücklichkeit", "—", "emphasis, insistence", "Er vertrat seine Position mit großer Nachdrücklichkeit.", "He advocated his position with great insistence.", "Stance", "C1"),
    ("der", "Vorbehalt", "die Vorbehalte", "reservation, proviso", "Sie stimmte nur unter Vorbehalt zu.", "She agreed only with reservations.", "Stance", "C1"),
    ("die", "Gewichtung", "die Gewichtungen", "weighting", "Die Gewichtung der Kriterien wurde offengelegt.", "The weighting of the criteria was disclosed.", "Academic", "C1"),
    ("die", "Abgrenzung", "die Abgrenzungen", "delimitation", "Eine klare Abgrenzung der Begriffe fehlt bislang.", "A clear delimitation of the terms is so far missing.", "Academic", "C1"),
    ("die", "Wechselwirkung", "die Wechselwirkungen", "interaction", "Zwischen beiden Faktoren besteht eine Wechselwirkung.", "There is an interaction between the two factors.", "Science", "C1"),
    ("die", "Rahmenbedingung", "die Rahmenbedingungen", "framework condition", "Die politischen Rahmenbedingungen haben sich geändert.", "The political framework conditions have changed.", "Politics", "C1"),
    ("der", "Spielraum", "die Spielräume", "scope, leeway", "Der finanzielle Spielraum ist eng geworden.", "The financial leeway has become narrow.", "Economy", "C1"),
    ("der", "Zielkonflikt", "die Zielkonflikte", "conflict of objectives", "Hier liegt ein klassischer Zielkonflikt vor.", "This is a classic conflict of objectives.", "Economy", "C1"),
    ("die", "Verhältnismäßigkeit", "—", "proportionality", "Das Gericht prüfte die Verhältnismäßigkeit der Maßnahme.", "The court examined the proportionality of the measure.", "Law", "C1"),
    ("die", "Rechtsprechung", "—", "case law, jurisprudence", "Die Rechtsprechung ist in diesem Punkt uneinheitlich.", "Case law is inconsistent on this point.", "Law", "C1"),
    ("die", "Auflage", "die Auflagen", "condition, requirement", "Die Erlaubnis wurde mit strengen Auflagen erteilt.", "The permission was granted with strict conditions.", "Law", "C1"),
    ("die", "Zuständigkeit", "die Zuständigkeiten", "competence, jurisdiction", "Die Zuständigkeit liegt beim Landesamt.", "Jurisdiction lies with the state office.", "Administration", "C1"),
    ("die", "Willkür", "—", "arbitrariness", "Der Vorwurf der Willkür wiegt schwer.", "The accusation of arbitrariness weighs heavily.", "Law", "C1"),
    ("die", "Nachvollziehbarkeit", "—", "traceability, comprehensibility", "Es mangelt an Nachvollziehbarkeit der Entscheidung.", "The decision lacks comprehensibility.", "Academic", "C1"),
    ("die", "Aussagekraft", "—", "informative value", "Die Stichprobe besitzt nur begrenzte Aussagekraft.", "The sample has only limited informative value.", "Science", "C1"),
    ("die", "Verzerrung", "die Verzerrungen", "distortion, bias", "Eine systematische Verzerrung ist nicht auszuschließen.", "A systematic bias cannot be ruled out.", "Science", "C1"),
    ("die", "Streuung", "die Streuungen", "dispersion, scatter", "Die Streuung der Werte ist auffällig hoch.", "The dispersion of the values is strikingly high.", "Science", "C1"),
    ("die", "Näherung", "die Näherungen", "approximation", "Das Modell liefert nur eine grobe Näherung.", "The model provides only a rough approximation.", "Science", "C1"),
    ("die", "Wechselseitigkeit", "—", "reciprocity", "Die Wechselseitigkeit der Verpflichtungen ist zentral.", "The reciprocity of the obligations is central.", "Philosophy", "C1"),
    ("die", "Zwangsläufigkeit", "—", "inevitability", "Von einer Zwangsläufigkeit kann keine Rede sein.", "There can be no talk of inevitability.", "Philosophy", "C1"),
    ("die", "Beliebigkeit", "—", "arbitrariness, interchangeability", "Diese Auslegung öffnet der Beliebigkeit Tür und Tor.", "This interpretation opens the door to arbitrariness.", "Philosophy", "C1"),
    ("das", "Spannungsfeld", "die Spannungsfelder", "area of tension", "Die Debatte bewegt sich in einem Spannungsfeld.", "The debate moves within an area of tension.", "Philosophy", "C1"),
    ("der", "Gegenentwurf", "die Gegenentwürfe", "counter-proposal", "Die Opposition legte einen Gegenentwurf vor.", "The opposition presented a counter-proposal.", "Politics", "C1"),
    ("die", "Sichtweise", "die Sichtweisen", "perspective, viewpoint", "Beide Sichtweisen haben ihre Berechtigung.", "Both perspectives have their justification.", "Stance", "C1"),
    ("die", "Deutungshoheit", "—", "interpretive authority", "Um die Deutungshoheit wird heftig gerungen.", "There is fierce struggle over interpretive authority.", "Society", "C1"),
    ("der", "Konsens", "—", "consensus", "Ein tragfähiger Konsens zeichnet sich ab.", "A viable consensus is emerging.", "Politics", "C1"),
    ("der", "Kompromiss", "die Kompromisse", "compromise", "Der Kompromiss befriedigt keine Seite ganz.", "The compromise fully satisfies neither side.", "Politics", "C1"),
    ("die", "Eskalation", "die Eskalationen", "escalation", "Eine weitere Eskalation muss vermieden werden.", "A further escalation must be avoided.", "Politics", "C1"),
    ("die", "Entfremdung", "—", "alienation", "Viele beklagen eine Entfremdung von der Politik.", "Many lament an alienation from politics.", "Society", "C1"),
    ("die", "Teilhabe", "—", "participation, inclusion", "Gesellschaftliche Teilhabe darf nicht vom Einkommen abhängen.", "Social participation must not depend on income.", "Society", "C1"),
    ("die", "Chancengleichheit", "—", "equality of opportunity", "Chancengleichheit bleibt ein politisches Ziel.", "Equality of opportunity remains a political goal.", "Society", "C1"),
    ("die", "Zumutung", "die Zumutungen", "imposition, unreasonable demand", "Diese Frist ist schlicht eine Zumutung.", "This deadline is simply an unreasonable demand.", "Society", "C1"),
    ("der", "Missstand", "die Missstände", "grievance, abuse", "Der Bericht deckt gravierende Missstände auf.", "The report uncovers serious abuses.", "Society", "C1"),
    ("die", "Fürsorge", "—", "care, welfare", "Die staatliche Fürsorge greift erst spät.", "State welfare only takes effect late.", "Society", "C1"),
    ("die", "Belastbarkeit", "—", "resilience, load capacity", "Die Belastbarkeit des Systems wurde überschätzt.", "The resilience of the system was overestimated.", "General", "C1"),
    ("die", "Anfälligkeit", "—", "susceptibility", "Die Anfälligkeit für Störungen ist bekannt.", "The susceptibility to faults is known.", "Technology", "C1"),
    ("die", "Widerstandsfähigkeit", "—", "resistance, robustness", "Die Widerstandsfähigkeit des Materials überzeugt.", "The robustness of the material is convincing.", "Technology", "C1"),
    ("die", "Rückkopplung", "die Rückkopplungen", "feedback loop", "Eine positive Rückkopplung verstärkt den Effekt.", "A positive feedback loop amplifies the effect.", "Science", "C1"),
    ("", "abwägen", "—", "to weigh up", "Man muss Nutzen und Risiko sorgfältig abwägen.", "One must carefully weigh up benefit and risk.", "Academic", "C1"),
    ("", "relativieren", "—", "to put into perspective", "Die Autorin relativiert ihre eigene These.", "The author puts her own thesis into perspective.", "Academic", "C1"),
    ("", "differenzieren", "—", "to differentiate", "Hier muss man deutlich differenzieren.", "One must clearly differentiate here.", "Academic", "C1"),
    ("", "verallgemeinern", "—", "to generalise", "Solche Befunde lassen sich nicht verallgemeinern.", "Such findings cannot be generalised.", "Academic", "C1"),
    ("", "einräumen", "—", "to concede, admit", "Der Minister räumte Fehler ein.", "The minister conceded mistakes.", "Stance", "C1"),
    ("", "beanstanden", "—", "to object to, criticise", "Der Prüfer beanstandete mehrere Punkte.", "The auditor objected to several points.", "Administration", "C1"),
    ("", "hinterfragen", "—", "to question critically", "Diese Annahme sollte man kritisch hinterfragen.", "One should critically question this assumption.", "Academic", "C1"),
    ("", "untermauern", "—", "to underpin, back up", "Er untermauerte seine These mit Zahlen.", "He underpinned his thesis with figures.", "Academic", "C1"),
    ("", "revidieren", "—", "to revise", "Wir mussten unsere Einschätzung revidieren.", "We had to revise our assessment.", "Academic", "C1"),
    ("", "eingrenzen", "—", "to narrow down", "Zunächst gilt es, das Problem einzugrenzen.", "First the problem must be narrowed down.", "Academic", "C1"),
    ("", "veranschaulichen", "—", "to illustrate", "Eine Grafik kann den Zusammenhang veranschaulichen.", "A chart can illustrate the connection.", "Academic", "C1"),
    ("", "erörtern", "—", "to discuss, examine", "Der Aufsatz erörtert mehrere Lösungswege.", "The essay discusses several solutions.", "Academic", "C1"),
    ("", "darlegen", "—", "to set out, explain", "Sie legte ihre Gründe ausführlich dar.", "She set out her reasons in detail.", "Academic", "C1"),
    ("", "nahelegen", "—", "to suggest, indicate", "Die Daten legen einen anderen Schluss nahe.", "The data suggest a different conclusion.", "Academic", "C1"),
    ("", "zutreffen", "—", "to apply, be accurate", "Diese Beschreibung trifft nur teilweise zu.", "This description is only partly accurate.", "Academic", "C1"),
    ("", "überwiegen", "—", "to outweigh, predominate", "Die Vorteile überwiegen die Nachteile deutlich.", "The advantages clearly outweigh the disadvantages.", "General", "C1"),
    ("", "sich abzeichnen", "—", "to become apparent", "Eine Trendwende zeichnet sich langsam ab.", "A change of trend is slowly becoming apparent.", "General", "C1"),
    ("", "sich niederschlagen", "—", "to be reflected in", "Die Reform schlägt sich in den Zahlen nieder.", "The reform is reflected in the figures.", "Economy", "C1"),
    ("", "zurückführen", "—", "to attribute to", "Den Rückgang führt man auf mehrere Ursachen zurück.", "The decline is attributed to several causes.", "Academic", "C1"),
    ("", "beitragen", "—", "to contribute", "Jeder kann zum Erfolg beitragen.", "Everyone can contribute to the success.", "General", "C1"),
    ("", "bedingen", "—", "to cause, necessitate", "Der Umbau bedingt eine längere Schließung.", "The renovation necessitates a longer closure.", "General", "C1"),
    ("", "entfallen", "—", "to be omitted, not apply", "Die Gebühr entfällt für Studierende.", "The fee does not apply to students.", "Administration", "C1"),
    ("", "aufgreifen", "—", "to take up, pick up on", "Der Bericht greift ältere Vorschläge auf.", "The report takes up older proposals.", "Academic", "C1"),
    ("", "sich durchsetzen", "—", "to prevail, catch on", "Die neue Norm hat sich rasch durchgesetzt.", "The new standard caught on quickly.", "Technology", "C1"),
    ("", "einhergehen", "—", "to be accompanied by", "Wachstum geht oft mit Belastungen einher.", "Growth is often accompanied by burdens.", "Economy", "C1"),
    ("", "gravierend", "—", "serious, grave", "Es handelt sich um einen gravierenden Mangel.", "This is a serious defect.", "General", "C1"),
    ("", "tragfähig", "—", "viable, sustainable", "Wir brauchen eine tragfähige Lösung.", "We need a viable solution.", "General", "C1"),
    ("", "nachhaltig", "—", "sustainable, lasting", "Die Wirkung war überraschend nachhaltig.", "The effect was surprisingly lasting.", "Environment", "C1"),
    ("", "unerlässlich", "—", "indispensable", "Sorgfalt ist hier unerlässlich.", "Care is indispensable here.", "General", "C1"),
    ("", "hinreichend", "—", "sufficient", "Die Begründung ist nicht hinreichend.", "The justification is not sufficient.", "Academic", "C1"),
    ("", "maßgeblich", "—", "decisive, authoritative", "Sie war maßgeblich an dem Projekt beteiligt.", "She was decisively involved in the project.", "General", "C1"),
    ("", "einschlägig", "—", "relevant, pertinent", "Die einschlägige Literatur ist umfangreich.", "The relevant literature is extensive.", "Academic", "C1"),
    ("", "vorrangig", "—", "primary, with priority", "Diese Aufgabe ist vorrangig zu behandeln.", "This task is to be treated with priority.", "Administration", "C1"),
    ("", "beispiellos", "—", "unprecedented", "Der Andrang war beispiellos.", "The rush was unprecedented.", "General", "C1"),
    ("", "zweifelsohne", "—", "undoubtedly", "Das ist zweifelsohne ein Fortschritt.", "That is undoubtedly progress.", "Stance", "C1"),
    ("", "vermeintlich", "—", "supposed, alleged", "Der vermeintliche Vorteil erwies sich als Irrtum.", "The supposed advantage proved to be an error.", "Stance", "C1"),
    ("", "durchweg", "—", "consistently, throughout", "Die Rückmeldungen waren durchweg positiv.", "The feedback was consistently positive.", "General", "C1"),
    ("", "mitunter", "—", "sometimes, occasionally", "Die Verfahren dauern mitunter Jahre.", "The proceedings sometimes take years.", "General", "C1"),
    ("", "nunmehr", "—", "now, henceforth", "Die Regelung gilt nunmehr bundesweit.", "The rule now applies nationwide.", "Formal", "C1"),
    ("", "ohnehin", "—", "anyway, in any case", "Der Termin war ohnehin zu knapp bemessen.", "The deadline was too tight anyway.", "General", "C1"),
    ("", "gleichwohl", "—", "nevertheless", "Der Einwand ist berechtigt, gleichwohl bleibt das Ziel richtig.", "The objection is valid, nevertheless the goal remains right.", "Linking", "C1"),
    ("", "zumal", "—", "especially since", "Wir sollten warten, zumal die Lage unklar ist.", "We should wait, especially since the situation is unclear.", "Linking", "C1"),
    ("", "sofern", "—", "provided that", "Sofern nichts dagegen spricht, beginnen wir morgen.", "Provided nothing speaks against it, we begin tomorrow.", "Linking", "C1"),
    ("", "anhand", "—", "on the basis of", "Anhand der Unterlagen lässt sich das prüfen.", "That can be checked on the basis of the documents.", "Formal", "C1"),
    ("", "hinsichtlich", "—", "with regard to", "Hinsichtlich der Kosten gibt es noch Fragen.", "With regard to the costs there are still questions.", "Formal", "C1"),
    ("", "angesichts", "—", "in view of", "Angesichts der Lage wurde die Reise abgesagt.", "In view of the situation the trip was cancelled.", "Formal", "C1"),
    ("", "ungeachtet", "—", "notwithstanding", "Ungeachtet aller Kritik hielt sie am Kurs fest.", "Notwithstanding all criticism she stuck to the course.", "Formal", "C1"),
    ("", "zugunsten", "—", "in favour of", "Der Antrag wurde zugunsten der Anwohner geändert.", "The application was changed in favour of the residents.", "Formal", "C1"),
]

KEYS = ('article', 'german', 'plural', 'english', 'exampleGerman',
        'exampleEnglish', 'category', 'level')

if __name__ == '__main__':
    out = [dict(zip(KEYS, row)) for row in CARDS]
    target = sys.argv[1] if len(sys.argv) > 1 else 'batch.json'
    with io.open(target, 'w', encoding='utf-8', newline='') as handle:
        handle.write(json.dumps(out, ensure_ascii=False))
    print('batch size: %d' % len(out))
