"""Generate lib/vocab_motion.dart from the line-icon mapping.

The TSV is the record; the Dart file is derived from it. Keeping the motion in
the same row as the icon means one place says what a word looks like and how it
moves, rather than two files that drift apart.

`tool/check_line_icons.py` fails the build when the generated file disagrees
with the mapping, so regenerating is not something anyone has to remember.

Usage:
    python tool/build_vocab_motion.py --write
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAP = os.path.join(ROOT, 'tool', 'vocab_line_icons.tsv')
OUT = os.path.join(ROOT, 'lib', 'vocab_motion.dart')

MOTIONS = ('none', 'travel', 'rock', 'pulse', 'rise', 'fade', 'spin')

HEADER = '''/// How each pictogram moves. Generated by tool/build_vocab_motion.py.
///
/// Do not edit by hand: the record is tool/vocab_line_icons.tsv, and
/// tool/check_line_icons.py fails the build when this file disagrees with it.
///
/// Motion is here because a verb is not a thing. A still pictogram of a plane
/// says "plane"; the same pictogram travelling says "to fly". That is the part
/// a picture of a noun never had to do, and it is why animated stock footage
/// looked worth having -- but the motion is the meaningful half, and we can
/// author that ourselves for nothing.
library;

/// The kinds of movement a pictogram can carry.
enum VocabMotion {
  /// Still. Plenty of words are better served by not moving.
  none,

  /// Crosses the tile and comes back: going, sending, arriving.
  travel,

  /// Tips side to side: working, cleaning, using a thing.
  rock,

  /// Breathes: speaking, mattering, being noticed.
  pulse,

  /// Lifts: getting up, learning, improving.
  rise,

  /// Dims: sleeping, tiring, ending.
  fade,

  /// Turns: time, repetition, exchange.
  spin,
}

'''


def rows():
    out = []
    for number, line in enumerate(io.open(MAP, encoding='utf-8'), 1):
        line = line.rstrip('\n')
        if not line.strip() or line.startswith('#'):
            continue
        parts = line.split(chr(9))
        if len(parts) < 4:
            raise SystemExit('%s line %d: expected 4 fields, got %d'
                             % (MAP, number, len(parts)))
        if parts[3] not in MOTIONS:
            raise SystemExit('%s line %d: "%s" is not a motion (%s)'
                             % (MAP, number, parts[3], ', '.join(MOTIONS)))
        out.append((parts[0], parts[1], parts[3]))
    return out


def render(data):
    lines = [HEADER]
    lines.append('/// Card id to the movement its pictogram carries.\n')
    lines.append('const Map<String, VocabMotion> vocabMotions = '
                 '<String, VocabMotion>{\n')
    for cid, german, motion in data:
        lines.append("  '%s': VocabMotion.%s, // %s\n" % (cid, motion, german))
    lines.append('};\n')
    return ''.join(lines)


def main():
    data = rows()
    text = render(data)
    if '--write' in sys.argv:
        io.open(OUT, 'w', encoding='utf-8', newline=chr(10)).write(text)
        print('wrote %s with %d entries' % (
            os.path.relpath(OUT, ROOT), len(data)))
        return 0
    current = io.open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
    if current.replace(chr(13), '') == text:
        print('%d entries, generated file is current' % len(data))
        return 0
    print('%d entries, generated file is STALE' % len(data))
    print('Run: python tool/build_vocab_motion.py --write')
    return 1


if __name__ == '__main__':
    sys.exit(main())
