#!/usr/bin/env python3
"""Keeps the generated compound table honest.

lib/vocab_compounds.dart is generated. Three ways it rots silently:

  * a part points at a card id that no longer exists, so the breakdown never
    renders and nobody notices -- the same silent hole that lost 368 drawings;
  * a card is listed as its own part, which renders as "X is built from X";
  * the file is hand-edited, making the generator's record wrong and the next
    regeneration a surprise.

Run: python tool/check_vocab_compounds.py
"""

from __future__ import annotations

import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TABLE = os.path.join(ROOT, 'lib', 'vocab_compounds.dart')


def main() -> int:
    problems = []
    if not os.path.exists(TABLE):
        print('Compound check failed:\n\n  - lib/vocab_compounds.dart missing.')
        return 1
    text = io.open(TABLE, encoding='utf-8').read()

    if 'Generated by tool/build_vocab_compounds.py' not in text:
        problems.append(
            'lib/vocab_compounds.dart has lost its generated-by header.'
        )

    entries = re.findall(
        r"'([^']+)': VocabCompound\('([^']*)', '([^']*)', '([^']*)'\)", text
    )
    if not entries:
        problems.append('lib/vocab_compounds.dart contains no entries.')

    known = set()
    german = {}
    lib = os.path.join(ROOT, 'lib')
    field = (r"id: '([^']*)'[^)]*?article: '[^']*'[^)]*?german: '([^']*)'")
    for name in sorted(os.listdir(lib)):
        if name.startswith('vocabulary') and name.endswith('.dart'):
            body = io.open(os.path.join(lib, name), encoding='utf-8').read()
            for cid, word in re.findall(field, body, re.S):
                known.add(cid)
                german.setdefault(cid, word)

    ids = [e[0] for e in entries]
    if len(ids) != len(set(ids)):
        problems.append('duplicate card ids in lib/vocab_compounds.dart.')

    for cid, modifier, head, link in entries:
        for role, part in (('card', cid), ('modifier', modifier), ('head', head)):
            if part not in known:
                problems.append(
                    '%s references a %s (%s) that is not a card, so the '
                    'breakdown would never render.' % (cid, role, part)
                )
        if modifier == cid or head == cid:
            problems.append(
                '%s (%s) is listed as its own part.'
                % (cid, german.get(cid, '?'))
            )
        if link and len(link) > 3:
            problems.append(
                '%s has a %d-character linking element, which is not a '
                'Fugenelement but a bad split.' % (cid, len(link))
            )

    if problems:
        print('Compound check failed:\n')
        for problem in problems[:20]:
            print('  - %s' % problem)
        if len(problems) > 20:
            print('  ... and %d more' % (len(problems) - 20))
        return 1

    print('Compound check passed: %d compounds, every part a real card.'
          % len(entries))
    return 0


if __name__ == '__main__':
    sys.exit(main())
