#!/usr/bin/env python3
"""Keeps the generated emoji table honest.

lib/vocab_emoji.dart is generated from Unicode's German annotations. Three
things can rot without anything failing to build:

  * an entry can point at a card id that no longer exists, and simply never
    appear -- the same silent hole that lost 368 drawings once already;
  * an entry can collide with a card that has since been given a real drawing,
    where the emoji would be the worse picture of the two;
  * the file can be hand-edited, which makes the generator's record wrong and
    the next regeneration a surprise.

Run: python tool/check_vocab_emoji.py
"""

from __future__ import annotations

import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TABLE = os.path.join(ROOT, 'lib', 'vocab_emoji.dart')

FIELD = r"id: '([^']*)'"


def main() -> int:
    problems = []

    if not os.path.exists(TABLE):
        print('Vocabulary emoji check failed:\n\n  - lib/vocab_emoji.dart is missing.')
        return 1
    text = io.open(TABLE, encoding='utf-8').read()

    if 'Generated by tool/build_vocab_emoji.py' not in text:
        problems.append(
            'lib/vocab_emoji.dart has lost its generated-by header, so nobody '
            'reading it knows not to edit it by hand.'
        )

    entries = re.findall(r"'([^']+)': '([^']+)',", text)
    ids = [cid for cid, _ in entries]
    if len(ids) != len(set(ids)):
        problems.append('lib/vocab_emoji.dart contains duplicate card ids.')

    known = set()
    lib = os.path.join(ROOT, 'lib')
    for name in sorted(os.listdir(lib)):
        if name.startswith('vocabulary') and name.endswith('.dart'):
            body = io.open(os.path.join(lib, name), encoding='utf-8').read()
            known |= set(re.findall(FIELD, body))

    for cid in ids:
        if cid not in known:
            problems.append(
                '%s has an emoji but is not a card. The entry would never '
                'appear.' % cid
            )

    drawn = set()
    for folder in ('vocab', 'vocab_line'):
        path = os.path.join(ROOT, 'assets', folder)
        if os.path.isdir(path):
            drawn |= {f[:-4] for f in os.listdir(path) if f.endswith('.svg')}
    overlap = sorted(set(ids) & drawn)
    if overlap:
        problems.append(
            'these cards have both a drawing and an emoji, so the emoji is '
            'dead weight: %s. Regenerate with '
            'python tool/build_vocab_emoji.py --write'
            % ', '.join(overlap[:8])
        )

    # An empty box helps nobody. Anything outside the pictograph ranges, or in
    # the too-new set the generator filters, must not have got through.
    for cid, emoji in entries:
        for char in emoji:
            if char in '‍️':
                continue
            point = ord(char)
            if not (point >= 0x1F000 or 0x2600 <= point <= 0x27BF):
                problems.append(
                    '%s maps to U+%04X, which is punctuation or notation '
                    'rather than a picture.' % (cid, point)
                )

    if problems:
        print('Vocabulary emoji check failed:\n')
        for problem in problems:
            print('  - %s' % problem)
        return 1

    print('Vocabulary emoji check passed: %d entries, every one a real card '
          'with no drawing of its own.' % len(ids))
    return 0


if __name__ == '__main__':
    sys.exit(main())
