#!/usr/bin/env python3
"""Keeps the separable-verb table from teaching the opposite of the rule.

This is the only animated grammar in the app, and the reason it is animated is
that the prefix moving to the end of the clause IS the rule. That also makes it
the only place where a wrong entry actively teaches a wrong sentence: animating
`wiederholen` as separable teaches "Ich hole wieder", which is a different verb
from "Ich wiederhole".

So the guard is stricter than for the other generated tables.

Run: python tool/check_separable_verbs.py
"""

from __future__ import annotations

import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TABLE = os.path.join(ROOT, 'lib', 'separable_verbs.dart')

NEVER_SEPARABLE = {
    'be', 'emp', 'ent', 'er', 'ge', 'miss', 'ver', 'zer', 'voll',
    'über', 'unter', 'um', 'durch', 'hinter', 'wider',
}

FIELD = (r"id: '([^']*)'[^)]*?article: '([^']*)'[^)]*?german: '([^']*)'"
         r"[^)]*?english: '([^']*)'")


def main() -> int:
    problems = []
    if not os.path.exists(TABLE):
        print('Separable-verb check failed:\n\n  - lib/separable_verbs.dart missing.')
        return 1
    text = io.open(TABLE, encoding='utf-8').read()

    if 'Generated by tool/build_separable_verbs.py' not in text:
        problems.append('lib/separable_verbs.dart lost its generated-by header.')

    entries = re.findall(
        r"'([^']+)': SeparableVerb\('([^']*)', '([^']*)'\)", text
    )
    if not entries:
        problems.append('lib/separable_verbs.dart contains no entries.')

    cards = {}
    lib = os.path.join(ROOT, 'lib')
    for name in sorted(os.listdir(lib)):
        if name.startswith('vocabulary') and name.endswith('.dart'):
            body = io.open(os.path.join(lib, name), encoding='utf-8').read()
            for cid, article, german, english in re.findall(FIELD, body, re.S):
                cards.setdefault(cid, (article, german, english))

    for cid, prefix, stem in entries:
        if cid not in cards:
            problems.append('%s is not a card.' % cid)
            continue
        article, german, english = cards[cid]
        low = german.strip().lower()

        if prefix != prefix.lower():
            problems.append(
                '%s (%s) has a capitalised prefix "%s". A separable prefix is '
                'never capitalised inside the verb.' % (cid, german, prefix)
            )
        if prefix in NEVER_SEPARABLE:
            problems.append(
                '%s (%s) uses "%s", which never detaches. Animating it teaches '
                'a sentence that is wrong.' % (cid, german, prefix)
            )
        if not low.startswith(prefix):
            problems.append(
                '%s (%s) does not start with its prefix "%s".'
                % (cid, german, prefix)
            )
        if not english.strip().lower().startswith('to '):
            problems.append(
                '%s (%s) is not glossed as a verb, so it does not conjugate '
                'and must not be animated as though it did.' % (cid, german)
            )
        if article in ('der', 'die', 'das'):
            problems.append('%s (%s) is a noun.' % (cid, german))

    # The prefix rules cannot catch every trap, and the worst one proves it:
    # "wieder" is genuinely separable in wiedersehen and genuinely is not in
    # wiederholen, so no rule over prefixes can tell them apart. That is what
    # the hand-written exclusions file is for, and its entire value is that
    # entries stay out. Regenerating must not quietly readmit one.
    excluded = os.path.join(ROOT, 'tool', 'separable_verbs_excluded.tsv')
    listed = {}
    if os.path.exists(excluded):
        for line in io.open(excluded, encoding='utf-8'):
            line = line.rstrip(chr(10))
            if not line.strip() or line.lstrip().startswith('#'):
                continue
            parts = line.split(chr(9))
            if len(parts) >= 3:
                listed[parts[0]] = (parts[1], parts[2])
    else:
        problems.append(
            'tool/separable_verbs_excluded.tsv is gone. It is the only thing '
            'keeping wiederholen out of an animation that would teach '
            '"Ich hole wieder".'
        )
    present = {cid for cid, _, _ in entries}
    for cid, (german, reason) in listed.items():
        if cid in present:
            problems.append(
                '%s (%s) is excluded but present in the table. %s'
                % (cid, german, reason)
            )

    if problems:
        print('Separable-verb check failed:\n')
        for problem in problems[:20]:
            print('  - %s' % problem)
        if len(problems) > 20:
            print('  ... and %d more' % (len(problems) - 20))
        return 1

    print('Separable-verb check passed: %d verbs, all genuinely separable.'
          % len(entries))
    return 0


if __name__ == '__main__':
    sys.exit(main())
